### ISSUE TITLE
How to read account balance? 

### ISSUE THREAD

**Issue by alvinsgithub** [NoahZinsmeister/web3-react#10]
It seems like useAccountBalancefrom "web3-react/hooks" is removed in the latest version.

**Comment by NoahZinsmeister** [comment]
Hi @alvinsgithub!

You're absolutely right. After some thinking, I decided that it didn't make sense for me to bundle a bunch of ad hoc hooks alongside the core web3 management logic, so I've removed all of them. My suggestion for now (at least until there's a robust library for ethereum-related hooks), is to simply implement these as necessary in your project.

Here are the relevant APIs in [ethers.js](https://docs.ethers.io/ethers.js/html/api-providers.html#account) and [web3.js](https://web3js.readthedocs.io/en/1.0/web3-eth.html#getbalance).

Hope this helps, let me know if you have any other questions!
