### ISSUE TITLE
Ledger connector The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by vanmoortel** [NoahZinsmeister/web3-react#104]
**Bug Description**
Hello,
Many of my users using Ledger have this kind of error when they interact with smart contract:
`The method eth_sendTransaction does not exist/is not available`
Has anyone ever had this kind of trouble before?
I specify that with the other connectors it works.
I use Infura as RPC provider.

**Reproduction**
```
// Helper to make write request to smart contract
// and dispatch success(after 1 confirmation) or error
export const sendContract = function* (action, method, methodParams, callParams) {
  try {
    const receiptResult = yield new Promise((res, rej) => {
      action.data.contract.methods[method](...methodParams).send(...callParams)
        .on('confirmation', (confirmationNumber, receipt) => {
          if (confirmationNumber) res({ confirmationNumber, receipt });
        }).on('error', rej);
    });
    yield put({ data: receiptResult, type: onSuccess(action.type) });
  } catch (error) {
    yield put({ data: error, type: onError(action.type) });
  }
};
```
https://github.com/vanmoortel/lrc-staking-dapp/blob/master/src/utils/simpleContractFetching.js

**Comment by mirshko** [comment]
I’m having an issue with DataCloneError after upgrading to the latest core and walletconnect package. If I remove the await statement on my contract I get this same method error.

@NoahZinsmeister, did something change with the core?

**Comment by mirshko** [comment]
@vanmoortel are you running 6.1.1 version of the core package?
