### ISSUE TITLE
Network Connector Error: Unhandled Runtime Error: could not detect network

### ISSUE THREAD

**Issue by brennanfife** [NoahZinsmeister/web3-react#105]
**Bug Description**
Seems with the recent network connector update, there is a bug that won't allow you to connect

<img width="960" alt="Screen Shot" src="https://user-images.githubusercontent.com/31396350/85594340-7612e000-b60d-11ea-8fd2-b8b4b87ed9ff.png">

**Reproduction**
CodeSandbox doesn't produce the error, yet other teammates have reproduced this

Steps to reproduce:
1. Download the example inside the repo
2. Switch to the network provider

**Expected Behavior**
Connect to network using the Network Provider

**Comment by mirshko** [comment]
@brennanfife @NoahZinsmeister the example is frozen so its not actually using the latest versions of the package. 

@NoahZinsmeister this is a severe bug, it seems that regardless of the network the latest versions are broken.

**Comment by NoahZinsmeister** [comment]
thanks @brennanfife @mirshko , i see the problem, working on it!

**Comment by NoahZinsmeister** [comment]
should be fixed in @web3-react/network-connector@6.1.3! thanks for the report
