### ISSUE TITLE
Contract call

### ISSUE THREAD

**Issue by jacklp** [NoahZinsmeister/web3-react#108]
I am just trying to learn how to use this library, is it possible to call a contract method through this or will I need to use another library for that?

**Comment by mirshko** [comment]
Nope! This library just exposes the provider's web3 library itself, either through Web3.js or ethers.js.

You'd generally use the ethers `Contract` function with your ABI and contract address and the web3 provider (which you can use the `library` variable exposed bu this hook for) to init a contract and do all calls against that

**Comment by nemixe** [comment]
sorry, can you show the example @mirshko ?, thanks.
