### ISSUE TITLE
Can I see any simple example react app?

### ISSUE THREAD

**Issue by jinserk** [NoahZinsmeister/web3-react#11]
I'm a newbie of react and web3. As trying to make my first react app using this package but it shows a vacant page, so it will be great help to see any kind of example I can refer to. Could you provide any simple example from the scratch?

**Comment by NoahZinsmeister** [comment]
Hi @jinserk! Let me know if this [CodeSandbox demo](https://codesandbox.io/embed/6v5nrq2nqw) answers any of your questions.

**Comment by jinserk** [comment]
Oh, I didn't know that. I checked the demo and works until I found some exception when I am using Chrome browser. By the way, how can I make the app like what you added the animated GIF in README file? Do I need to add css and logo images by myself, or does it support in default?

**Comment by NoahZinsmeister** [comment]
Yes, you'll need to configure all the UI by yourself :)

**Comment by jinserk** [comment]
Thank you @NoahZinsmeister! for sharing the project and prompt reply! :)
