### ISSUE TITLE
Remove deprecated metamask APIs

### ISSUE THREAD

**Issue by ebceu4** [NoahZinsmeister/web3-react#110]
**Deprecated APIs**

- MetaMask will soon stop reloading pages on network change.
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' on initialization.
- The event 'networkChanged' is deprecated and may be removed in the future.
Please use 'chainChanged' instead.
- The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
- 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.

**Additional links on new apis**
https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
https://eips.ethereum.org/EIPS/eip-1193

**Comment by mirshko** [comment]
@NoahZinsmeister https://medium.com/metamask/breaking-changes-to-the-metamask-provider-its-happening-eebc91fff1a7

this change is coming very soon, can we get an updated metamask connector asap?

**Comment by paulrberg** [comment]
I think the change has already happened, as of Jan 14, 2021:

[Breaking Changes to the MetaMask Provider are Here](https://medium.com/metamask/breaking-changes-to-the-metamask-provider-are-here-7b11c9388be9)

**Comment by paulrberg** [comment]
Sorry to follow up but this is quite an important update that needs to be made.

@NoahZinsmeister, any chance you could take a look, or give someone you trust permission to write to GitHub and the Npm registry?

**Comment by lazarmitic** [comment]
This has not been fixed yet?

**Comment by ahmadina** [comment]
This has not been fixed yet?!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
