### ISSUE TITLE
Error when switching network/account on metamask (example code)

### ISSUE THREAD

**Issue by LRUki** [NoahZinsmeister/web3-react#127]
**Bug Description**
I get "Error: underlying network changed" after switching account or network on the example code.

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. press inject to connect to metamask
2. switch network/account on metamsk

**Expected Behavior**
update the network/account info without throwing an error

**Additional Context**

**Comment by xiphiness** [comment]
also getting this, looking for a fix. error is happening in ethers BaseProvider.getTransactionCount, not sure where it's called, not the most useful stack trace

**Comment by TBouder** [comment]
I cannot access the CodeSandbox reproduction, but I had the same issue with [ethersjs](https://github.com/ethers-io/ethers.js). This [issue](https://github.com/ethers-io/ethers.js/issues/866) could help you.

The workaround with ethers.js is the following code, when using `new ethers.providers.Web3Provider`
```
const getLibrary = (provider, connector) => {
	return new ethers.providers.Web3Provider(provider, 'any')
};
```
instead of 
```
const getLibrary = (provider, connector) => {
	return new ethers.providers.Web3Provider(provider)
};
```

**Comment by thecryptoneer** [comment]
```
const getLibrary = (provider, connector) => {
	return new ethers.providers.Web3Provider(provider, 'any')
};
```

the above code fails if you call library.getSigner(account).signMessage(message) from inside the metamask in-app broswer I noticed yesterday.

I replaced it by: 
```
import { Web3Provider } from '@ethersproject/providers'
const POLLING_INTERVAL = 12000
...
const library = new Web3Provider(provider)
library.pollingInterval = POLLING_INTERVAL
return library
```
