### ISSUE TITLE
Add Portis to the CodeSandbox exmaple

### ISSUE THREAD

**Issue by radotzki** [NoahZinsmeister/web3-react#13]
I forked the CodeSandbox example and added Portis as an optional provider:
https://codesandbox.io/s/xj7613p044

I believe it will be useful for devs if it will appear in the official example :)

**Comment by NoahZinsmeister** [comment]
Thanks @radotzki ! I was worried about exposing my dApp ID, but since you seem to be willing to do so, I incorporated your change into the official example :)
