### ISSUE TITLE
Issue: connector.on is not a function 

### ISSUE THREAD

**Issue by pi0neerpat** [NoahZinsmeister/web3-react#134]
**Bug Description**

I've used this library in existing apps and found it to be useful, but setting it up in a new app is pretty difficult. The docs don't actually describe how to use this tool, and assume some prior knowledge that I don't have. The example is too complex and poorly organized. Any help is appreciated.

The error I'm getting: `connector.on is not a function`. This is in a brand new app. Do I need `@web3-react/injected-connector` ? Its not clear.

```json
    "@ethersproject/providers": "^5.0.6",
    "@redwoodjs/forms": "^0.20.0",
    "@redwoodjs/router": "^0.20.0",
    "@redwoodjs/web": "^0.20.0",
    "@web3-react/core": "^6.1.1",
    "@web3-react/injected-connector": "^6.0.7",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
```

Provider is in `index.js`

```js
import ReactDOM from 'react-dom'
import { RedwoodProvider, FatalErrorBoundary } from '@redwoodjs/web'
import FatalErrorPage from 'src/pages/FatalErrorPage'

import { Web3Provider } from '@ethersproject/providers'
import { Web3ReactProvider } from '@web3-react/core'

import Routes from 'src/Routes'

import DefaultLayout from 'src/layouts/DefaultLayout'

import './scaffold.css'
import './index.css'

function getLibrary(provider, connector) {
  return new Web3Provider(provider) // this will vary according to whether you use e.g. ethers or web3.js
}

ReactDOM.render(
  <FatalErrorBoundary page={FatalErrorPage}>
    <RedwoodProvider>
      <Web3ReactProvider getLibrary={getLibrary}>
        <DefaultLayout>
          <Routes />
        </DefaultLayout>
      </Web3ReactProvider>
    </RedwoodProvider>
  </FatalErrorBoundary>,
  document.getElementById('redwood-app')
```
And calling activate here

```js
const DefaultLayout = ({ children }) => {
  const { activate } = useWeb3React()

  return (
    <>
      <div className="rw-button-group">
        <button
          onClick={() => activate('injected')}
          className="rw-button rw-button-blue"
        >
          Connect
        </button>
      </div>
      {account}
      {children}
    </>
  )
}
```

**Comment by ahtashamabbasse** [comment]
I'm facing the same issue, did you get any work around?

**Comment by ahtashamabbasse** [comment]
@pi0neerpat I've found the solution below mention code snippet is life savior for me. 🚀

```
import { InjectedConnector } from '@web3-react/injected-connector';
export const injected = new InjectedConnector({ supportedChainIds: [1, 3, 4, 5, 42] });

activate(injected);
```

**Comment by self-coding-crab** [comment]
Sometimes connector returns 'injected' string

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
