### ISSUE TITLE
Rename packages that don't depend on React 

### ISSUE THREAD

**Issue by DannyDelott** [NoahZinsmeister/web3-react#139]
**Description**
Packages like `@web3-react/abstract-connector` don't actually depend on React at all.

Can we rename these packages so that is more clear? `@web3-suite/abstract-connector`, or `@web3-toolkit/abstract-connector`.

**Additional Context**

It's common practice to structure logic and UI separately, and it's confusing to see the "react" keyword in files that don't (and shouldn't) contain any UI logic.

**Comment by NoahZinsmeister** [comment]
while the parent name for this project is always going to be web3-react, the v8 actually uses vanilla zustand stores which are fully agnostic of react! so, it's easier than ever to use the package without needing react
