### ISSUE TITLE
updating MetaMask state

### ISSUE THREAD

**Issue by jinserk** [NoahZinsmeister/web3-react#14]
Hi @NoahZinsmeister!

Sorry for opening another issue here but I cannot still understand well the structure of `web3-react` and the `context` which could be fetched from `useWebContext()`. Here,
```
import React, { Component, Fragment, useEffect } from "react";
import Web3Provider, { Connectors, useWeb3Context } from "web3-react";

const { InjectedConnector } = Connectors;
const MetaMask = new InjectedConnector();
const connectors = { MetaMask };

function 
function MetaMaskComponent() {
  const context = useWeb3Context();

  useEffect(() => {
    context.setConnector("MetaMask")
  }, []);

  return ({ context.active ? <MyComponent /> : "None" });
}

class App extends Component {
  render() {
    return (
      <Web3Provider connectors={connectors} libraryName="ethers.js">
        <div className="App">
          <MetaMaskComponent />
        </div>
      </Web3Provider>
    );
  }
}

export default App;
```
Once `context.setConnector("MetaMask")` called and it sets the `context.active` as `true`, and if I logout MetaMask, I wonder what happens in `context`? Currenty I'm using the unstable version of `web3-react` (v 3.1.3) and it seems it doesn't update any of `context` properly, so it keeps still the `active` as `true` and `connector` as `MetaMask`. Is there any way to render components according to the MetaMask's login status without external reload of the page? In other words, can I know the MetaMask's login status from the `connector` or `context`?

**Comment by jinserk** [comment]
In my humble opinion, we need to add some `context.updateConnector()` method to support the MetaMask's status of "connected already but not logged in". Currently `useWeb3Context()` has only `setConnector()` and `unsetConnector()` method, so cannot handle such status properly. Please let me know if you have any.

**Comment by NoahZinsmeister** [comment]
You're correct that if you activate the MetaMask connector, and then log out of Metamask, the context will still (incorrectly) maintain active. This is because MetaMask emits no events indicating logout. If they did, we could simply call [one of the manager functions](https://github.com/NoahZinsmeister/web3-react/tree/next#manager-functions) (of which `setConnector` and `unsetConnector` are only 2) from within the `InjectedConnector`. Since this isn't the case though, the only way to achieve something like this would be manually polling, probably within a custom connector. Not sure this would be worth it, seems like a bit of an edge case to deal with.

Also, the manager functions are meant to be very simple: all logic more complex than setting/unsetting connectors should be exposed via functions on a particular connector, so instead of calling `context.updateConnector`, the pattern would be to call `context.activeConnector.blah`.

**Comment by jinserk** [comment]
Hmm. I didn't know that MetaMask emits no events on logout. Temporarily I updated my code to:
```
function MetaMaskComponent() {
  const context = useWeb3Context();

  useEffect(() => {
    console.log(context);
    context.active || context.setConnector("MetaMask");
    context.account || context.unsetConnector("MetaMask");
  }, [context]);

  return (
    context.active
    ? ( context.account ? <MyComponent /> : <AccountUnavailable /> )
    : <Web3Unavailable />
  );
}
```
so if `context.account` changed to `null`, it calls `unsetConnector()` to disconnect the connector. I don't know this is the best option we can choose. I guess I can utilize `Web3State` or something but don't know how to..

**Comment by NoahZinsmeister** [comment]
@jinserk great solution!

So the default behavior around this is slightly different in the newest release (`4.0.0` - get it with `yarn add web3-react`) - if a user logs out of metamask after successfully logging in, the metamask connector _will be unset_ and a global error will be set with code `InjectedConnector.errorCodes.UNLOCK_REQUIRED`. So under your scheme, you likely want to include something like:

```
  useEffect(() => {
    if (context.error && context.error.code === InjectedConnector.errorCodes.UNLOCK_REQUIRED) {
      context.setConnector("MetaMask")
    }
  }, [context.error]);
```

Let me know if that makes sense!

**Comment by jinserk** [comment]
Thanks @NoahZinsmeister! for the update! I've tested new version and it works well. By the way, I doubt if I have to check the `context.error` since the `context.active` will be `false` if the logout triggers the connector to be unset, so we can just monitor `context.active` to call `context.setConnector("MetaMask")`.

**Comment by NoahZinsmeister** [comment]
Amazing! Thanks for trying this all out, let me know if you have any other issues :)
