### ISSUE TITLE
About ledger connector

### ISSUE THREAD

**Issue by EdsonAlcala** [NoahZinsmeister/web3-react#143]
Hello,

I have been working with the ledger connector and I have some questions that hopefully you can help me understand so that I can contribute !

Basically those lines:

- https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/ledger-connector/src/index.ts#L57
- https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/ledger-connector/src/index.ts#L58

Could you tell why are those lines required?

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
