### ISSUE TITLE
How can I use web3-react ... without React? : )

### ISSUE THREAD

**Issue by AoDev** [NoahZinsmeister/web3-react#144]
**Description**
Soo, I am pretty new to web3 development and I see that this library is used in many projects.

I am interested in all the management part of the connexion, providers/connectors, etc... but I'd like to be able to use all that without having to mount the UI.

What I'm looking for is a way to reuse most of this project's code but the "data / state manager" wouldn't be implemented in a React context, just a plain JS module. Is that possible without too much effort?

**Comment by dimiandre** [comment]
https://web3js.readthedocs.io/en/v1.3.0/getting-started.html#adding-web3-js
