### ISSUE TITLE
Error: Invariant failed: A root already exists for provided key

### ISSUE THREAD

**Issue by platocrat** [NoahZinsmeister/web3-react#145]
I'm currently using `createWeb3ReactRoot()` in my `index.ts` file of my React app:
```ts
const Web3ProviderNetwork = createWeb3ReactRoot("INFURA_PROJECT_ID")
```

The home page loads fine on the first render, but on the second render, I get this error:
```
Error: Invariant failed: A root already exists for provided key
```

Wondering why this happens. Also wondering what key are we supposed to use in the function. Is it the Infura Project ID, or Project Secret?

**Comment by self-coding-crab** [comment]
Is this bug resolved?

**Comment by StKostyantin** [comment]
@platocrat Why did you close the issue? Can you please write how you solved the problem?

**Comment by StKostyantin** [comment]
Bub and quick fix #176

**Comment by platocrat** [comment]
> @platocrat Why did you close the issue? Can you please write how you solved the problem?

Tbh, I think I never solved the issue and switched to using pure React instead. That's all I can remember, but wish I could provide more info

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by annguyen97dev** [comment]
I solved this problem by way:

const Web3ProviderNetwork =
  typeof window !== "undefined" && createWeb3ReactRoot(NetworkContextName);

  <Web3ReactProvider getLibrary={getLibrary}>
      {typeof window !== "undefined" ? (
        //@ts-ignore
        <Web3ProviderNetwork getLibrary={getLibrary}>
          <Children />
        </Web3ProviderNetwork>
      ) : (
        <Children />
      )}
    </Web3ReactProvider>
