### ISSUE TITLE
Deprecate Squarelink connector

### ISSUE THREAD

**Issue by freeatnet** [NoahZinsmeister/web3-react#147]
**Description**

Hey Noah! Thanks for making `web3-react`!

It looks like the Squarelink adapter can be deprecated as Squarelink has shut down their wallet. I can't find any blog posts about it, but I received the following email:

> Dear Squarelink User,
> 
> Thank you for your continuous support of our project in the past few years. We are happy to have supported the Ethereum, DApp, and DeFi communities. Unfortunately, we are unable to continue supporting our wallet and we will be terminating service indefinitely starting on **DECEMBER 16TH, 2020.**
> You are being notified because you may have funds remaining in your Squarelink wallet and you will need to export your accounts by DECEMBER 16TH, 2020. Squarelink is non-custodial, so we will be unable to export your accounts on your behalf. Any remaining accounts will be lost permanently.
> 
> […]
> We will send a weekly reminder email until you have exported your accounts or until DECEMBER 16TH, 2020. If you have any questions, please email contact@squarelink.com and we will do our best to respond in a timely fashion.
> 
> Sincerely,
> The Squarelink Team

Their wallet portal no longer resolves, either: https://app.squarelink.com/register

**Comment by NoahZinsmeister** [comment]
thanks @freeatnet ! deprecated and (mostly) scrubbed from the repo
