### ISSUE TITLE
Publish new version of npm (NetworkConnector does not work)

### ISSUE THREAD

**Issue by marekkirejczyk** [NoahZinsmeister/web3-react#149]
**Bug Description**
NetworkConnector does not work.

**Additional Context**
Working version is in the repository, but is not yet published as npm.

Would be great to publish it!

**Comment by LogvinovLeon** [comment]
FYI: It [is published](https://www.npmjs.com/package/@web3-react/network-connector/v/6.1.5), but tagged as `next` instead of `latest`.

**Comment by marekkirejczyk** [comment]
@LogvinovLeon Thanks for noticing :)
@NoahZinsmeister Would it make sense to release it as `latest`? Do you recommend using `next`?
