### ISSUE TITLE
WalletConnect-Connector support more than one chain

### ISSUE THREAD

**Issue by pmprete** [NoahZinsmeister/web3-react#152]
**Description**
Currently there is a restriction than walletconnnect-connector can only have 1 chain
`invariant(Object.keys(rpc).length === 1, '@walletconnect/web3-provider is broken with >1 chainId, please use 1')`
https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/walletconnect-connector/src/index.ts#L31

But this is no longer true, it can support multiple chains easily https://docs.walletconnect.org/quick-start/dapps/web3-provider#rpc-url-mapping

**Additional Context**
Removing this restriction would alow dapps to use mainnet and testnet as well as other networks

**Comment by edward-arinin-web-dev** [comment]
Faced same issue caused by adding multiple chains for BSC network while using WalletConnect Connector.
Any updates on this 🧐 ?

**Comment by anxolin** [comment]
+1

**Comment by MAkzent** [comment]
+1 curious if web3-react can use WalletConnect on Polygon (Matic)

**Comment by anxolin** [comment]
I went for it, and did a PR with the fix. Basically exposing all the WalletConnect interface. Also, it allows other ways of setting this up, in case you just want to provide a `infuraId` (or `infuraId` and the list of `supportedChainIds`).

i.e.

```ts
// We can specify any other network
const provider = new WalletConnectConnector({
 rpc: {
    1: "https://mainnet.mycustomnode.com",
    3: "https://ropsten.mycustomnode.com",
    100: "https://dai.poa.network",
    // ...
  },
});
```

```ts
const provider = new WalletConnectConnector({
  infuraId: "27e484dcd9e3efcfd25a83a78777cdf1",
  supportedChainIds: [1, 4, 100]
});
```


PR: https://github.com/NoahZinsmeister/web3-react/pull/185

Let me know if this solve the issue!

**Comment by MAkzent** [comment]
> I went for it, and did a PR with the fix. Basically exposing all the WalletConnect interface. Also, it allows other ways of setting this up, in case you just want to provide a `infuraId` (or `infuraId` and the list of `supportedChainIds`).
> 
> i.e.
> 
> ```ts
> // We can specify any other network
> const provider = new WalletConnectConnector({
>  rpc: {
>     1: "https://mainnet.mycustomnode.com",
>     3: "https://ropsten.mycustomnode.com",
>     100: "https://dai.poa.network",
>     // ...
>   },
> });
> ```
> 
> ```ts
> // We can specified just with an infuraId and an optional supportedChainIds
> const provider = new WalletConnectConnector({
>   infuraId: "27e484dcd9e3efcfd25a83a78777cdf1",
>   supportedChainIds: [1, 4, 100]
> });
> ```
> 
> PR: #185
> 
> Let me know if this solve the issue!

Very nice, thank you for that! 

Follow-up question about the WalletConnect connect logic:
Does the wallet, that I want to connect with, need to be connected to that same network as well? Or is it okay to request a connection to Polygon, while my wallet is connected to Mainnet? 

Thanks again!

**Comment by anxolin** [comment]
> Follow-up question about the WalletConnect connect logic:
Does the wallet, that I want to connect with, need to be connected to that same network as well? Or is it okay to request a connection to Polygon, while my wallet is connected to Mainnet?

I think your question is better suited in WalletConnect telegram channel. 
If i understand you correctly, your wallet connected by WC will tell the Dapp the current network. Depending in the network that is selected, for read operations your dapp will use the appropriate RPC endpoint specified in the setup of the connector. I'm not very familiar with Polygon, if it's a Ethereum compatible sidechain should work if you add the RPC endpoint there. But again, I think this issue is not the best place to ask this.

**Comment by asad97290** [comment]
const provider = new WalletConnectProvider({
      rpc: {
        56: "https://bsc-dataseed.binance.org",
      },
    });




trying to connect to the bsc main net but failed getting this error in the browser 
POSThttps://mainnet.infura.io/v3/
[HTTP/2 401 Unauthorized 1193ms]

**Comment by RabbitTerra** [comment]
Add this feature asap!

**Comment by pmprete** [comment]
Im currently using rLogin [@rsksmart/rlogin](https://www.npmjs.com/package/@rsksmart/rlogin) with [@rsksmart/rlogin-web3-react-connector](https://www.npmjs.com/package/@rsksmart/rlogin-web3-react-connector). Is similar to web3Modal and web3-react and works with multiple chains

**Comment by creativogee** [comment]
> const provider = new WalletConnectProvider({ rpc: { 56: "https://bsc-dataseed.binance.org", }, });
> 
> trying to connect to the bsc main net but failed getting this error in the browser POSThttps://mainnet.infura.io/v3/ [HTTP/2 401 Unauthorized 1193ms]

Currently having this issue too. Clearly specified polygon but it makes the first request to infura

**Comment by Iamkhova** [comment]
[ConnectWalletError]  TypeError: Cannot read properties of undefined (reading 'toString')
    at cleanChainId (ConnectWalletButton.tsx:186:1)
    at ConnectWalletButton.tsx:238:1
    at async getNetworkInfo (ConnectWalletButton.tsx:236:1)
    at async processWalletUser (ConnectWalletButton.tsx:259:1)
    at async handleConnect (ConnectWalletButton.tsx:264:1)
    at async ConnectWalletButton.tsx:278:1
    at async handleActivation (ConnectWalletButton.tsx:274:1)
    at async activateWalletConnect (ConnectWalletButton.tsx:296:1)
    at async webOptions (ConnectWalletButton.tsx:330:1)
    at async handleClose (ConnectWalletButton.tsx:387:1)

**Comment by ahmedaisar** [comment]
> > const provider = new WalletConnectProvider({ rpc: { 56: "https://bsc-dataseed.binance.org", }, });
> > trying to connect to the bsc main net but failed getting this error in the browser POSThttps://mainnet.infura.io/v3/ [HTTP/2 401 Unauthorized 1193ms]
> 
> Currently having this issue too. Clearly specified polygon but it makes the first request to infura

Hey mate,

I use below to connect Binance Testnet, it def works. Happy coding!

const providerOptions = {
        walletconnect: {
            package: WalletConnectProvider,
            options: {
                rpc: {
                    97: "https://data-seed-prebsc-2-s1.binance.org:8545/",
                }
            },
            qrcodeModalOptions: {
                mobileLinks: [
                    "metamask",
                    "trust",
                    "argent",
                    "rainbow",
                    "imtoken",
                    "pillar",
                ]
            }
        }
    };
    web3Modal = new Web3Modal({
        network: "mainnet",
        cacheProvider: false,
        providerOptions,
        theme: "dark",
        disableInjectedProvider: false,
    });

**Comment by hari7345** [comment]
> Faced same issue caused by adding multiple chains for BSC network while using WalletConnect Connector. Any updates on this 🧐 ?

have you solved this?
