### ISSUE TITLE
Allow to specify amount of accounts to request in ledgerConnector

### ISSUE THREAD

**Issue by ArinCantCode** [NoahZinsmeister/web3-react#155]
**Description**

Right now the `LedgerConnector` exposed method `.getAccount()` that returns a single account address of from the ledger.

```
  _proto.getAccount = function getAccount() {
    try {
      var _this9 = this;

      return Promise.resolve(_this9.provider._providers[0].getAccountsAsync(1).then(function (accounts) {
        return accounts[0];
      }));
    } catch (e) {
      return Promise.reject(e);
    }
  };
```

Simply changing that code to this:

```
  _proto.getAccount = function getAccount(accountNum) {
    try {
      var _this9 = this;

      return Promise.resolve(_this9.provider._providers[0].getAccountsAsync(accountNum).then(function (accounts) {
        return accounts
      }));
    } catch (e) {
      return Promise.reject(e);
    }
  };
```

Allows me to fetch the amount of accounts i want.

Would also be nice to set offset so that i can page the results but i didn't look into it.

**Comment by Tararan** [comment]
@ArinCantCode , @NoahZinsmeister  Is this possible now?
Documentation is not that good, and I have been trying to solve this issue for entire day yesterday. 

How would I grab multiple accounts so that I can give user ability to choose which one they want?

**Comment by ArinCantCode** [comment]
@Tararan i don't think this was ever solved, i think i used https://www.npmjs.com/package/patch-package to patch the lines i mentioned above. Once that is done it should just work.

**Comment by Tararan** [comment]
@ArinCantCode , thank you.
But, what do you do about following error that is thrown by LedgerSubprovider?

If I change code as you suggested and I attempt ledger.getAccount(20) it will throw this error:

![Screenshot 2021-05-31 at 21 29 32](https://user-images.githubusercontent.com/30859637/120234084-825cdf80-c257-11eb-84e4-6744ed17fc7f.png)

It will actually always throw this error unless I return return accounts[0].

All packages relating to web3-react are lates packages including ledger-connector

**Comment by ArinCantCode** [comment]
@Tararan I don't have access to the repository or ledger atm to really check it out :(

when you say:

`It will actually always throw this error unless I return return accounts[0].`

I guess it means that when you return `accounts[0]` but use `getAccountsAsync(accountNum)` it still throws? 

If i were you i would try to play around with the inputs, but i can't provide much input...

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
