### ISSUE TITLE
Does web3-react package supports web3.js?

### ISSUE THREAD

**Issue by dobpp** [NoahZinsmeister/web3-react#167]
**Bug Description**

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**

**Additional Context**

**Comment by JuanuMusic** [comment]
The documentation doesnt seem to explain much on how to use this package with pthe providers/connectors/etc.
I'm also struggling to understand how to connect a metamask wallet, or any other stuff...

I know this is open source but a small guid on doing the ntire flow (connecting wallets etc) would be great to start using this package, if not, people will move forward and find better alternatives.

**Comment by noobshow** [comment]
Does it support web3.js and how?

**Comment by talentlessguy** [comment]
web3-react is built around ethers.js but probably you can use it with web3.js, although it's not recommended
