### ISSUE TITLE
Selecting Accounts

### ISSUE THREAD

**Issue by flyingnobita** [NoahZinsmeister/web3-react#170]
When I connect to my Hardhat default wallet with the NetworkConnector, there are no accounts being selected. I try to select one with `library.getSigner(0)` but this didn't seem to work.

How do I select the accounts?

Also is interacting with the Library the correct approach to interact with the provider?  Or am I suppose to do this through a separate method (such as using Ethers.js)?

Thank you

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
