### ISSUE TITLE
network connector's fetch should specify Content-Type header

### ISSUE THREAD

**Issue by wildmolasses** [NoahZinsmeister/web3-react#173]
When connecting to a geth rpc endpoint (in this case L2 optimism) with the network connector, an error code 415 is received saying that the request payload must be 'application/json'

We can add the request header to the following line of the network-connector:

https://github.com/NoahZinsmeister/web3-react/blob/d0b038c748a42ec85641a307e6c588546d86afc2/packages/network-connector/src/index.ts#L63

Could add 

```js
        headers: {
          'Content-Type': 'application/json'
        },
```

Submitted a PR!

**Comment by Velenir** [comment]
This issue prevents using NetworkConnector with Avalanche https://api.avax.network/ext/bc/C/rpc rpc
By default `fetch(url, {method: "POST"})` sends a request with `Content-Type: text/plain`
```sh
curl --location --request POST 'https://api.avax.network/ext/bc/C/rpc' \
--header 'content-type: text/plain' \
--header 'accept: */*' \
--data-raw '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}'
```
which results in `invalid content type, only application/json is supported`

Some other rpc enpoints for other chains may handle `text/plain` alright and parse it as JSON it anyway, but some clearly can't

**Comment by ImmodestExtant** [comment]
Same error on Celo and Harmony, too.

**Comment by Venoox** [comment]
+1 same issue on Cronos
