### ISSUE TITLE
createWeb3ReactRoot not working with SSR(Nextjs)

### ISSUE THREAD

**Issue by StKostyantin** [NoahZinsmeister/web3-react#176]
**Bug Description**
If I try to use createWeb3ReactRoot with nextjs - I get an error:
"Error: Invariant failed: A root already exists for provided key INFURA"

A quick fix looks like this

```
const Web3ProviderNetwork =
   process.browser && createWeb3ReactRoot (NetworkContextName);

<Web3ReactProvider getLibrary = {getLibrary}>
     {process.browser? (
       // @ ts-ignore
       <Web3ProviderNetwork getLibrary = {getLibrary}>
           {children}
       </Web3ProviderNetwork>
     ): children}
   </Web3ReactProvider>

```
But it seems to me that this bug should be fixed.

**Comment by OgierDeBusbecq** [comment]
This solution didn't work for me, but I found another solution [here](https://githubmemory.com/repo/eenagy/uni-wallet). I agree it would be nice if this bug was fixed.

**Comment by eenagy** [comment]
Use dynamic loading for next.js

Define provider `components/defaultprovider.js`
```js
import { createWeb3ReactRoot } from '@web3-react/core'
import { DefaultProviderName } from 'src/constants'


const Web3ReactProviderDefault = createWeb3ReactRoot(DefaultProviderName)

const Web3ReactProviderDefaultSSR = ({ children, getLibrary }) => {
  return (
    <Web3ReactProviderDefault getLibrary={getLibrary}>
      {children}
    </Web3ReactProviderDefault>
  )
}

export default Web3ReactProviderDefaultSSR;
```

Load it without SSR in `_app.js`

```js
const Web3ReactProviderDefault = dynamic(
  () => import('../components/defaultprovider'),
  { ssr: false }
)



const App = ({ Component, pageProps }) => {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <Web3ReactProviderDefault getLibrary={getLibrary}>
        <Component {...pageProps} />
      </Web3ReactProviderDefault>
    </Web3ReactProvider>
  )
}

```

**Comment by maximgeerinck** [comment]
> Use dynamic loading for next.js
> 
> Define provider `components/defaultprovider.js`
> 
> ```js
> import { createWeb3ReactRoot } from '@web3-react/core'
> import { DefaultProviderName } from 'src/constants'
> 
> 
> const Web3ReactProviderDefault = createWeb3ReactRoot(DefaultProviderName)
> 
> const Web3ReactProviderDefaultSSR = ({ children, getLibrary }) => {
>   return (
>     <Web3ReactProviderDefault getLibrary={getLibrary}>
>       {children}
>     </Web3ReactProviderDefault>
>   )
> }
> 
> export default Web3ReactProviderDefaultSSR;
> ```
> 
> Load it without SSR in `_app.js`
> 
> ```js
> const Web3ReactProviderDefault = dynamic(
>   () => import('../components/defaultprovider'),
>   { ssr: false }
> )
> 
> 
> 
> const App = ({ Component, pageProps }) => {
>   return (
>     <Web3ReactProvider getLibrary={getLibrary}>
>       <Web3ReactProviderDefault getLibrary={getLibrary}>
>         <Component {...pageProps} />
>       </Web3ReactProviderDefault>
>     </Web3ReactProvider>
>   )
> }
> ```
this will break SEO for any `<Component`

**Comment by nftgeek** [comment]
> > Use dynamic loading for next.js
> > Define provider `components/defaultprovider.js`
> > ```js
> > import { createWeb3ReactRoot } from '@web3-react/core'
> > import { DefaultProviderName } from 'src/constants'
> > 
> > 
> > const Web3ReactProviderDefault = createWeb3ReactRoot(DefaultProviderName)
> > 
> > const Web3ReactProviderDefaultSSR = ({ children, getLibrary }) => {
> >   return (
> >     <Web3ReactProviderDefault getLibrary={getLibrary}>
> >       {children}
> >     </Web3ReactProviderDefault>
> >   )
> > }
> > 
> > export default Web3ReactProviderDefaultSSR;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Load it without SSR in `_app.js`
> > ```js
> > const Web3ReactProviderDefault = dynamic(
> >   () => import('../components/defaultprovider'),
> >   { ssr: false }
> > )
> > 
> > 
> > 
> > const App = ({ Component, pageProps }) => {
> >   return (
> >     <Web3ReactProvider getLibrary={getLibrary}>
> >       <Web3ReactProviderDefault getLibrary={getLibrary}>
> >         <Component {...pageProps} />
> >       </Web3ReactProviderDefault>
> >     </Web3ReactProvider>
> >   )
> > }
> > ```
> 
> this will break Social media previews and negatively affect SEO for any `<Component` text

Hi   @maximgeerinck I'm on the same page. How did you solve this SEO issue?

**Comment by StKostyantin** [comment]
> 

I didn't any issues

But I also switched to version 8 - there is no such problem

**Comment by msathya98** [comment]
Hi How did you fix this issue ?  which method you have used ?
