### ISSUE TITLE
doesn't work with latest MetaMask

### ISSUE THREAD

**Issue by jinserk** [NoahZinsmeister/web3-react#19]
MetaMask has been updated to 6.4.1 a few days ago, and they something changed the events so that web3-react 5.0.4 doesn't work well any more. It cannot detect the MetaMask login/logout, for example.

**Comment by NoahZinsmeister** [comment]
are you sure? 6.4.1 works for me using this code: https://codesandbox.io/s/6v5nrq2nqw. re. logging in and out, logging out with metamask doesn't unset the connector by default anymore (perhaps it used to? regardless, this behavior has changed.) one pattern for logging out is to check for errors of type `InjectedConnector.errorCodes.UNLOCK_REQUIRED`, unset the connector, and then optionally set it again to trigger the metamask access request modal.

**Comment by jinserk** [comment]
My mistake. web3-react detects logout with MetaMask, but when I login again, it doesn't reload. Obviously it does using the code in https://codesandbox.io/s/rjwjmronr4. Do I need to check context.error or something?

**Comment by jinserk** [comment]
One more question: if the browser has no web3 capability -- i.e. no MetaMask extension installed -- how to avoid the repetitive rendering?

**Comment by jinserk** [comment]
It seems that both of the above questions are solved with the following code:
```
function AppMain() {
  const context = useWeb3Context();

  return (
    <Fragment>
      <div className="App">
        test!!!
      </div>
    </Fragment>
  );
}

function MetaMaskComponent() {
  const context = useWeb3Context();

  console.log(context);
  useEffect(() => {
    if (!context.active) {
      if (!context.connector)
        context.setConnector('MetaMask');
      else if (context.error.code === InjectedConnector.errorCodes.UNLOCK_REQUIRED)
        context.unsetConnector('MetaMask');
    }
  });

  if (!context.active && !context.error) {
    return (
      <div>Loading...</div>
    );
  }

  if (context.error) {
    console.error(context.error);
    if (context.error.code === InjectedConnector.errorCodes.UNLOCK_REQUIRED) {
      return <AccountUnavailable />;
    } else {
      return <Web3Unavailable />;
    }
  }

  return <AppMain />;
}

export default function App() {
  return (
    <Web3Provider connectors={connectors} libraryName='ethers.js'>
      <MetaMaskComponent />
    </Web3Provider>
  );
}
