### ISSUE TITLE
MetaMask disconnects while attempting to change network to binance smart chain

### ISSUE THREAD

**Issue by hakeemullahjan** [NoahZinsmeister/web3-react#196]
**Bug Description**

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**

**Additional Context**

**Comment by gigamesh** [comment]
I'm experiencing this as well. https://gateway.optimism.io/

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
