### ISSUE TITLE
Default example walletconnect/web3-proivder is broken with >1 chainId

### ISSUE THREAD

**Issue by mateo-io** [NoahZinsmeister/web3-react#197]
**Bug Description**

I'm trying this project out with Chrome on Windows, Metamask installed, and I get the following error both on codesandbox and when developing locally.

`Error: Invariant failed: @walletconnect/web3-provider is broken with >1 chainId, please use 1`

![image](https://user-images.githubusercontent.com/6109587/118576472-36397780-b74e-11eb-8a4a-7558ea4cecd0.png)

**Comment by ChangoMan** [comment]
I got this too, I fixed it by going into `example/connectors.ts` and changing the `export const walletconnect` to this:

```
export const walletconnect = new WalletConnectConnector({
  rpc: { 1: RPC_URLS[1] },
  qrcode: true,
  pollingInterval: POLLING_INTERVAL
})
```

Basically remove the `4: RPC_URLS[4]` part from the `rpc` object.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by akash1412** [comment]
hi, I want to support multiple chain connections with wallet connect in my app. Can you help me with how I can achieve that?
Like I checked the new beta version example and it doesn't support the Binance chain is it going to support in the future.
