### ISSUE TITLE
Not able to activate provider right after page mount.

### ISSUE THREAD

**Issue by theKashey** [NoahZinsmeister/web3-react#199]
If a connection is being _reactivated_ right after page mount - it will not activated, and no error will be reported __if__ parent component will rerender.

**Reproduction**
Steps to reproduce:
1. call `activate` from `useWeb3ReactManager`
2. re-render tree above 
3. connection is marked as stale

**Expected Behavior**

Expected connection to happen

**Additional Context**

The root cause is this line: 
https://github.com/NoahZinsmeister/web3-react/blob/6737868693adb7e1e28ae80499e19901e9aae45a/packages/core/src/manager.ts#L120

- every time hook is called - increment `updateBusterRef`
- and if connection started with lower number - mark it as `stale` and reject. 
- even if it is __connected__ by fact (and some further updates will _reveal_ the connection)

I am really not sure what `updateBusterRef` is for, but it cannot be used as it is used right now.

----

In my case I was able to mitigate the problem by supressing updates above the tree, but that's not always possible.

**Comment by maximgeerinck** [comment]
Agreed. Seems to be a big problem using next.js as well because of the router transitioning

**Comment by damianlluch** [comment]
> Agreed. Seems to be a big problem using next.js as well because of the router transitioning
> 
> adding something like this worked, though it's not pretty
> 
> ```
> const Web3ReactProvider: any = dynamic(
>   () => import('@web3-react/core').then(i => i.Web3ReactProvider) as any,
>   { ssr: false },
> );
> ```
> 
> and making sure `<Web3ReactProvider getLibrary={getLibrary}>` is the top of the tree

Sorry, but I'm having I think the same problem, the connection doesn't re-establish automatically after a refresh in Next.js.
I've seen that you use something from "dinamic", what is that? a library?

thanks

**Comment by theKashey** [comment]
That is a code splitting solution from NextJS, which in this case is not fixing anything, while the second point - "is the top of the tree", read "hoisting above update source" does.

**Comment by leanazulyoro** [comment]
I'm facing the same issue, also usign Nextjs. If attempting to reconnect after a route change around 50% of the time I would get a stale connection warning. I'm also not sure what that updateBuster is for, but it would at least be nice if instead of a warning it would throw an error. That way we could catch it and attempt to connect again.

**Comment by leanazulyoro** [comment]
> That is a code splitting solution from NextJS, which in this case is not fixing anything, while the second point - "is the top of the tree", read "hoisting above update source" does.

Also, I checked but already had Web3ReactProvider at the top of the tree. Also tried to load it with dynamic as suggested by @maximgeerinck but no luck.

**Comment by leanazulyoro** [comment]
> That is a code splitting solution from NextJS, which in this case is not fixing anything, while the second point - "is the top of the tree", read "hoisting above update source" does.

@theKashey did you in fact solve this by moving the Web3ReactProvider to the top of the tree? I have it wrapping everything in the _app.js file, I don't think there is a higher place to put it in a nextjs app.

**Comment by theKashey** [comment]
> every time hook is called - increment updateBusterRef

Hoisting code is not enough, you have to ensure it's not _'updated'_ due to some logic. I would recommend, and personally did it that way, to extract necessary code into `React.memo`-ed component to prevent unnecessary `updateBusterRef` updated.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
