### ISSUE TITLE
AlphaWallet not supported yet ?

### ISSUE THREAD

**Issue by Elden97** [NoahZinsmeister/web3-react#20]
Hello,

Do you think that you will add AlphaWallet soon ?
Cause I need this for my Website.

Cordially,

**Comment by NoahZinsmeister** [comment]
@Elden97 afaik they did not have an up-to-date `window.ethereum` object, see [here](https://github.com/Uniswap/uniswap-frontend/issues/282).

there's probably some improvements to be done around this on the `web3-react` side, but i'm afraid i won't have time to check for a few more weeks, though it may be fixed now? also note that it'd be pretty easy to write your own connector locally that works with alphawallet if my temporary negligence gets too bad 😛.

**Comment by James-Sangalli** [comment]
@NoahZinsmeister this has been fixed, thanks for your help.
