### ISSUE TITLE
Use `ethereum.request`, not `ethereum.send` when available.

### ISSUE THREAD

**Issue by MicahZoltu** [NoahZinsmeister/web3-react#206]
https://github.com/NoahZinsmeister/web3-react/blob/6737868693adb7e1e28ae80499e19901e9aae45a/packages/injected-connector/src/index.ts#L196

`ethereum.send` was never actually specified and different apps and providers have different implementations of it making it the worst of all options for compatibility.  `ethereum.request` is the most well specified (https://eips.ethereum.org/EIPS/eip-2696) and should always be preferred over any other options available.  `ethereum.sendAsync` isn't formally specified anywhere, but everyone implements in the same way so should be the first fallback option.  `ethereum.send` should only be used if nothing else is available due to its incompatibility with so much in the ecosystem.

**Comment by babyface001** [comment]
https://eips.ethereum.org/EIPS/eip-1193

**Comment by greg-nagy** [comment]
Yo, 

This implementation just gave me a hard time.

@NoahZinsmeister Would you merge a PR — given good quality — that updates the `injected-connector` to work with the `ethereum.request()`?

Happy to make the PR, but lazy to make it if it's something that won't be merged.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
