### ISSUE TITLE
InjectedConnector and EIP-1102

### ISSUE THREAD

**Issue by fvictorio** [NoahZinsmeister/web3-react#21]
`InjectedConnector` doesn't seem to respect [EIP-1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md). In other words, it seems like it uses `window.web3` as the provider instead of `window.ethereum`. Is this correct?

I can provide more details if necessary.

**Comment by NoahZinsmeister** [comment]
@fvictorio the `InjectedConnector` should throw [an appropriate error](https://github.com/NoahZinsmeister/web3-react/blob/latest/src/connectors/injected.ts#L45) if `window.web3` exists instead of `window.ethereum`. Are you seeing different behavior?

**Comment by fvictorio** [comment]
Sorry, my bad, I was in localhost and I had already connected MetaMask with some other project. Sorry for being an idiot and jumping to conclusions :man_facepalming:  Thanks!
