### ISSUE TITLE
WalletConnect provider doesn't work after user rejects the request the first time

### ISSUE THREAD

**Issue by lucid-eleven** [NoahZinsmeister/web3-react#217]
I'm not sure if I'm using it wrong, but if I activate the WalletConnectConnector the first time on my website, it works and shows the QR code or shows the connect to mobile wallet screen, but then if the user cancels out of the QR code, or rejects the request from their wallet, trying to activate WalletConnectConnector again from my website doesn't seem to do anything.  The page has to be refreshed.

I tried running the example application and it's the exact same behaviour there.

Steps to reproduce:
1. Activate WalletConnectConnector
2. Reject the request by closing the QR code without connecting, or reject the request from mobile wallet
3. Try to activate WalletConnectConnector again

**Expected Behavior**
The QR code or the Connect To Mobile Wallet modal appears again

**Comment by lucid-eleven** [comment]
I ended up working around the issue by doing something like this to reset the provider
`if (connector instanceof WalletConnectConnector && connector.walletConnectProvider?.wc?.uri) {
      connector.walletConnectProvider = undefined
}`

**Comment by Theo6890** [comment]
Up! I had to do what @lucid-eleven wrote above

**Comment by remon-nashid** [comment]
Very nasty issue and needs to be fixed.

**Comment by jung-han** [comment]
Do you have any plans to update without cleaning like the above in your team?

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by karens885** [comment]
hi how i solved this issue;
const WalletConnectProvider = require("@walletconnect/web3-provider");
  WalletConnectProviderObject = new WalletConnectProvider.default({
   infuraId = xxx
});
in WalletConnectProviderObject  there is variable  ''connected'';
for each operation i  just check if  

 if(WalletConnectProviderObject.connected == false)
{
// than create new  WalletConnectProviderObject   ;

}

**Comment by TetianaMolchanova** [comment]
const isRequestActive: Ref<UnwrapRef<boolean>> = ref(false);
    if (isRequestActive.value) {
        console.warn("NEW A request is already active. Please wait.");
        return;
    }

    console.log('if AFTER', );

    try {
        // Example: Requesting account access
        const accounts = await (window.ethereum as any)?.request({ method: 'eth_requestAccounts' }).then((account) => console.log('account', account)).catch((error: unknown) => console.error('error', error)).finally(() => console.log('finally', ));
        // Proceed with additional actions like showing balance, switching chains, etc.
        console.log('NEW accounts', accounts);
        isRequestActive.value = true;
    } catch (error) {
        console.error("NEW Error interacting with MetaMask:", error);
        // Handle error appropriately
        isRequestActive.value = false;
    } finally {
        console.log('NEW finally isRequestActive.value', isRequestActive.value);
        isRequestActive.value = false;
    }
    console.log('metaMaskCall end', );
    
    For catching error here the magic is done in this line of code above: 
    
    const accounts = await (window.ethereum as any)?.request({ method: 'eth_requestAccounts' }).then((account) => console.log('account', account)).catch((error: unknown) => console.error('error', error)).finally(() => console.log('finally', ));
    
    We caught this error in .catch method of request.
    
    this code is for Vue 3 with typescript
