### ISSUE TITLE
Best way to check for existing connection?

### ISSUE THREAD

**Issue by spobwoode** [NoahZinsmeister/web3-react#220]
I have a button that connects using `web3React.activate(injected)` but I have to press the button each time I refresh the page.

What's the best way to check for an existing connection on each page load, so that it persists? I thought about setting a cookie and then automatically calling `web3React.activate(injected)` when the cookie is detected but I wanted to check that there's no built-in way to do this.

Thanks.

**Comment by PolyPigeonFinance** [comment]
```
injected.isAuthorized().then((isAuthorized) => {
        if (isAuthorized) {
            activate(injected);
        }
    })
```

this should work fine :D

**Comment by ThePaulo1** [comment]
```
injected.isAuthorized().then((isAuthorized) => {
        if (isAuthorized) {
            activate(injected);
        }
})
```
    
this should work fine :D

**Comment by spobwoode** [comment]
Worked perfectly. Thanks 🙏

**Comment by Shmoji** [comment]
What about the Torus connector? It doesn't seem to have the _isAuthorized_ method for some reason
