### ISSUE TITLE
Request network change

### ISSUE THREAD

**Issue by ThePaulo1** [NoahZinsmeister/web3-react#221]
Is there a way I could request for a network change if the network id is not a supported one?

Example: User comes from Uniswap on my website which only supports chain id 123 but the user's MetaMask is still connected to chain id 1. As soon as the user got connected with my website MetaMask should pop up and ask if my website is allowed to change the network id from 1 to 123.

**Comment by cosmin-negoita** [comment]
I know there's the [useInactiveListener](https://github.com/NoahZinsmeister/web3-react/blob/v6/example/hooks.ts) hook, but I'm not sure how it's intended to be used. I have a similar problem, but with the useWallet package and someone pointed to the aforementioned hook.

**Comment by sambacha** [comment]
`wallet_switchEthereumChain `should only be called as a result of direct user action, such as the click of a button, [reference from the official metamask docs](https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods). 

You *can* create something called a MetaMask deeplink URL, this can have the the specified parameters of the new network connection 

e.g. https://metamask-links.netlify.app/?method=wallet_addEthereumChain&params[0][chainId]=0x64&params[0][chainName]=xDAI%20Chain&params[0][rpcUrls][0]=https://dai.poa.network&params[0][iconUrls][0]=https://xdaichain.com/fake/example/url/xdai.svg&params[0][iconUrls][1]=https://xdaichain.com/fake/example/url/xdai.png&params[0][nativeCurrency][name]=xDAI&params[0][nativeCurrency][symbol]=xDAI&params[0][nativeCurrency][decimals]=18&params[0][blockExplorerUrls][0]=https://blockscout.com/poa/xdai/

**Comment by jacobedawson** [comment]
> Is there a way I could request for a network change if the network id is not a supported one?
> 
> Example: User comes from Uniswap on my website which only supports chain id 123 but the user's MetaMask is still connected to chain id 1. As soon as the user got connected with my website MetaMask should pop up and ask if my website is allowed to change the network id from 1 to 123.

The way I'm handling this is with a check to see if the current chainId is the one I would like to support. Following code is edited for brevity:

```
// ConnectButton.tsx
const { account, chainId } = useWeb3React();

if (account) {
  return chainId === 1 ? <Button>{account}</Button> : <SwitchNetworkButton>Switch to Mainnet</SwitchNetworkButton>
}
```

```
// SwitchNetworkButton.tsx

import { injected } from "src/web3/connectors";

export function SwitchNetworkButton() {
  return (
    <Button
      onClick={() => {
        // NOTE: presuming user is using injectedConnector
        injected
          .getProvider()
          .then((provider) => {
            provider.request({
              method: "wallet_switchEthereumChain",
              params: [
                {
                  chainId: "0x1",
                },
              ],
            });
          })
          .catch((error: any) => {
            console.log(error);
          });
      }}
    >
      Switch to Mainnet
    </Button>
  );
}
```

This will warn the user that they are on the wrong network, and allow them to prompt their wallet to switch networks when the buttton is clicked. 

NOTE: 

Something odd that I noticed (and still haven't resolved) is that chainId will only be detected if there is no "supportedChainIds" property passed to the InjectedConnector constructor:

`export const injected = new InjectedConnector({});` // works with the switch button

```
// does not work with the switch button
export const injected = new InjectedConnector({
  supportedChainIds: [1, 5, 42],
});
```

If an array of ids is passed to it, e.g. 1, 5, 42, then switching the network to an unsupported network will not trigger an update in the chainId. You can test this yourself by adding a useEffect hook and logging the chainId, when supportedChainIds are added the chainId will be undefined when switching networks:

```
  useEffect(() => {
    console.log(account, chainId, active, connector);
    if (error) {
      console.log(error);
    }
  }, [error, chainId, active, account, connector]);
```

Still trying to work out why this is the case, will update this if I find out.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
