### ISSUE TITLE
We wrote some docs for web3react , hoping someone will check them out

### ISSUE THREAD

**Issue by wschwab** [NoahZinsmeister/web3-react#226]
**Description**

Hi! [We](https://linumlabs.com) really like your library, and ended up writing some internal docs to help us use it better, which we are in the process of turning into an article. Seeing as a lot of Web3React isn't documented, we thought this might be useful for you. We'd like to invite any of the Web3React team to take a look, give feedback, and use whatever might be useful for you.

**Additional Context**

We've been writing using a HackMD [here](https://hackmd.io/Ykpp1MWLTjixIZG2ZJEShA), and would be happy to respond to any feedback here in the thread.

**Comment by wschwab** [comment]
If it would be better to open a PR pushing docs to the repo, I'd be happy to do that too, but would want to be able to discuss where and in what structure they should be included

**Comment by pauldcollins** [comment]
Thanks for this @wschwab I've been watching Noah's [Video here](https://www.youtube.com/watch?v=9ih_J223Hrg) and trying to match it up with the examples and to be honest, I'm still struggling to connect a MetaMask wallet!

Your docs are great, really helpful. The only section that could use more detail is the initial setup of a Project in React, including importing a the `web3-react` Provider, using `Web3.js` and connecting to a `MetaMask` wallet - from a blank `create-react-app` for example.

The examples docs are comprehensive and great, but a basic setup doc would really help for people jumping in for the first time on a dApp, like me! 

Thanks again

**Comment by wschwab** [comment]
> The only section that could use more detail is the initial setup of a Project in React, including importing the `web3-react` Provider, using `Web3.js` and connecting to a `MetaMask` wallet - from a blank `create-react-app` for example.
> 
> The examples docs are comprehensive and great, but a basic setup doc would really help for people jumping in for the first time on a dApp, like me!

Thanks for the feedback! I'd really like to dive into this. I've been in the space for a couple of years, so there's a good chance that things I think are obvious aren't. Looking at the article, I realize that we did gloss over some parts of setup. Do you mean something like [this](https://github.com/NoahZinsmeister/web3-react/tree/v6/docs#web3reactprovider) from `web3react`'s docs? If you do - great! We'll make sure to also include that (or at least link to it). If not, could you dive in a bit more to what we could explain more?

(As a big aside, you'd probably be interested to learn that there are a number of React boilerplates custom made for Eth, which you may find easier to use for a dapp environment than pure `create-react-app`. I'll list 3:

- [create-eth-app](https://github.com/paulrberg/create-eth-app#readme) by Paul R Berg
- [scaffold-eth](https://github.com/austintgriffith/scaffold-eth#-scaffold-eth) by Austin Griffith (which is built on top of create-eth-app)
- [useDapp](https://usedapp.readthedocs.io/en/latest/index.html) by Ethworks

That being said, there's nothing _wrong_ with developing on `create-react-app`.)

**Comment by pauldcollins** [comment]
Hi @wschwab thanks for your reply. I did try out the example from the `web3react` docs you linked to, but as a beginner to the space, I couldn't get it working. I guess if there were a complete, but basic example of the most common setup to connect to a wallet (I'm guessing `Web3` and `MetaMask`), that would explain a lot. Some things that (I think) were missing are. 

1.) What libraries you would need to import first, on top of the `web3React` library. (Is it `Web3` and `InjectedConnector`)
2.) How you would use those with the `web3React` library, to connect to the MetaMask wallet. For example, should this line of code:

`return new Web3Provider(provider)`

be changed to 

`return new Web3(provider)`

Once we are using the Web3 library. 

3.) A launch button, to connect to the wallet, so we could see what functionality needs to happen when clicked, to connect.

Those are just some ideas. I guess another could be to just have a `CodeSandBox` or `CodePen` that shows the one example. I know there is [this one](https://codesandbox.io/s/github/NoahZinsmeister/web3-react/tree/v6/example?fontsize=14&hidenavigation=1&theme=dark), but as it contained many scenarios, it was hard to work out the bare minimum for importing `Web3react` and connecting to a wallet.

Once again, thanks for taking the time to put the docs together, they helped me understand a lot more about `web3react`, it's just the setup I've struggled with.

**ASIDE**: No I didn't know about those boilerplates. They look awesome. I will look at moving my current `create-react-app` components across I think. Thanks heaps!

**Comment by wschwab** [comment]
> I guess if there were a complete, but basic example of the most common setup to connect to a wallet (I'm guessing Web3 and MetaMask), that would explain a lot.

That's a great idea! These docs were actually first written for an internal boilerplate we use, which may explain why they're lacking in certain areas. I think you're right - a simple example page would be beneficial.

**Comment by pauldcollins** [comment]
Please post here when you can @wschwab looking forward to seeing it. Thanks for all your work so far. 

I've been using `useDapp` also, since you sent the link, it's really useful for getting setup.

Thanks again

**Comment by Andrea-Dispe** [comment]
> **Description**
> 
> Hi! [We](https://linumlabs.com) really like your library, and ended up writing some internal docs to help us use it better, which we are in the process of turning into an article. Seeing as a lot of Web3React isn't documented, we thought this might be useful for you. We'd like to invite any of the Web3React team to take a look, give feedback, and use whatever might be useful for you.
> 
> **Additional Context**
> 
> We've been writing using a HackMD [here](https://hackmd.io/Ykpp1MWLTjixIZG2ZJEShA), and would be happy to respond to any feedback here in the thread.

Sorry I didn't fully understand, you wrote the docs for the web3React? The link you posted sends me to the docs of another library: @usedapp/core

**Comment by Theo6890** [comment]
Much appreciated! Especially the section about **_deactivate()_**! I spent ages until I've found this to understand metasmask uses **deactivate()** whereas as you stated Torus, WalletConnect and others use **connector.close()**

Thanks a lot! 🙏

**Comment by wschwab** [comment]
@pauldcollins just got back around to working on this some more. I'll answer one of your questions more specifically first:
> should this line of code: ```javascript return new Web3Provider(provider)```
> be changed to ```javascript return new Web3(provider) ```
> Once we are using the Web3 library.

I think you mean to ask if you're using the web3.js library if you'd need to use `new Web3` instead of `new Web3Provider` - the answer is yes. The basic idea there is that you need to import a web3 provider from Ethers, Web3.js, or wherever, and then instantiate it in the `getLibrary` function.

We also added an "Initial Setup" section, and are curious what your feedback is on it . Thanks again for the feedback!

**Comment by pauldcollins** [comment]
Hi @wschwab thanks for coming back to me on this. 

That example makes much more sense to me now at least! Great to have an example of what a complete file would look like. Thanks for taking the time to sort that out. 

Also, thanks for answering my question and all your other advice. It's really helped on this journey into dApps! 

All the best

**Comment by dhruvkelawala** [comment]
Thanks for an amazing work. I had hard-time figuring out the documentation.

**Comment by wschwab** [comment]
@dsldsl  I am unfortunately not sure - it's been a while since I wrote this, and I've been focused on the smart contract side a lot more since then, so I haven't been working with it recently

**Comment by gsteenkamp89** [comment]
> Agreed this would be great in the repo! @wschwab[wschwab](https://github.com/wschwab) do you know if there's a way with this lib to automatically re-connect on page load without needing to manually click reconnect to MM? I know how to do it with plain ethers.js but not sure with these wrappers. Thanks!

Hey @dsldsl I could probably help answer this.
Just be aware that these docs are kinda obsolete for v8 (current version), but if you're using v6 in your poject then this will still be useful:

So I think the answer to your problems lies in a method on the `InjectedConnector` class: [isAutorized()](https://github.com/NoahZinsmeister/web3-react/blob/17882f0e4279a8fa425f79b96a1536bbf292e1db/packages/injected-connector/src/index.ts#L190)

So if I were you I would create a hook that checks if the return value is true, and if so then call `activate()`;

```typescript
// somewhere in your config files
import { InjectedConnector } from '@web3-react/injected-connector'
export const Injected = new InjectedConnector({ supportedNetworks: [1] });

// hooks folder

export const useAutoConnect = ()=> {
 const { activate } = useWeb3React();
 
 useEffect(()=> {
    if (injected.isAuthorized()) {
        activate(injected);
    }
 }, [activate])
}
```
And then just call `useAutoConnect()` somewhere top level in your application.
Add whatever error handling you'd need, but it should work. 
Hope this helps!

**Comment by wschwab** [comment]
New versions of `web3react` has made this outdated, closing.
