### ISSUE TITLE
Connector.off() is not a function

### ISSUE THREAD

**Issue by sammdec** [NoahZinsmeister/web3-react#227]
**Bug Description**
When attempting to deactivate a recently connected wallet. We will receive a connector.off() error. The library code alludes that this shouldn’t be possible as it guards for a connector object to be present. 

Has anyone else seen this behaviour or solved it?

**Comment by Theo6890** [comment]
Hi @sammdec look at this issue #239  it might help you. Cheers 😉

**Comment by gwendall** [comment]
Install the latest `events` package. Solved by @Synvox https://github.com/EthWorks/useDApp/issues/320#issuecomment-990633636

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by pony13500815917** [comment]
安装 events 依赖库

npm i events 或 yarn add events

在入口文件中引入 events

import 'events'
