### ISSUE TITLE
Disconnect wallet, but reconnects on refresh.

### ISSUE THREAD

**Issue by iangregsondev** [NoahZinsmeister/web3-react#228]
Hi,

I have implemented (using the example) a connection to metamask and it works great. I refresh and after a second then it reconnects! Exactly what I need.

Now I decided to implement the disconnect. I did, and when I disconnect then it does disconnect and the UI updates but as soon as I refresh then it reconnects the wallet.

Am I doing something wrong ?

I notice the demo app also does the same. ( https://codesandbox.io/s/p5b66?file=/pages/index.tsx )

I was hoping for a method to disconnect permantenly or at least some state so that it knows not to reconnect.

I am basically using the following from the example app

```
  // handle logic to eagerly connect to the injected ethereum provider, if it exists and has granted access already
  const triedEager = useEagerConnect()


  // handle logic to connect in reaction to certain events on the injected ethereum provider, if it exists
  useInactiveListener(!triedEager || !!activatingConnector)
```

and I have 

```
  const onDisconnect = () => {
    deactivate()
  }


  return (
    <div>
      <div>ChainId: {chainId}</div>
      <div>Account: {account}</div>
      {active ? (
        <div>✅ </div>
      ) : (
        <div>
        <button type="button" onClick={onClick}>
          Connect
        </button>


        </div>
      )}
      <button type="button" onClick={onDisconnect}>
        Disconnect
      </button>
    </div>
  )

```

As I say, if I disconnect then the UI updates and it seems I am disconnected - but a refresh then causes it to reconnect.

Of course, it is the following code that performs that - inside of useEagerConnect

```
  injected.isAuthorized().then((isAuthorized: boolean) => {
      if (isAuthorized) {
        activate(injected, undefined, true).catch(() => {
          setTried(true)
        })
      } else {
        setTried(true)
      }
    })
```

So it seems the disconnect doesn't unauthorized ?

Are there any ways around this ?

Thanks in advance

**Comment by iangregsondev** [comment]
I could store the state of my disconnect in localStorage for example and then look at the value on refresh..

But I didn't want to re-invent the wheel and I figured I must be doing something wrong :-) ?

**Comment by Andrea-Dispe** [comment]
Hello @iangregsondev , I am sorry I cannot help you as I just started using this library but it seems you solve a problem I am having  and for which I couldn't find a solution. How did you manage to implement autoconnection to the wallet once the page refreshes? I have used the web3React code found on the npm page: 
```
const injectedConnector = new InjectedConnector({
  supportedChainIds: [
    1, // Mainet
    3, // Ropsten
    4, // Rinkeby
    5, // Goerli
    42, // Kovan
  ],
})
const handleClick = () => {
  activate(injectedConnector)
}

```
I noticed the active variable turns true once the wallet is connected but I do not know how to keep it true upon refresh.
How do you do it?

**Comment by Andrea-Dispe** [comment]
Hello, I have got the same issue and cannot find a solution. Were you able to you fix that?

**Comment by iangregsondev** [comment]
@Andrea-Dispe no I wasn't able to fix it with an out-of-the-box solution which is what I was looking for. Its very easy to fix without that. You could just use localStorage and store if you disconnected or not.

But I don't want to re-invent the wheel and I was assuming that this is already fixed. 

I will probably do the localStorage fix implementation myself but It felt wrong on my part and I thought it would have been already fixed - but it appears not - so maybe my idea isn't as bad as I first thought :-) AH AH

**Comment by jontonsoup** [comment]
this seems like a major security issue? is there a plan to fix this?

**Comment by narlypunk** [comment]
@

> @Andrea-Dispe no I wasn't able to fix it with an out-of-the-box solution which is what I was looking for. Its very easy to fix without that. You could just use localStorage and store if you disconnected or not.
> 
> But I don't want to re-invent the wheel and I was assuming that this is already fixed.
> 
> I will probably do the localStorage fix implementation myself but It felt wrong on my part and I thought it would have been already fixed - but it appears not - so maybe my idea isn't as bad as I first thought :-) AH AH

Hey @iangregsondev could you share your solution for the interim? :)

**Comment by rockstar1112** [comment]
it's same issue with me.
I can deactivae with button.. and after refresh, the injected button include green checker icon again..
I can't find any solution. pls help me this issue ....

onClick={() => {
deactivate() 
}

**Comment by irzhywau** [comment]
any thoughts on this please? @NoahZinsmeister

**Comment by rockstar1112** [comment]
Hello. how are you ?

**Comment by elvinest** [comment]
I also encountered the same problem, looking forward to the update!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
