### ISSUE TITLE
Adding Keystone hardware wallet to web3-react

### ISSUE THREAD

**Issue by BitcoinLixin** [NoahZinsmeister/web3-react#229]
Hi! web3-react is amazing!

[We](https://keyst.one/) are Keystone hardware wallet team. We have been in the space for over 3 years (with previous brand Cobo Vault). We were mostly working on Bitcoin security and recently we started to explore what we can help in Ethereum community.
This is a [quick demo](https://twitter.com/KeystoneWallet/status/1415316932954255362) we have just released last week.

Aside from ABI decoding to avoid some classic attacks like phishing sites, we have some other advantages compared to current hardware solution for Ethereum:
* 4 inch touch screen brings much better UX to avoid human error.
* QR code has much less connectivity issues compared to USB/Bluetooth and it creates 100% air-gapping for your private keys.
* Details about our product design philosophies: https://blog.keyst.one/keystone-product-design-principles-cd833bc11125
* Details about open source: https://blog.keyst.one/on-open-source-and-transparency-ba37fa1c1e8c
* Some other cool features like secret words Shamir Secret Sharing Scheme ([SLIP39](https://github.com/satoshilabs/slips/blob/master/slip-0039.md))

Question - 
What's the process of getting integrated with web3-react (we will submit PR but do we need to send sample device to anyone for testing before get merged)? If sample device is needed, who should I ping?

Thanks!

**Comment by NoahZinsmeister** [comment]
hi! thanks for the interest, please see https://github.com/NoahZinsmeister/web3-react/#adding-connectors for guidance on adding connectors
