### ISSUE TITLE
What happened to web3Hooks?

### ISSUE THREAD

**Issue by nharlow89** [NoahZinsmeister/web3-react#23]
Projects using older versions of this library make use of several hooks that were found in `src/web3Hooks.js` at one point, including `useTransactionManager` and `useSignPersonalManager`. These functionalities seem pretty core to any real web3 frontend, so I was curios about the decision to remove them or if it was replaced somehow.

**Comment by NoahZinsmeister** [comment]
agreed @nharlow89, i addressed my rationale behind removing these hooks [here](https://github.com/NoahZinsmeister/web3-react/issues/10#issuecomment-477438067).

they have not and will not be replaced, my recommendation is to do one of:

a) look at my old implementations in the git history and copy them over to your project
b) search for some open-source implementations, either stand-alone hooks/components/etc. or embedded in apps (the [uniswap-frontend](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/hooks/index.js) repo contains some interesting examples) or
c) write your own implementations

hope this helps!
