### ISSUE TITLE
use `@walletconnect/ethereum-provider` instead of `@walletconnect/web3-provider`

### ISSUE THREAD

**Issue by moodysalem** [NoahZinsmeister/web3-react#231]
**Description**
this new provider should be much smaller, and hopefully not send getBlockByNumber requests for every new block it receives

**Additional Context**
cc @pedrouid

**Comment by pedrouid** [comment]
This would be a very welcome improvement and we will be updating our documentation to recommend this new package

TLDR' this new packages completely removes the dependency from web3-provider-engine which had polling enabled by default plus introduced a lot of legacy code which is now redundant in 2021

**Comment by hbarcelos** [comment]
Any estimates on when this will be complete?

**Comment by talentlessguy** [comment]
@hbarcelos alpha version of web3-react uses `ethereum-provider`, see https://github.com/NoahZinsmeister/web3-react/tree/main/packages/walletconnect
