### ISSUE TITLE
Unhandled Rejection (Error): Invariant failed: No <Web3ReactProvider ... /> found.

### ISSUE THREAD

**Issue by charlower** [NoahZinsmeister/web3-react#233]
**Bug Description**
Hello, I've been trying to work this out for hours. Can anyone help diagnose what on earth I am doing wrong?

Error:
![Screen Shot 2021-07-24 at 11 02 51 am](https://user-images.githubusercontent.com/7565117/126853126-d6447947-b0b2-4263-9ba3-000889a1827e.png)

Code:
https://gist.github.com/charlower/9e3f8d2f1d58522d2496c5cf1fc955d9

**Comment by charlower** [comment]
Ahhh all good worked it out. Check updated code here for solution:

Code:
https://gist.github.com/charlower/50ed5e2d5ed4f49d657cdcd2ba672386

**Comment by SCBuergel** [comment]
This is super helpful - my search engine brought me here about 5 times by now for that gotcha ;)
