### ISSUE TITLE
Wallet disconnection issue

### ISSUE THREAD

**Issue by Theo6890** [NoahZinsmeister/web3-react#239]
If you try to disconnect InjectedWallet (Metamask) using `connector.close()` it will fail. Though, you can't use `deactivate()` all the time as some wallets (e.g. _WalletConnect_) only supports `connector.close()`.

```
const context = useWeb3React();
const { deactivate } = context;

// works
deactivate() ?? connector?.close();

// doesnt works cause it is possible: connector === undefined
// e.g.: InjectedConnector (Metamask) deconnection
connector?.close() ?? deactivate(); 
```

**Comment by dhruvkelawala** [comment]
Property 'close' does not exist on type 'AbstractConnector'

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
