### ISSUE TITLE
Polygon Support

### ISSUE THREAD

**Issue by novaknole** [NoahZinsmeister/web3-react#256]
Hi @NoahZinsmeister 

I want to support polygon(testnet and production).

1. Somehow, the injected connector(which is metamask) only allows `supportedChainIds` argument, and when I pass 137 to it, it still can't connect to it.  Does this mean I can't support polygon through metamask on this web3-react ? any plans on this ?
2. Which connector should I use that supports polygon ?

**Comment by chlenc** [comment]
I have the samw issue

**Comment by talentlessguy** [comment]
check in alpha version, should be working fine
