### ISSUE TITLE
Wrong ChainId returned when switching from Rinkeby to Avalanche networks

### ISSUE THREAD

**Issue by DimitarTAtanasov** [NoahZinsmeister/web3-react#257]
**Bug Description**

**Reproduction**
[CodeSandbox reproduction](https://codesandbox.io/s/jolly-napier-c6yyh?file=/connectors.ts:141-163)

Steps to reproduce:
1. Include Avalanche networks ids for InjectedConnector
`export const injected = new InjectedConnector({ supportedChainIds: [1, 3, 4, 5, 42, 43113, 43114] })`
2. Press the 'Injected' option
 3. open Metamask and choose "Rinkeby" network
 4. change the network again to Avalanche ( no matter if you choose Avalanche Mainnet C-Chain or Avalanche FUJI C-Chain)
 

**Expected Behavior**
"Chain Id" should be populated with either 43114 or 43113 depending on the Avalanche network you have chosen.

**Additional Context**
"Chain Id"  is populated with 1(eth mainnet)

NOTE: The issue is only reproducible if you choose Rinkeby and then Avalanche. In all other scenarios chain id is populated correctly.

**Comment by justeth** [comment]
I can also reproduce this behavior when switching from the Binance Smart Chain to Avalanche.
Doing so triggers both the events `chainChanged` & `networkChanged`

Switching to Binance Smart Chain first:

> Handling 'chainChanged' event with payload 0x38
> Emitting 'Web3ReactUpdate' with payload {chainId: "0x38", provider: Proxy}
> Handling 'networkChanged' event with payload 56
> Emitting 'Web3ReactUpdate' with payload {chainId: "56", provider: Proxy}

Switching to Avalanche: 

> Handling 'chainChanged' event with payload 0xa86a
> Emitting 'Web3ReactUpdate' with payload {chainId: "0xa86a", provider: Proxy}
> Handling 'networkChanged' event with payload 1
> Emitting 'Web3ReactUpdate' with payload {chainId: "1", provider: Proxy}

chainId is now updated to "1", which corresponds to the Ethereum main net and does not reflect the true chain selected in the Injected Connector (Metamask in my case)

`networkChanged` is a deprecated event and should be removed 

 https://github.com/NoahZinsmeister/web3-react/blob/f41dc87032a6ec6f43ed5f349a4847a9ab85f861/packages/injected-connector/src/index.ts#L78

( ref: https://docs.metamask.io/guide/ethereum-provider.html#networkchanged-deprecated )

**Comment by DimitarTAtanasov** [comment]
Removing the networkChanged event listener after every web3React.activate(...) call worked for me as a workaround, thanks @justeth

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
