### ISSUE TITLE
WalletConnectConnector: MetaMask App connection is successful, but modifying the network does not trigger the chainChanged event

### ISSUE THREAD

**Issue by acrens** [NoahZinsmeister/web3-react#259]
**WalletConnectConnector chainChanged event not work；but accountsChanged event is work**

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**

**Additional Context**

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
