### ISSUE TITLE
web3modal connector

### ISSUE THREAD

**Issue by shrugs** [NoahZinsmeister/web3-react#260]
**Description**

I wanted to use web3-react's state machine and context helpers with web3modal's UI, so i write a simple connector. I'm looking for feedback on features i've missed (custom errors? what about supported chain information based on `ICoreOptions['network']`?) before i issue a pull request.

```ts
import { ConnectorUpdate } from '@web3-react/types';
import { AbstractConnector } from '@web3-react/abstract-connector';
import type { default as Web3Modal, ICoreOptions } from 'web3modal';

export class Web3ModalConnector extends AbstractConnector {
  public options: Partial<ICoreOptions>;
  public provider?: any;
  public web3Modal?: Web3Modal;

  constructor(options: Partial<ICoreOptions>) {
    // super({supportedChainIds: options.network ? });
    super();

    this.options = options;

    this.handleChainChanged = this.handleChainChanged.bind(this);
    this.handleAccountsChanged = this.handleAccountsChanged.bind(this);
    this.handleDisconnect = this.handleDisconnect.bind(this);
  }

  private handleChainChanged(chainId: number | string): void {
    this.emitUpdate({ chainId });
  }

  private handleAccountsChanged(accounts: string[]): void {
    this.emitUpdate({ account: accounts[0] });
  }

  private handleDisconnect(): void {
    this.emitDeactivate();
  }

  public async load(): Promise<void> {
    if (!this.web3Modal) {
      const Web3Modal = await import('web3modal').then((m) => m.default);
      this.web3Modal = new Web3Modal(this.options);
    }
  }

  public async activate(): Promise<ConnectorUpdate> {
    await this.load();

    this.web3Modal.on('chainChanged', this.handleChainChanged);
    this.web3Modal.on('accountsChanged', this.handleAccountsChanged);
    this.web3Modal.on('disconnect', this.handleDisconnect);

    this.provider = await this.web3Modal.connect();
    const account = this.provider.selectedAddress ?? this.provider.accounts[0];

    return { provider: this.provider, account };
  }

  public async getProvider(): Promise<any> {
    return this.provider;
  }

  public async getChainId(): Promise<number | string> {
    return this.provider.chainId;
  }

  public async getAccount(): Promise<null | string> {
    return this.provider.accounts[0];
  }

  public deactivate() {
    this.provider?.removeListener('disconnect', this.handleDisconnect);
    this.provider?.removeListener('chainChanged', this.handleChainChanged);
    this.provider?.removeListener('accountsChanged', this.handleAccountsChanged);

    // use disconnect function if exists
    this.provider?.disconnect?.();

    // use close function if exists
    this.provider?.close?.();
  }
}
```
 and here's an eager connect hook

```ts
export function useEagerConnect() {
  const { activate } = useWeb3React();

  useEffect(() => {
    (async () => {
      await connector.load();
      if (connector.web3Modal?.cachedProvider) {
        activate(connector);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
}

```

**Comment by ssijak** [comment]
This feature would be great to have

**Comment by shrugs** [comment]
i've switched to using `@gimmixorg/use-wallet` which has similar (but not as much) functionality

**Comment by shrugs** [comment]
Will leave this issue open for the maintainers to triage as necessary, or perhaps someone will make the PR themselves.

**Comment by ssijak** [comment]
@shrugs Did you have issues with your snippet from the first post here? I'm looking into staying with @web3-react until they officially support the modal.

**Comment by shrugs** [comment]
i had a small issue with the walletconnect cached provider and my eager connect hook (sometimes when the page loads, the cached provider is there, but web3modal doesn't know that and asks the user to connect again), but nothing major.

**Comment by photonite** [comment]
This would be of great help!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by jellohouse** [comment]
What is the status on this?

Can we easily use web3-react with web3modal?

Or I should copy pasta shrugs code above?

**Comment by ShravanSunder** [comment]
scaffold-eth/eth-hooks has a web3modal connector for web3-react.  However its using v6.  I am waiting for v8 to be stable before upgrading it.  See https://github.com/scaffold-eth/eth-hooks/issues/123
