### ISSUE TITLE
Ledger Connector: Allow for switching between accounts

### ISSUE THREAD

**Issue by DannyFung97** [NoahZinsmeister/web3-react#265]
Hi, I have been playing around with the Ledger connector and I think it would greatly benefit if it has some kind of function to allow switching in between accounts.

So far, as soon as the ledger wallet is successfully connected, the account to appear is the very first one that was retrieved. I know there is a function that can retrieve accounts but I don't see a function that would switch over to that account.

I think this would be a helpful addition to the connector, is this a planned implementation?

**Comment by outdoteth** [comment]
@DannyFung97 I've opened a PR to add this. So it works in 3 steps:

1) Set the ledger path
2) Fetch the accounts
3) Set the account

lmk if you had another idea of how to implement it

**Comment by DannyFung97** [comment]
Nice, I really like those additions. :)

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
