### ISSUE TITLE
LatticeConnector crashes on Production build with Vite. Seems like issue with ESM.

### ISSUE THREAD

**Issue by dhruvkelawala** [NoahZinsmeister/web3-react#266]
**Bug Description**

I am using LatticeConnector in one of my projects. All of my connectors work fine in development mode but LatticeConnector fails on Production build done with Vite. Seems like an ESM issue but I am not sure.
![Screenshot 2021-09-05 at 2 49 39 PM](https://user-images.githubusercontent.com/50968441/132121841-e84d9516-0977-4721-8705-88a875961e56.png)

**Reproduction**
 const LatticeConnector = (await import('@web3-react/lattice-connector')).LatticeConnector;
      return new LatticeConnector({
        chainId: 1,
        url: NETWORK_URLS[SupportedChainId.MAINNET],
        appName: 'MyApp',
      });

**Comment by talentlessguy** [comment]
try console logging LatticeConnector if it gets imported

**Comment by dhruvkelawala** [comment]
It was issue because of readable-streams having circular dependency which is not supported by Vite.
