### ISSUE TITLE
Cannot install in clean CRA project

### ISSUE THREAD

**Issue by wslyvh** [NoahZinsmeister/web3-react#27]
Tried to install it into a clean create-react-app, but it fails.

**Steps to repro**
Install/update create-react-app
Create new project: npx create-react-app web3 --typescript 
npm install web3-react
npm run build 

Expect that that should be enough to run the solution.

**Result**
`npm ERR! path /Users/wslyvh/Documents/Code/Test/web3/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /Users/wslyvh/Documents/Code/Test/web3/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /Users/wslyvh/Documents/Code/Test/web3/node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wslyvh/.npm/_logs/2019-08-08T14_34_50_685Z-debug.log`

**Workaround**
Delete & clean node_modules (specifically node_modules/ganache-core/node_modules/web3-providers-ws/node_modules/websocket).

**Comment by NoahZinsmeister** [comment]
looks like this is an issue with `web3`? happy to reopen if that's in fact not the case.
