### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by swene-dev** [NoahZinsmeister/web3-react#279]
**Bug Description**
I'm getting this warning in the console:
`./node_modules/ethers/dist/ethers.min.js`
`Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Reproduction**
```js
yarn dev
```

Steps to reproduce:
1. I'm importing the following:
```js
import { Web3Provider } from '@ethersproject/providers'
import { formatEther } from '@ethersproject/units'
```

2. And in the package.json:
```js
"@ethersproject/providers": "latest",
"@ethersproject/units": "latest",
```

**Expected Behavior**
no warning

**Comment by AlbertLin0327** [comment]
Has anyone managed to solve this? Stuck in this error for a while. thx
