### ISSUE TITLE
Using WalletConnectConnector

### ISSUE THREAD

**Issue by fvictorio** [NoahZinsmeister/web3-react#28]
I set up web3-react with WalletConnector but I'm not getting the modal with the QR. I guess I can do it using `context.connector.walletConnector` and then following the instructions in [WalletConnect docs](https://docs.walletconnect.org/quick-start/dapps), but I thought that the web3-react connector would handle that for me. Am I missing something here?

Thanks!

**Comment by NoahZinsmeister** [comment]
hey @fvictorio, yeah unfortunately there's some finagling that needs to be done, most of which is demonstrated in this [codesandbox](https://codesandbox.io/s/6v5nrq2nqw). let me know if that still isn't working!

**Comment by fvictorio** [comment]
Oh, I see. I ended up doing something very similar, so at least I know I'm not that off. Thanks!
