### ISSUE TITLE
Failed to connect mobile wallets using WalletConnectConnector

### ISSUE THREAD

**Issue by kcraftsman** [NoahZinsmeister/web3-react#280]
**Bug Description**

**Codes**
export const walletConnect = new WalletConnectConnector({
  rpc: {
    1: "...",
    ...
  },
  bridge: 'https://bridge.walletconnect.org',
  qrcode: true,
  pollingInterval: 12000,
})

export default App(props) {

  const {active, account, library, chainId, connector, activate, deactivate} = useWeb3React();

  const onConnect = () => {
  try {
        await activate(walletConnect);
    } catch (e) {
        console.log(e);
    }
  }

  return (
    <button onClick={onConnect}>Connect Wallet</button>
  )

}

Steps to reproduce:
1. Open a mobile browser, and click the button on the page.
2. See the error page as below:

Unhandled Rejection (TypeError): undefined is not an object (evaluating '_walletconnect_environment__WEBPACK_IMPORTED_MODULE_0__["getSubtleCrypto"]().importKey")
....

**Expected Behavior**
See the modal to connect a wallet

**Additional Context**

Test it with Safari and Firefox with IOS 15

Screenshoot of error page:
![log](https://user-images.githubusercontent.com/1791669/135204741-42bface4-1e58-4b7a-9aeb-a128e0149a97.jpeg)

**Comment by viet-nv** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

You shoud use https. 
If you're using CRA for init repo, you can run `HTTPS=true yarn start`

https://create-react-app.dev/docs/using-https-in-development#linux-macos-bash

**Comment by kcraftsman** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
> 
> You shoud use https. If you're using CRA for init repo, you can run `HTTPS=true yarn start`
> 
> https://create-react-app.dev/docs/using-https-in-development#linux-macos-bash

Yes, it works out
