### ISSUE TITLE
MagicConnector does not support Polygon Testnet (Mumbai)

### ISSUE THREAD

**Issue by SweetmanTech** [NoahZinsmeister/web3-react#283]
**Bug Description**
Although [Magic supports Polygon's Mumbai testnet,](https://magic.link/docs/blockchains/polygon) the MagicConnector throws an error when I use the chainId: `80001`.

In the short-term, we are removing MagicConnector from our stack & using native Magic SDK instead.

Can you fix this bug?
<img width="1365" alt="Screen Shot 2021-10-01 at 12 18 02 AM" src="https://user-images.githubusercontent.com/23249402/135501321-701b2520-0be3-4945-9a8f-e59eb0d73157.png">

**Reproduction**
[CodeSandbox reproduction]()
```
new MagicConnector({ 
        apiKey: process.env.MAGIC_API_KEY, 
        chainId: 80001, 
        email
    })
```

chainId 80001 will throw an error.

Steps to reproduce:
1.  Initialize MagicConnector with `chainId: 80001`.
2. See error on screen.

**Expected Behavior**
I expect MagicConnector to support Polygon & Mumbai networks.

**Additional Context*
*

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
