### ISSUE TITLE
Auto activate on page load if wallet is already connected

### ISSUE THREAD

**Issue by ccarnino** [NoahZinsmeister/web3-react#289]
**Bug Description**
I have followed the documentation to have the page connect to the wallet as follows
```
export default function SignInButton() {
  const { account, activate, active } = useWeb3React()

  // useEffect(() => {
  //   activate(injectedConnector)
  // }, [account, activate, active])
  
  async function connectWallet() {
    activate(injectedConnector)
  }

  if (active) {
    return (
      <span>
        {shorterAddress(account)}
      </span>
    )
  }

  return (
    <button onClick={connectWallet}>
      Sign-in with Ethereum
    </button>
  )
}
```

Everything works as expected. If the user taps on `Sign-in with Ethereum` button it ask to connect the wallet, when approved the component renders again and shows the connected address.

Now, if I reload the page, the `account === undefined and active === false`. But as soon as I click on the `Sign-in with Ethereum` button, the component reloads and `account` and `active` are correctly set.

I could avoid this calling the `activate(...)` in `useEffect(...)`, but it would also mean that a completely new user, on the page load would be immediately asked to connect their wallets. Which is as bad.

Am I doing anything wrong?

**Additional Context**
I am using a `create-next-app` project. For the rests is a normal react app.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see #163 (comment)

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
