### ISSUE TITLE
After walletconnect is connected, refresh the page and activate walletconnect again. At this time, the websocket connection delay is too serious，At this time, the PC performs an operation, and the mobile phone needs to delay for several minutes to receive the command trigger

### ISSUE THREAD

**Issue by supermars01** [NoahZinsmeister/web3-react#299]
**Bug Description**
When I connect to walletconnect, I refresh the page to activate walletconnect again. At this time, it takes a few minutes for a transaction to trigger the websocket mobile connection，At this time, the PC performs an operation, and the mobile phone needs to delay for several minutes to receive the command trigger

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**

**Additional Context**

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
