### ISSUE TITLE
QRcode will pop up automatically by chance

### ISSUE THREAD

**Issue by supermars01** [NoahZinsmeister/web3-react#301]
**Bug Description**
1. When I disconnect walletconnect from my phone,

2. Or when the close () method is called,

QRcode will pop up automatically by chance,

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**
![img](https://user-images.githubusercontent.com/7869573/138387586-504e8b3a-6bd4-401a-960c-6f787b392f4c.png)

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
