### ISSUE TITLE
InjectedConnector not working on mobile browsers

### ISSUE THREAD

**Issue by spobwoode** [NoahZinsmeister/web3-react#303]
InjectedConnector is working great with Metamask on all desktop browsers and with Metamask in-app mobile browser but it's not working on mobile browsers (Chrome/Safari/etc). I'm guessing it's because the mobile browsers don't have the Metamask plugin so there's nothing to 'inject'. 

Is there any way to make this work? If not, is there a better way to integrate web3-react so that it's truly cross-platform?

**Comment by Artimunor** [comment]
you can download a wallet like trustwallet and inject that in the browser by going to an intent link
or use mobile apps with built in browser like the metamask app
