### ISSUE TITLE
supportedChainIds only accept Integer

### ISSUE THREAD

**Issue by AlbertLin0327** [NoahZinsmeister/web3-react#304]
Currently, the connector (Inject, BSC, ...) only takes in integer (56, 97, ...) but Binance-Chain's chain id is "Binance-Chain-Tigris". I can not manage to solve the issue, and I am wondering does anyone run into the same issue. Thank you!

my "useInactiveListener" function
`
    
    const useInactiveListener = (suppress: boolean = false) => {
    const { connector, active, error } = useWeb3React();
    const connectedWallet = localStorage.getItem('Wallet') ?? '';
    const { login } = useAuth();

    useEffect((): any => {
        if (connector && connector.on && !active && !error && !suppress) {
            const handleConnect = () => {
                console.log("Handling 'connect' event");
                login(connectedWallet);
            };
            const handleChainChanged = (chainId: string | number) => {
                console.log("Handling 'chainChanged' event with payload", chainId);
                if (Number.isNaN(chainId)) return;
                window.location.reload();
                login(connectedWallet);
            };
            const handleAccountsChanged = (accounts: string[]) => {
                console.log("Handling 'accountsChanged' event with payload", accounts);
                if (accounts.length > 0) {
                    login(connectedWallet);
                }
            };
            const handleNetworkChanged = (networkId: string | number) => {
                console.log("Handling 'networkChanged' event with payload", networkId);
                if (Number.isNaN(networkId)) return;
                login(connectedWallet);
            };

            connector.on('connect', handleConnect);
            connector.on('chainChanged', handleChainChanged);
            connector.on('accountsChanged', handleAccountsChanged);
            connector.on('networkChanged', handleNetworkChanged);

            return () => {
                if (connector.removeListener) {
                    connector.removeListener('connect', handleConnect);
                    connector.removeListener('chainChanged', handleChainChanged);
                    connector.removeListener('accountsChanged', handleAccountsChanged);
                    connector.removeListener('networkChanged', handleNetworkChanged);
                }
            };
        }
    }, [active, error, suppress, connector, login, connectedWallet]);
};
    
`
Result:
`
<img width="1130" alt="Screen Shot 2021-10-27 at 14 58 39" src="https://user-images.githubusercontent.com/11944812/139015804-8d7950c8-1014-49c3-b532-847182cb848c.png">
<img width="1146" alt="Screen Shot 2021-10-27 at 14 58 51" src="https://user-images.githubusercontent.com/11944812/139015814-626008a4-b743-4631-94f2-5076687f7ca6.png">

`

Step to reproduce:
1. First connect wallet with proper chain (BSC, ETH mainnet)
2. Switch to Binance Chain.

**Comment by h0tw4t3r** [comment]
this patch fixes the issue, also adds return on `activate()` promise with account":

```
diff --git a/node_modules/@web3-react/core/dist/core.esm.js b/node_modules/@web3-react/core/dist/core.esm.js
index 7426262..f246cce 100644
--- a/node_modules/@web3-react/core/dist/core.esm.js
+++ b/node_modules/@web3-react/core/dist/core.esm.js
@@ -180,8 +180,12 @@ var augmentConnectorUpdate = function augmentConnectorUpdate(connector, update)
       return Promise.resolve(Promise.all([update.chainId === undefined ? connector.getChainId() : update.chainId, update.account === undefined ? connector.getAccount() : update.account])).then(function (_ref2) {
         var _chainId = _ref2[0],
             _account = _ref2[1];
-        var chainId = normalizeChainId(_chainId);
 
+        try {
+          var chainId = normalizeChainId(_chainId);
+        } catch {
+          throw new UnsupportedChainIdError(_chainId, connector.supportedChainIds);
+        }
         if (!!connector.supportedChainIds && !connector.supportedChainIds.includes(chainId)) {
           throw new UnsupportedChainIdError(chainId, connector.supportedChainIds);
         }
@@ -361,6 +365,8 @@ function useWeb3ReactManager() {
                 onError: onError
               })
             });
+
+            return augmentedUpdate
           });
         });
       }, function (error) {
@@ -411,26 +417,36 @@ function useWeb3ReactManager() {
 
       return Promise.resolve(function () {
         if (!error) {
-          var _chainId4 = update.chainId === undefined ? undefined : normalizeChainId(update.chainId);
+          try {
+            var _chainId4 = update.chainId === undefined ? undefined : normalizeChainId(update.chainId);
+            if (_chainId4 !== undefined && !!connector.supportedChainIds && !connector.supportedChainIds.includes(_chainId4)) {
+              var _error2 = new UnsupportedChainIdError(_chainId4, connector.supportedChainIds);
 
-          if (_chainId4 !== undefined && !!connector.supportedChainIds && !connector.supportedChainIds.includes(_chainId4)) {
-            var _error2 = new UnsupportedChainIdError(_chainId4, connector.supportedChainIds);
+              onError ? onError(_error2) : dispatch({
+                type: ActionType.ERROR,
+                payload: {
+                  error: _error2
+                }
+              });
+            } else {
+              var _account4 = typeof update.account === 'string' ? normalizeAccount(update.account) : update.account;
 
-            onError ? onError(_error2) : dispatch({
-              type: ActionType.ERROR,
-              payload: {
-                error: _error2
-              }
-            });
-          } else {
-            var _account4 = typeof update.account === 'string' ? normalizeAccount(update.account) : update.account;
+              dispatch({
+                type: ActionType.UPDATE,
+                payload: {
+                  provider: update.provider,
+                  chainId: _chainId4,
+                  account: _account4
+                }
+              });
+            }
+          } catch {
+            var _error1 = new UnsupportedChainIdError(update.chainId, connector.supportedChainIds);
 
-            dispatch({
-              type: ActionType.UPDATE,
+            onError ? onError(_error1) : dispatch({
+              type: ActionType.ERROR,
               payload: {
-                provider: update.provider,
-                chainId: _chainId4,
-                account: _account4
+                error: _error1
               }
             });
           }
diff --git a/node_modules/@web3-react/core/dist/manager.d.ts b/node_modules/@web3-react/core/dist/manager.d.ts
index a3521dd..f4dad01 100644
--- a/node_modules/@web3-react/core/dist/manager.d.ts
+++ b/node_modules/@web3-react/core/dist/manager.d.ts
@@ -1,5 +1,5 @@
 import { Web3ReactManagerReturn } from './types';
 export declare class UnsupportedChainIdError extends Error {
-    constructor(unsupportedChainId: number, supportedChainIds?: readonly number[]);
+    constructor(unsupportedChainId: string | number, supportedChainIds?: readonly number[]);
 }
 export declare function useWeb3ReactManager(): Web3ReactManagerReturn;
diff --git a/node_modules/@web3-react/core/dist/types.d.ts b/node_modules/@web3-react/core/dist/types.d.ts
index b8e285a..ea766da 100644
--- a/node_modules/@web3-react/core/dist/types.d.ts
+++ b/node_modules/@web3-react/core/dist/types.d.ts
@@ -1,6 +1,7 @@
 import { AbstractConnector } from '@web3-react/abstract-connector';
+import { ConnectorUpdate } from '@web3-react/types';
 export interface Web3ReactManagerFunctions {
-    activate: (connector: AbstractConnector, onError?: (error: Error) => void, throwErrors?: boolean) => Promise<void>;
+    activate: (connector: AbstractConnector, onError?: (error: Error) => void, throwErrors?: boolean) => Promise<ConnectorUpdate>;
     setError: (error: Error) => void;
     deactivate: () => void;
 }

```

**Comment by h0tw4t3r** [comment]
Hey @NoahZinsmeister, any details on why is this issue closed?
