### ISSUE TITLE
using @web3-react/injected-connector inside react-native-webview

### ISSUE THREAD

**Issue by sandys** [NoahZinsmeister/web3-react#305]
would like to use injected-connector inside a react-native-webview.

to communicate with react-native, it needs to invoke `window.ReactNativeWebView.postMessage(event.data);`

is it possible to add these changes ?

**Comment by NoahZinsmeister** [comment]
hi @sandys, probably yes! this use case might be specific enough to warrant a one-off connector that you maintain, though. also, going to close as part of general clean-up in advance of making v8 the `latest` release
