### ISSUE TITLE
When connecting walletconnect, rpcurl is not updated, and there is an acquisition error. Uniswap also has the same problem

### ISSUE THREAD

**Issue by supermars01** [NoahZinsmeister/web3-react#306]
**Bug Description**

When I connect to metamask and then walletconnect, rpcurl defaults to https://mainnet.infura.io/v3/ ${infura_key} does not automatically match RPC nodes according to walletconnect's current connected network. You need to refresh the page to get them normally. The version of @ Web3 react / core I use is v6.19

@web3-react/walletconnect-connector v6.27

Would you like to fix this problem? Is there a problem with the version pack

step1：Connect to metamask (mainnet) and then walletconnect (Kovan). The chainid and rpcurl are not updated
![step1](https://user-images.githubusercontent.com/7869573/139363347-9905dd76-4bfd-4a32-8aae-bf65cac0f5fc.png)
step2：At this time, the page needs to be refreshed before the chainid and rpcurl are updated
![step2](https://user-images.githubusercontent.com/7869573/139363443-31dd7e2a-78d6-40b0-b811-dd1572573846.png)

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**

**Additional Context**

**Comment by sambacha** [comment]
you can not use multiple web3 providers at the same time, that is why this is not working.

Pick one provider, you can not use multiple. This is a long known issue. e.g. you can't use Nifty Wallet and Metamask at the same time.

**Comment by supermars01** [comment]
> you can not use multiple web3 providers at the same time, that is why this is not working.
> 
> Pick one provider, you can not use multiple. This is a long known issue. e.g. you can't use Nifty Wallet and Metamask at the same time.

I know, but when I first connect to metamask and then want to switch to walletconnect, I have to operate the metamask plug-in, disconnect the wallet and connect to walletconnect. Is the user experience too bad? In fact, there is no such bug in walletconnect @ 6.2.0, but I can't use the @ 6.2.0 package now because there is a problem with this package,lug-in, disconnect the wallet and connect walletconnect. Is the user experience too bad

**Comment by henry12322** [comment]
Contact coinbase support instead bro. https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by sambacha** [comment]
Do you have a repo / can you try the v8 alphas? (they are located on the main branch for reference)

**Comment by arintrongs** [comment]
@sambacha I'm also facing this problem. Could you help provide us more detail on how to install v8 alpha version pls? You mean the `@web3-react/walletconnect-connector` or `@web3-react/core`? Thanks! :)

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by dawid-tknm** [comment]
Bumped into a similar problem today,, in my case adding explicit `chainId` field to `WalletConnectConnector` constructor options has helped:

```
const walletConnect = new WalletConnectConnector({
  rpc: { [CHAIN_ID]: RPC_URL },
  chainId: CHAIN_ID // add this
});
```
