### ISSUE TITLE
Coinbase wallet signature is different on desktop and mobile

### ISSUE THREAD

**Issue by chrysb** [NoahZinsmeister/web3-react#309]
**Bug Description**
I implemented `web3-react` using `InjectedConnector`. I'm asking users to sign a message using their wallet to prove they own their wallet.

On desktop, the chrome extension pops up, I connect, and then the Coinbase Wallet app sends me a notification to sign. I sign, and the signature gets validated by the backend using Alchemy provider and works just fine.

In the Coinbase Wallet iOS app, when I initiate the process, it pops up the sign message dialog, and after I sign, it produces a different signature hash than the desktop app (with the same exact message). Thus, the signature fails verification.

How could this be?

**Comment by henry12322** [comment]
I think you should contact coinbase support bro. https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by chrysb** [comment]
> I think you should contact coinbase support bro. https://my.forms.app/form/617e6cc70d06846f4ca75ee4

Any moderators wanna deal with this scam?

**Comment by sambacha** [comment]
What ethers provider version are you using? V5.5.0 has changes personal sign methods, 5.4.0 has the old behavior

**Comment by chrysb** [comment]
Updating my version of `ethers` resolved the issue. Woohoo!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
