### ISSUE TITLE
walletconnect-connector doesn't work in 6.2.8

### ISSUE THREAD

**Issue by Chef-Cheems** [NoahZinsmeister/web3-react#310]
**Bug Description**
Package: @web3-react/walletconnect-connector
The `@walletconnect/ethereum-provider` was updated to 1.6 in #255.
For some reason now WalletConnect modal closes and opens again after approving connection. Connection does not get established. Also when modal is closed the error is thrown.

Environment:
```json
"@web3-react/core": "^6.1.9",
"@web3-react/walletconnect-connector": "^6.2.8",
```

**Reproduction**
Unfortunately I don't have time to make contrived example, but here's the problem I'm describing:
https://github.com/pancakeswap/pancake-frontend/compare/develop...Chef-Cheems:feature/update-walletconnect?expand=1

Screencapture of connection attempt

https://user-images.githubusercontent.com/81824236/139859804-c70e7fc7-672c-4059-8066-6529baec8f9e.mp4

**Expected Behavior**
Being able to connect via WalletConnect

**Additional Context**
Latest @walletconnect/ethereum-provider is 1.6.6, maybe its worth updating to that at the same time.

**Comment by henry12322** [comment]
You should contact coinbase support instead bro. https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by paulrberg** [comment]
Not sure if it is related but I'm also encountering an error with v6.2.8. When I scan the QR code, I am getting this error:

```text
Error: invalid web3Provider (arg="web3Provider", value="[object Object]", version=4.0.48)
```

<details>
<summary>Click to expand the full error log
Uncaught Error: invalid web3Provider (arg="web3Provider", value="[object Object]", version=4.0.48)
    at Object.n [as throwError] (ethers.min.js:1)
    at new c (ethers.min.js:1)
    at getLibrary (index.js:29)
    at provider.tsx:50
    at updateMemo (react-dom.development.js:16835)
    at Object.useMemo (react-dom.development.js:17315)
    at useMemo (react.development.js:1643)
    at Web3ReactProvider (provider.tsx:49)
    at renderWithHooks (react-dom.development.js:16241)
    at updateFunctionComponent (react-dom.development.js:18328)
    at beginWork$1 (react-dom.development.js:20151)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at beginWork$$1 (react-dom.development.js:25738)
    at performUnitOfWork (react-dom.development.js:24665)
    at workLoopSync (react-dom.development.js:24638)
    at performSyncWorkOnRoot (react-dom.development.js:24237)
    at react-dom.development.js:12180
    at unstable_runWithPriority (scheduler.development.js:818)
    at runWithPriority$2 (react-dom.development.js:12130)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12175)
    at flushSyncCallbackQueue (react-dom.development.js:12163)
    at scheduleUpdateOnFiber (react-dom.development.js:23676)
    at dispatchAction (react-dom.development.js:17057)
    at manager.ts:144
    
index.js:1 The above error occurred in the <Web3ReactProvider> component:
    in Web3ReactProvider (at src/index.js:56)
</summary>
</details>

**Comment by githubdoramon** [comment]
I have issues with walletconnect connector as well... But in my case I can connect, the transactions are fired, but application never receives the callbacks for transactionHash, receipt, etc

**Comment by rpedroni** [comment]
> I have issues with walletconnect connector as well... But in my case I can connect, the transactions are fired, but application never receives the callbacks for transactionHash, receipt, etc

Have the same exact problem for WalletLink - curious enough on ropsten things work but for mainnet it's as if the awaited promise never fulfills or fails

**Comment by michaelr524** [comment]
> I have issues with walletconnect connector as well... But in my case I can connect, the transactions are fired, but application never receives the callbacks for transactionHash, receipt, etc

I think that I have the same issue. I've noticed that this only happens after realod (wc reconnect) of the page. If the tx is sent at the same session that created the connection then I receive the result of the promise/callback.
Can you confirm the above? @githubdoramon

**Comment by michaelr524** [comment]
> > I have issues with walletconnect connector as well... But in my case I can connect, the transactions are fired, but application never receives the callbacks for transactionHash, receipt, etc
> 
> I think that I have the same issue. I've noticed that this only happens after realod (wc reconnect) of the page. If the tx is sent at the same session that created the connection then I receive the result of the promise/callback. Can you confirm the above? @githubdoramon

"@web3-react/walletconnect-connector": "6.2.4", works

**Comment by dohomi** [comment]
I can confirm, also the demo page https://web3-react-mu.vercel.app/ currently only works on the first try, the second click on the connect button does not work any more.

**Comment by dohomi** [comment]
I got a working solution now for `6.2.4`, @michaelr524 is right about that:
```ts
const activateAccount = async () => {
    // @ts-ignore
    if (window.ethereum) {
      await activate(injected, error => {
        injected.deactivate()
      })
    } else {
      await activate(walletconnect, error => {
        if (error instanceof UserRejectedRequestErrorWalletConnect) {
          walletconnect.handleDisconnect() // => this function I found by accident, its not inside of TypeScript but he only which works...
        }
      })
    }
  }
```
Strange is that only the call to `walletconnect.handleDisconnect()` recovers from closing the WalletConnect dialog.

**Comment by Pujith-M** [comment]
Setting `walletConnector.walletConnectProvider` to null worked 
Found this solution on pancake-swap
https://github.com/pancakeswap/pancake-frontend/blob/48f41ada3f36f8bf738705b81e35eb6f455833fb/src/hooks/useAuth.ts#L48

```
              if (connector instanceof WalletConnectConnector) {
                const walletConnector = connector as WalletConnectConnector
                walletConnector.walletConnectProvider = null
              }
```

**Comment by mikker** [comment]
Seeing the same things as you @rpedroni, @githubdoramon. Did you find a solution?

**Comment by michaelr524** [comment]
Still looking for a solution in order to upgrade to the latest version..

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Comment by aledalgrande** [comment]
Can confirm that if your signer looks "dead", not returning success/fail from the promise, you have to `deactivate` before you `activate`. You can get into that state if the user closes WalletConnect without connecting.
