### ISSUE TITLE
Need to be able to trigger the switch network

### ISSUE THREAD

**Issue by gpxl-dev** [NoahZinsmeister/web3-react#311]
**Description**

Would like to be able to call

```javascript
        library.provider.request!({
          method: "wallet_switchEthereumChain",
          params: [
            {
              chainId: "0x1",
            },
          ],
        });
```

To switch to another network in the event that the current network is not supported, but at this point, `provider` is undefined. I think provider could still be defined in this particular case, right?

**Comment by NoahZinsmeister** [comment]
hi! this type of use case is supported in v8 for metamask (and soon walletlink!)
