### ISSUE TITLE
Remove u2f and migrate to webusb in ledger connector

### ISSUE THREAD

**Issue by outdoteth** [NoahZinsmeister/web3-react#313]
**Bug Description**

As per: https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md:

> We strongly advise to migrate to @ledgerhq/hw-transport-webusb [from @ledgerhq/hw-transport-u2f]

The transport connector in the ledger connector atm is using u2f and should be migrated to webusb instead.

**Comment by agcty** [comment]
+1 u2f will be deprecated in Feb 2022

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
