### ISSUE TITLE
Trouble with _networkId Trezor subprovider

### ISSUE THREAD

**Issue by TrejGun** [NoahZinsmeister/web3-react#317]
**Bug Description**
Can't sign a transaction using Trezor subprovider, because _networkId is undefined.

**Reproduction**

TrezorConnector init as:
`    const connector = new TrezorConnector({
      chainId: 1337,
      url: process.env.JSON_RPC_ADDR as string,
      pollingInterval: 12000,
      manifestEmail: "our@test.com",
      manifestAppUrl: "http://localhost:3003",
    });
`
But deeper, in node_modules/@0x/subproviders/lib/src/subproviders/trezor.js,
transaction init wants networkId, which is undefined. only chainId previously set in config.

`
transaction: {
  to: txData.to,
  value: txData.value,
  data: txData.data,
  chainId: this._networkId,
  nonce: txData.nonce,
  gasLimit: txData.gas,
  gasPrice: txData.gasPrice,
   },
`

**Expected Behavior**
Sign transactions correctly using Trezor.
Probably give way to set networkId and chainId independently

**Additional Context**
Trezor firmware 2.4.2
"@web3-react/trezor-connector": "6.1.9",

**Comment by gsteenkamp89** [comment]
I have the same problem. Trezor wallet connects as expected, but upon attempting to submit a transaction I get this error:
The error:
> Invalid parameters: Parameter "chainId" has invalid type. "number" expected.

**Comment by gsteenkamp89** [comment]
@TrejGun I solved this issue with the `config` object in the TrezorConnector constructor, where I specified the `netowrkId` that the 0zsubprovider is expecting.

```typescript
export const trezor = new TrezorConnector({
  chainId: CHAIN_ID,
  url: NODE_URL,
  pollingInterval: POLLING_INTERVAL,
  manifestEmail: MANIFEST_EMAIL,
  manifestAppUrl: APP_URL,
  config: {
    networkId: CHAIN_ID,
  },
});
```

I'll take the liberty of closing this issue

**Comment by TrejGun** [comment]
cool, thanks, will try

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
