### ISSUE TITLE
The error from useWeb3Context is of type Error, which doesn't have a code property - leads to TypeScript warning

### ISSUE THREAD

**Issue by pcowgill** [NoahZinsmeister/web3-react#32]
When using `useWeb3Context` from `web3-react` in a TypeScript-flavored create-react-app app, this error is shown: `Property 'code' does not exist on type 'Error'. ts(2339)`

Here's a snippet to reproduce it:

```
import { useWeb3Context, Connectors } from "web3-react";
const { Connector } = Connectors;

const { error } = useWeb3Context();

const blockRender =
    error &&
    error.code &&
    error.code === Connector.errorCodes.UNSUPPORTED_NETWORK;
```

**Comment by NoahZinsmeister** [comment]
hey @pcowgill, thanks for the report!

makes sense, i override that error locally with this snippet: https://github.com/NoahZinsmeister/web3-react/blob/latest/src/declarations.ts#L20. looking at MDN though, it seems like `name` might be the right property for what i'm trying to accomplish: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name.

i'm going to keep the issue open and experiment with this in the next version.

**Comment by pcowgill** [comment]
@noahzinsmeister Thanks for the example of how to override it! Agreed, I think `name` would suit your needs here.

**Comment by pcowgill** [comment]
Also, you can subclass errors so that they’ll have name set automatically in the case of a frequently used “error code”

**Comment by NoahZinsmeister** [comment]
🙏 that sounds perfect, i'll try that!

**Comment by pcowgill** [comment]
@NoahZinsmeister In the meantime, do you know of any examples of an app using this library making use of [those or similar declarations](https://github.com/NoahZinsmeister/web3-react/blob/latest/src/declarations.ts#L20)? Thanks!

**Comment by pcowgill** [comment]
This seems to work for an app using this lib:

`ErrorWithCode.ts`
```
export interface ErrorWithCode extends Error {
  code?: string | number | undefined;
}

```


`MyComponent.tsx`
```
import { ErrorWithCode } from "[insert-path-here]/types/ErrorWithCode";
const {
    active,
    error,
    setConnector,
    setError
  }: {
    active: boolean;
    error?: ErrorWithCode | null;
    setConnector: any;
    setError: any;
  } = useWeb3Context();
```

(The `any` type for the functions isn't good TypeScript, but left it like that since that's not the focus here.)

**Comment by NoahZinsmeister** [comment]
going to close this, as v6 uses custom errors which can be checked with `instanceof`! thanks for bringing this up.
