### ISSUE TITLE
Unable to distinguish between metamask over coin98  

### ISSUE THREAD

**Issue by mohitdave7** [NoahZinsmeister/web3-react#323]
**Bug Description**
I am trying to connect with metamask or coin98  wallet from the chrome extention . So i have added metamask and coin98 wallet extentions in the chrome . and when i am trying to connect with metamask but  it's opening the window for the coin98. 

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. Start chrome extention and install metamask  wallet and then coin98 wallet
2. Click on "connect to wallet" and then select metamask . It will be redirected to coin98 wallet extention.

**Expected Behavior**

It should open metamask when clicking on the same

**Additional Context**
 try this link to find a bug:
https://app.uniswap.org/#/swap

**Comment by hoangman1108** [comment]
in coin98 extentions. choolse setting -> Override Wallets -> disable all. it will resolve your problem
