### ISSUE TITLE
How to keep WalletConnect connection, after another activate method call with different connector

### ISSUE THREAD

**Issue by nenadV91** [NoahZinsmeister/web3-react#326]
With update of `web3-react/walletconnect-connector` from `6.2.4` to `6.2.8`, in our app when we change the active wallet from WalletConnect to Metamask for example it will close the connection with WalletConnect and remove the `walletconnect` data from the localStorage. Which looks like the call on `activate` method with another connector closes the connection with the previous wallet if the previous wallet was WalletConnect. Was this change intentional and is there a way to configure this so that previous connection is kept after calling activate with another connector.

**Expected Behavior**
- keep connection with WalletConnect when another connector is connected with activate method

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
