### ISSUE TITLE
Few connectors use deprecated dependency

### ISSUE THREAD

**Issue by hammadgigalabs** [NoahZinsmeister/web3-react#327]
**Description**
Few connectors such as Trezor and WalletLink use the following dependency
 
`https://github.com/ethereumjs/ethereumjs-abi.git`

which is now deprecated!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
