### ISSUE TITLE
Why are HOCs not recommended?

### ISSUE THREAD

**Issue by gwn** [NoahZinsmeister/web3-react#33]
Any solid reasons? My projects are highly based on HOCs and I'm very happy with that. These days many projects offer both hooks, render props and HOCs as interfaces but this is the first time I see someone talk about HOCs -which are the oldest and most established one of those- as being "not recommended".

I'm asking this question not to start something like a flame war or defending functional programming or anything like that. My current app's architecture encourages the use of HOCs as much as possible and I want to know any possible downsides of interacting with this library using HOCs.

Please clarify.

https://github.com/NoahZinsmeister/web3-react#not-recommended---hocs

**Comment by NoahZinsmeister** [comment]
there are no specific reasons why web3-react won't work with HOCs!

in my personal opinions hooks (and _maybe_ render props) are the future of react, and i find using them much more intuitive than HOCs, hence why i don't encourage support. you are welcome to continue using them if they help you solve problems though!

**Comment by gwn** [comment]
Thank you, I feel better now :)

**Comment by NoahZinsmeister** [comment]
hey @gwn, just published some new v6 versions with better support for non-hooks usage! the TLDR is that there's a [`getWeb3ReactContext`](https://github.com/NoahZinsmeister/web3-react/tree/v6/docs#getweb3reactcontext) function exported from `@web3-react/core` that gives you access to the raw react context.

you can use this to unlock [`contextType`](https://reactjs.org/docs/context.html#classcontexttype) patterns, create your own HOC, etc.

let me know if you have any questions!

**Comment by gwn** [comment]
Thank you very much for taking the time for this :)

From the docs:
> or whatever other render prop/HOC/etc. shenanigans your manager whose personal site still runs on PHP is making you write

I both laughed to this and got somewhat offended at the same time :D

**Comment by NoahZinsmeister** [comment]
@gwn all in good fun :)
