### ISSUE TITLE
v8 recommended usage

### ISSUE THREAD

**Issue by agcty** [NoahZinsmeister/web3-react#330]
I've been going through v8 of the codebase today on a mission to integrate it into my own project.

I can already see several benefits over the v6 version, most of all it seems much more flexible than before. Exposing specific hooks is a very nice solution IMO.

However, in v6 it was quite clear how you use the library: 

you have on or more context providers, and values are consumed with useWeb3React()

v8 is very different, it seems that by default there is no Web3ReactProvider anymore and you can just create a new connector/hook tuple like this:

`export const [metaMask, hooks] = initializeConnector<MetaMask>((actions) => new MetaMask(actions))`

activate it, and then use the hooks.

The obvious benefit is you can very easily use different connectors and their respective hooks across the codebase.

But how? What's the recommended usage.

My thought was put all connectors in a context provider and then write your own integration for consuming. Something like this:

```jsx
export function useWeb3React() {
  const { connectors } = useWeb3ReactConnectors()

  // const test = connectors.find(([connector]) => connector instanceof MetaMask)
  const chPair = connectors.filter(([connector, hooks]) => !!hooks?.useIsActive()).sort(sortByPriority())[0]
  const [activeConnector, hooks] = chPair


  const active = hooks.useIsActive()
  const account = hooks.useAccount()
  const provider = hooks.useProvider()
  const error = hooks.useError()
  const chainID = hooks.useChainId()
  const ensName = hooks.useENSName(provider)
  const deactivate = () => activeConnector.deactivate()

  return { active, account, provider, error, chainID, ensName, deactivate }
}
```

Benefits of that is that it really becomes maximally extensible.

Other possibility I could think of is use zustand to expose some functions to change connector and chain etc.

@NoahZinsmeister how did you envision usage? Would be really interested to know :)

**Comment by NoahZinsmeister** [comment]
thanks for the issue @agcty , this is a great point for discussion! my thought was to exactly do what you're reaching for, which is basically a meta-hook that's aware of the activation state of every connector you've defined, then returns the relevant hooks based on some kind of priority order.

there are other possible patterns here, i.e. simultaneously showing the state of two wallets (one on L1 and one L2, for example), but the above usage is what i'd expect to be most common.

curious, does that code snippet work for you?

would it be worth thinking about some kind of canonical hook here where connectors are passed in in priority order and this type of logic is performed?

**Comment by agcty** [comment]
Adapted my example which works now although it has a lot of issues like rerendering all the time etc, rendering fewer hooks than expected etc.

```jsx
export function useWeb3React() {
  const chPair = connectors.filter(([connector, hooks]) => !!hooks.useIsActive()).sort(sortByPriority)[0]

  // metamask is default
  const defaultConnector = connectors[1]

  const activeConnector = chPair?.[0] ?? defaultConnector[0]
  const hooks = chPair?.[1] ?? defaultConnector[1]

  // if no default this won't work because there could be no active connectors so filter will return nothing
  // if filter returns nothing we also cannot use conditionals because react will complain there are more hooks rendered than 
  // during previous (which makes sense, can't put a hook inside an if statement)
  const active = hooks.useIsActive()
  const account = hooks.useAccount()
  const provider = hooks.useProvider()
  const error = hooks.useError()
  const chainID = hooks.useChainId()
  const ensName = hooks.useENSName(provider)
  // this won't work
  const active = hooks?.useIsActive()

  return { active, account, provider, error, chainID, ensName }
}

function getPriority(connector: Connector) {
  const priorityList = {
    metamask: 1,
    walletConnect: 2,
    // etc. etc
    // last needs to always be network
    network: 3,
  }

  if (connector instanceof MetaMask) {
    return priorityList.metamask
  }

  if (connector instanceof WalletConnect) {
    return priorityList.walletConnect
  }

  if (connector instanceof Network) {
    return priorityList.network
  }
}

const sortByPriority = (a: [Connector, Web3ReactHooks], b: [Connector, Web3ReactHooks]) => {
  return getPriority(a[0]) - getPriority(b[0])
}
```

Debugging all of these issues got me somewhat confused.

Do you even need to put the connectors in context or state? No you should just be able to import them right?

Ideally I'd just want to use different hooks like useIsActive, useEnsName etc. that use the connector with the highest priority behind the scenes. And then if people want a drop in solution for useWeb3React() they can just build it using these hooks.

Hooks are both beautiful and mess with your brain sometimes.

**Comment by NoahZinsmeister** [comment]
got it - i totally understand where you're coming from. let me do some thinking on what a canonical priority list abstraction would look like! sounds like that would be useful

**Comment by NoahZinsmeister** [comment]
here's an interesting experiment @agcty : https://github.com/NoahZinsmeister/web3-react/pull/355

basically a `useHighestPriorityConnector` hook that takes in a bunch of connectors and returns the first one that's active! as you'll see there are some hacks to manage react lifecycle updates, but it seems potentially acceptable!

**Comment by agcty** [comment]
@NoahZinsmeister yooooo that's amazing!

love how you're using the ref and zustand subscribe/unsubscribe for performance optimization 🤯
also much better to use the respective stores instead of the hooks to compute if a connector is active

as a first pass this is really amazing!

**Comment by vanruch** [comment]
@NoahZinsmeister Yes, something like this would be amazing! Or in general, there should be a way to access connector state without using hooks to iterate or have them inside `if`s. Maybe keep state in Connector class and add getters to `chainId`, `accounts`, etc?

**Comment by NoahZinsmeister** [comment]
totally, i actually merged that code so it's available in core now!

i think returning the store from `initializeConnector` is good , opens the door for interesting stuff like this in apps as opposed to just core. i'm not 100% satisfied with that hook, but it's a start!

another thing to note is that `useHighestPriorityConnector` works for the generic case, but in any particular codebase, it might make more sense to do something like:

typescript```
function useBestActiveConnectorHooks(metaMaskHooks, networkHooks) {
  const isActiveMetaMask = metaMaskHooks.useIsActive()
  const isActiveNetwork = networkHooks.useIsActive()

  return isActiveMetaMask ? metaMaskHooks : networkHooks
}
```

this avoids the array of hooks problem, as all connectors you want to support can be fully enumerated.

**Comment by NoahZinsmeister** [comment]
hi all, had a bit of a chat with @btraut in https://github.com/NoahZinsmeister/web3-react/issues/375 and have (hopefully) made some usage improvements! he rightly pointed out that substituting hooks for one another at runtime breaks the semantics of hooks. so, i've refactored the example to not do that, which has 2 benefits:

1. it makes the specific UI for each connector very straightforward. components simply statically import the hooks for the connector in question! easy.
2. makes it clear that an abstraction for picking between connectors is very much needed. enter [`getPriorityConnector`](https://github.com/NoahZinsmeister/web3-react/blob/550fb419b8d827bc5abb5fc584cb3c53843c58ac/packages/core/src/index.ts#L35). the idea here is similar to `initializeConnector` - you statically pass in a prioritized list of connectors + hooks, and it returns a wrapped version of each relevant hook that tracks the first active connector. the only small weirdness here is that you'll see i'm mounting hooks from an array, which breaks the hooks eslint rule. however, this isn't actually an issue since the array of connectors is static.

very basic usage is demoed here: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example/components/connectors/PriorityExample.tsx

**Comment by davidthomasparks** [comment]
Hi @NoahZinsmeister, I can't seem to load this priority example. I'm having trouble upgrading from V6 to this newest update. Also, there is no more Web3ReactProvider that wraps _app in _app for Next apps. What do we use instead? I'm a bit lost.
