### ISSUE TITLE
How to use web3-react with mnemonic or account private key?

### ISSUE THREAD

**Issue by thapld** [NoahZinsmeister/web3-react#334]
**Description**
How to use web3-react with mnemonic or account private key?

**Additional Context**

**Comment by rafinskipg** [comment]
@NoahZinsmeister  is there a way to load a public/private key pair into web3-react?

**Comment by NoahZinsmeister** [comment]
yes, though you'd have to write your own connector for it. to be honest, i can't recommend this, as having private keys available in the browser is extremely unsafe
