### ISSUE TITLE
Moderate vulnerability in @web3-react/walletconnect-connector

### ISSUE THREAD

**Issue by luisdelahoz** [NoahZinsmeister/web3-react#339]
**Bug Description**
There is a moderate vulnerability in `@web3-react/walletconnect-connector`: **Inefficient Regular Expression Complexity in chalk/ansi-regex**.

![Screenshot from 2021-12-27 12-55-41](https://user-images.githubusercontent.com/2762088/147487984-35fe21bf-d2b4-4b66-b69c-e1911c57fea1.png)
![Screenshot from 2021-12-27 12-55-50](https://user-images.githubusercontent.com/2762088/147487986-5257e4ca-0978-4b19-8c94-1c74f7079b74.png)

Steps to reproduce:
1. npm audit

**Expected Behavior**
The vulnerability does not exist.

**Additional Context**
The current packages that I'm using are `"@web3-react/walletconnect-connector": "^6.2.8"` and `@web3-react/core: "^6.1.9"`.

**Comment by luisdelahoz** [comment]
@NoahZinsmeister what is the reason? Is it already solved?

**Comment by NoahZinsmeister** [comment]
yeah this is probably fixed, walletconnect-connector was bumped. also those vulns in deps of deps are usually not actually serious

**Comment by anthonysgro** [comment]
This vulnerability is still happening for me
