### ISSUE TITLE
TypeError: library.BatchRequest is not a constructor

### ISSUE THREAD

**Issue by metamn** [NoahZinsmeister/web3-react#34]
I'm trying to load 10 blocks from the chain in a batch: https://ethereum.stackexchange.com/questions/1587/how-can-i-get-the-data-of-the-latest-10-blocks-via-web3-js

```
const latest = await web3.eth.getBlockNumber()
const blockNumbers = _range(latest - n, latest + 1, 1)
const batch = new web3.eth.BatchRequest()

blockNumbers.forEach((blockNumber) => {
  batch.add(
    web3.eth.getBlock.request(blockNumber, storeLocalCopy)
  )
})

batch.execute()
```
Loading the first block works with:

```
/**
   * Loads the latest block number
   */
  const [latestBlockNumber, setLatestBlockNumber] = useState(0);

  useEffect(() => {
    if (active) {
      library
        .getBlockNumber()
        .then(value => {
          setLatestBlockNumber(value);
        })
        .catch(err => {
          console.log(err);
        });
    }
  }, [active]);
```

However when issuing a `const batch = new library.BatchRequest()` I'm getting the following error: `TypeError: library.BatchRequest is not a constructor`

Thank you!

**Comment by NoahZinsmeister** [comment]
this sounds like an issue with web3 or ethers, not web3-react. however, if you can share a minimal reproduction via codesandbox i'd be happy to take a look!
