### ISSUE TITLE
Venly connector

### ISSUE THREAD

**Issue by AqeelKazmi** [NoahZinsmeister/web3-react#346]
**Description**
can we have a Venly connector? so it will be easy to integrate venly wallet into any DEX

**Additional Context**

**Comment by NoahZinsmeister** [comment]
see https://github.com/NoahZinsmeister/web3-react#adding-connectors

**Comment by usama1050** [comment]
> **Description** can we have a Venly connector? so it will be easy to integrate venly wallet into any DEX
> 
> **Additional Context**
please tell me is this  issue resolved? i am stuck on it if there is any solution please tell me.

**Comment by AqeelKazmi** [comment]
No, As Uniswap is using web3-react , and web3-react has no support for venly.
