### ISSUE TITLE
Understanding error bubbling

### ISSUE THREAD

**Issue by PaulRBerg** [NoahZinsmeister/web3-react#36]
## Description
I'm trying to understand the way errors are handled in web3-react.

In the README:

> suppressAndThrowErrors (false by default) controls whether errors, instead of bubbling up to context.error, are instead thrown by this function

But that's not how things work in my app. I get this warning:

```
Silently handling error from 'Injected': Error: Unsupported Network: 100.
```

I use a `useEffect` Hook similar to [this one from uniswap-frontend](https://sourcegraph.com/github.com/Uniswap/uniswap-frontend/-/blob/src/components/Web3Status/index.js#L161:13).

I know that you set `suppressAndThrowErrors` to true and handle errors manually, but I purposefully reverted to the default to see what happens (and use the global context state to handle my wallet modal).

While inspecting the source code, I saw the following in `manager.ts`:

```
if (refId.current !== callingTimeRefId + 1) {
  // eslint-disable-next-line no-console
  console.warn(`Silently handling error from '${connectorName}': ${error.toString()}`)
  return
}
```

Pardon my noobness, but why do you need to do this in the first place? And then, is there any workaround or do I also have to suppress and throw the errors?

## Environment

- react 16.11.0
- web3-react@5.0.5

**Comment by pcowgill** [comment]
@PaulRBerg The reason that error is suppressed is because of what it says in the comment above it `// if the component has re-rendered since this function was called, eat the error`.

As long as the component is still the latest version of itself, then the `suppressAndThrowErrors` setting is followed.

So you'll want to trace through what is causing your component(s) to rerender, and maybe initiate the connection after that is done. Or make sure the `useEffect` hook is getting cleaned up with a special `return` function for the hook so there wouldn't have been an error making it back after the component is about to rerender in the first place. If the code for which you're running into this is open-source, feel free to link to it here.

I agree that the two possible modes of error handling and what they're used for in use cases like Uniswap could be documented more clearly:

1. handle them inline and do retries, show a warning to the developer in dev mode, or whatever is appropriate in that specific spot

     In this case you DO want to suppress and throw errors)

1. having a global context for your app you use to display the most important error (if any) to the user, since `web3-react` nudges you towards doing that for at least some errors.

    In this case you do NOT want to suppress and throw errors, but rather let them flow through to the global error in the `web3-react` context)

In the case of Uniswap, for example, both strategies are used for different function calls - but they're mostly suppressed and thrown in-line. So it's interesting that the context-style errors are the default.

**Comment by pcowgill** [comment]
@PaulRBerg As for that specific error, it looks like you need to change the network you're on in MetaMask to one of the supported ones in the array like is shown below or add the network you're on in MetaMask to the list of supported ones for the injected connector. (Those sound similar but are opposite options.)

```
const MetaMask = Connectors.InjectedConnector({
  supportedNetworks: [...]
})
```

[Here's where the error itself comes from](https://github.com/NoahZinsmeister/web3-react/search?q=unsupported+network&unscoped_q=unsupported+network)

**Comment by PaulRBerg** [comment]
> I agree that the two possible modes of error handling and what they're used for in use cases like Uniswap could be documented more clearly:
>
> 1. handle them inline and do retries, show a warning to the developer in dev mode, or whatever is appropriate in that specific spot
>
> In this case you DO want to suppress and throw errors)
>
> 2.  having a global context for your app you use to display the most important error (if any) to the user, since web3-react nudges you towards doing that for at least some errors.
>
> In this case you do NOT want to suppress and throw errors, but rather let them flow through to the global error in the web3-react context)

This would've been much, much more intuitive imo.

> As for that specific error, it looks like you need to change the network you're on in MetaMask to one of the supported ones in the array

Yeah, I purposefully set MetaMask to xDai for web3-react to throw the error.

> As long as the component is still the latest version of itself, then the suppressAndThrowErrors setting is followed.

Does this mean that if `suppressAndThrowErrors` is `false` (default value), the error is bubbled all the way to the top (context state), but **only and only if** the component did not re-render?

The code is not yet open source, but I made this gist with the said component: [Web3Status.js](https://gist.github.com/PaulRBerg/7e9901caa11a34f8ece59c368f18d8bb).

**Comment by NoahZinsmeister** [comment]
error handling has changed fairly significantly from v5 -> v6. the way things are handled now should be much more consistent and easy to reason about.

to give a high level overview (i will add this to the docs when i get a moment): errors during the _initial activation_ (while calling `activate`), are handled in 1 of 4 ways:

1) in the case where there's been >=1 other updates to the web3-react state between when `activate` was called and when it resolves with the data required to complete the activation, errors are silently suppressed (in dev mode, this will log a warning to the console). this should really only happen in cases where activation takes a long time and the user (or you as a dev) do something in the intervening time like activating another connector, deactivating the current connector, etc.
2) if `throwErrors` (the third argument to `activate`) is true, errors will be thrown and should be handled in a .catch. no updates to the web3-react state will occur.
3) if `onError` (the second argument to `activate`) is defined, that function is called with the error. no updates to the web3-react state will occur.
4) if none of these are true, the error will be set in the web3-react state (along with the connector).

errors that occur _while a connector is set_ are handled in 1 of 2 ways:

1) if an `onError` function was passed to `activate`, this function is called with the error. no updates to the web3-react state will occur.
2) if it wasn't, the error will be set in the web3-react state.

in all of these scenarios, keep in mind that calling `setError` with an error will update the web3-react state. you can do this any time a connector is set, and it can be useful for e.g. when you want to manually trigger your app's handling of the 'global' web3-react error property.

there's one more nuance: if an error is ever set in the web3-react state, and a connector triggers an update, the manager will attempt to revalidate all properties as if `activate` was called again, to recover from the error state.

**Comment by NoahZinsmeister** [comment]
let me know if i can provide more detail, or if you have any feedback on this whole process
