### ISSUE TITLE
Declaring package as module breaks ts-node in V8

### ISSUE THREAD

**Issue by vanruch** [NoahZinsmeister/web3-react#361]
After updating web3-react to v8, I'm getting following error when trying to run mocha tests:
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ...`

Looks like this is caused by adding `"type": "module"` to package.json

Is it necessary to make this package an esm module? If yes, are there any ways of fixing it?

**Node version**: checked on v14 and v16

Edit: ts-node also has issues with modules

**Comment by NoahZinsmeister** [comment]
hm, `"type": "module"` is just be indicating that the package is meant to be consumed as an es module, in this case using the `exports.import` entry (`"./dist/index.js"`). the `"module": "./dist/index.js"` entry is a fallback for tooling that doesn't yet use `exports`. there are also CJS exports in `dist/cjs`, but those should be avoided if possible.

to be honest, this sounds like it might be a ts-node issue? happy to modify entries where it makes sense for compatibility, but i don't see any easy fix here

**Comment by vanruch** [comment]
Yes, this is a ts-node issue https://github.com/TypeStrong/ts-node/issues/935#issuecomment-1000945034
It's possible to make it work by using ts-node/esm loader and declaring your own package as module.

**Comment by NoahZinsmeister** [comment]
great, thanks for digging! closing for now :)
