### ISSUE TITLE
WalletConnect transactions Issue

### ISSUE THREAD

**Issue by RonaldThayil** [NoahZinsmeister/web3-react#364]
import { WalletConnectConnector } from "@web3-react/walletconnect-connector";

I have used this for connecting walletconnect through QR code and used  **useWeb3React** for connecting to wallet.
Metamask extension is working fine but not able to use walletconnect for transactions

const transactionParameters = {
    to: contractAddress, // Required except during contract publications.
    from: acct, // must match user's active address.
    data: window.contract.methods
      .mintNFT(acct, tokenURI)
      .encodeABI(), //make call to NFT smart contract
  };

const txHash = await window.ethereum.request({
      method: "eth_sendTransaction",
      params: [transactionParameters],
    });

The above works fine with metamask extension but not with Walletconnect

It would be great if anyone can help me out.
Thank you

![Screenshot (4)](https://user-images.githubusercontent.com/90387898/149735173-3194f8c2-99b1-4e3f-af25-35ee0530e076.png)

**Comment by alexcyr** [comment]
ran into a similar issue with wallet connect. Calling into a smart contract, transactionHash event is never picked up. Works fine with metamask extension. web3-react on v6 btw

```
contract.methods
          .deposit(
            account,
            account,
            '0x0000000000000000000000000000000000000000',
            depositAmount,
            '0x0000000000000000000000000000000000000000',
          )
          .send({
            from: account,
            value: depositAmount,
          })
          .on('error', function () {
            setSigning(false);
            setError('');
          })
          .on('transactionHash', function (transactionHash: string) {})
          ```

**Comment by NoahZinsmeister** [comment]
going to close, as this is not really related to web3-react, it's related to your usage of ethers

**Comment by RonaldThayil** [comment]
> going to close, as this is not really related to web3-react, it's related to your usage of ethers

Can you let me know where am making mistake because I am new here?

It would be great if you help me.
