### ISSUE TITLE
WalletConnect connector has unresolved dependency (@walletconnect/ethereum-provider)

### ISSUE THREAD

**Issue by rromanovsky** [NoahZinsmeister/web3-react#367]
After I installed `@web3-react/walletconnect` package, I have one unresolved dependency:  
> ../node_modules/@web3-react/walletconnect/dist/index.js:34:26: error: Could not resolve "@walletconnect/ethereum-provider"

Reproduced on `@web3-react/walletconnect` 8.0.1-beta.0

**Comment by NoahZinsmeister** [comment]
ah yes, as you can [see in the package.json](https://github.com/NoahZinsmeister/web3-react/blob/e834e0ac2574b8cef673f1075285cd434b219f9b/packages/walletconnect/package.json#L35) `@walletconnect/ethereum-provider` is a peer dependency of `@web3-react/walletconnect`, so you have to install it on your own! the idea here is to make it easier for people to make non-breaking walletconnect version bumps without touching the connector
