### ISSUE TITLE
WalletConnect send promise never resolves

### ISSUE THREAD

**Issue by amper-fb** [NoahZinsmeister/web3-react#381]
take packages/example and add the following component:
```
function Actions({ hooks: { useAccounts, useProvider } }: { hooks: Web3ReactHooks }) {
  const provider = useProvider()
  const accounts = useAccounts()  

  return (
    <div>
      <button onClick={() => provider.send(
        'personal_sign', [ `test ${Date.now()}`, accounts[0]])
          .then(console.log)
          .catch(console.error)}>
        personal_sign</button>
    </div>
  )
}
```
...
in `App()` after `<Accounts hooks={hooks}>` add:
```
            <Actions hooks={hooks}/>
```

When connecting MetaMask and clicking personal_sign and signing on the wallet, the response is resolved and appears in console.

When connecting a Wallet Connect wallet (any) and clicking personal_sign and signing on the wallet, the response is never resolved or rejected.

**Comment by amper-fb** [comment]
@NoahZinsmeister this reproducible in `@uniswap/interface` and affects a lot of users

**Comment by NoahZinsmeister** [comment]
the interface isn't using v8, so this is either a broader problem or perhaps has some other cause. sounds like a walletconnect issue potentially

**Comment by amper-fb** [comment]
you're right, I believe it's a `@walletconnect/ethereum-provider` [issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/718)
