### ISSUE TITLE
Property 'request' is missing in type 'MockWalletConnectProvider' but required in type 'Provider'

### ISSUE THREAD

**Issue by ChrisChan888** [NoahZinsmeister/web3-react#383]
Type 'WalletConnect' does not satisfy the constraint 'Connector'.
  Types of property 'provider' are incompatible.
    Type 'MockWalletConnectProvider | undefined' is not assignable to type 'Provider | undefined'.
      Property 'request' is missing in type 'MockWalletConnectProvider' but required in type 'Provider'

"@web3-react/core": "8.0.4-beta.0",
    "@web3-react/metamask": "8.0.2-beta.0",
    "@web3-react/walletconnect": "8.0.3-beta.0",

![Screenshot 2022-01-24 at 4 09 25 PM](https://user-images.githubusercontent.com/86586482/150745041-7b22e924-a780-419d-ac21-9399cd2cebdc.png)
.

**Comment by ChrisChan888** [comment]
Failed to compile.

./node_modules/@web3-react/walletconnect/dist/index.js
Module not found: Can't resolve '@walletconnect/ethereum-provider' in '/Users/yiulapsang/Desktop/workspace/blockchain/try-moralis/node_modules/@web3-react/walletconnect/dist'

**Comment by brioapp** [comment]
same here.

**Comment by rahulbhadja** [comment]
ConnetWallet provider is not working. same issue.

**Comment by BowgartField** [comment]
I fix this with `yarn add @walletconnect/ethereum-provider"

**Comment by brioapp** [comment]
> I fix this with `yarn add @walletconnect/ethereum-provider`. Don't ask me why

I have this package already. no fix.

**Comment by JackShort** [comment]
You have to link this package (@walletconnect/ethereum-provider) as a dependency. Easiest solution: uninstall @web3-react/walletconnect -> install @walletconnect/ethereum-provider -> reinstall @web3-react/walletconnect. Should work.

**Comment by JFrankfurt** [comment]
`yarn add @walletconnect/ethereum-provider` worked for me
