### ISSUE TITLE
Possible bug with the injected connector

### ISSUE THREAD

**Issue by FFBrandynThibault** [NoahZinsmeister/web3-react#384]
I have found that if my user has both MetaMask and Coinbase installed in Chrome the injected connector can't differentiate between the two. Click connect on MetaMask but on refresh the app shows disconnected because it is trying to connect to Coinbase which does't have permissions for the site.

Let me know if this is a bug or if there is something I can do to resolve this issue.

**Comment by NoahZinsmeister** [comment]
ah, yeah if you have 2 extensions that are both injecting `window.ethereum` they're just going to clobber each other unpredictably, and you're never going to get consistent results. you should just make sure that only 1 injecting extension is active at a time!
