### ISSUE TITLE
Desactivate metamask auto-connect

### ISSUE THREAD

**Issue by BowgartField** [NoahZinsmeister/web3-react#385]
Hi, 
I have coded a multi-connection wall on which you can choose which connector you want to use: 
![image](https://user-images.githubusercontent.com/13118844/150983674-b4bdf4a9-f17d-4907-a467-0a6b5dac6d59.png)

However, even if I haven't called `metamaskConnector.activate()` on the metamask connector, it connects automatically. 
In contrast to this issue #330  I would like there to be no order of priority but to be able to choose which one to use.

Do you have any solutions for me?
Thanks :)

**Comment by NoahZinsmeister** [comment]
hi @BowgartField , yes, assuming you're on v8, you may simply pass `false` to the `connectEagerly` parameter! see `https://github.com/NoahZinsmeister/web3-react/blob/main/packages/metamask/src/index.ts#L34`. this will prevent the metamask connector from automatically connecting on page load if it can. let me know if this solves your problem!
