### ISSUE TITLE
v8: Error saying MetaMask doesn't derive from Connector

### ISSUE THREAD

**Issue by etheria-chan** [NoahZinsmeister/web3-react#386]
Getting error that tells me `MetaMask` does not derive from `Connector`, even though peaking the `MetaMask` code shows that it `extends Connector`. This is in a fresh web3-react v8 install.

```
TS2344: Type 'MetaMask' does not satisfy the constraint 'Connector'.
  Property 'actions' is protected but type 'Connector' is not a class derived from 'Connector'.
    2 | import { MetaMask } from '@web3-react/metamask'
    3 |
  > 4 | export const [metaMask, hooks] = initializeConnector<MetaMask>((actions) => new MetaMask(actions))
  ```
  
  And the `MetaMask` index.d.ts:
  
  ```
  export declare class MetaMask extends Connector {
  ```

**Comment by JFrankfurt** [comment]
@etheria-chan I ran into this too, and fixed it by bumping `@web3-react/core` up to `8.0.9-beta.0`

**Comment by JackShort** [comment]
I was able to solve it by upgrading @web3-react/metamask up to 8.0.6-beta.0

**Comment by decryptozoo** [comment]
This still happens for the `EIP1193` connector as of `@web3-react/eip1193` `8.0.23-beta.0`.
