### ISSUE TITLE
Connect to Wallet Connection with @web3-react/walletconnect-connector shows errors "Cannot read properties of undefined (reading 'connected')"

### ISSUE THREAD

**Issue by evansben87** [NoahZinsmeister/web3-react#388]
Hi,
I made connection with Wallet Connection with code bellow but I get error is Cannot read properties of undefined (reading 'connected'). Anyone can help me this issues. Thank you

`import {
    UserRejectedRequestError as UserRejectedRequestErrorWalletConnect,
    WalletConnectConnector,
} from '@web3-react/walletconnect-connector'

import { UnsupportedChainIdError, useWeb3React } from '@web3-react/core'

const connection = async () => {
       const { activate } = useWeb3React();
       const connector = new WalletConnectConnector({
            rpc: { 56: 'https://bsc-dataseed.binance.org/' },
            bridge: 'https://bridge.walletconnect.org',
            qrcode: true,
            pollingInterval: 10000
        })
       await activate(connector, async (error) => {
                if (error instanceof UnsupportedChainIdError) {
                    console.log(error)
                    const network = config.unsupportedChainSetup[config.chainId];
                    const hasSetup = await switchChain(network ?? { chainId: `0x${parseInt(config.chainId.toString()).toString(16)}` })
                    if (hasSetup) {
                        setError(null)
                        await activate(connector, async () => {
                            setError(`${error.message}`)
                        })
                    } else {
                        setError(`Unable to connect to required network ${config.chainId}`)
                    }
                } else {
                    if (error instanceof NoEthereumProviderError || error instanceof NoBscProviderError) {
                        setError('No wallet provider was found')
                    } else if (
                        error instanceof UserRejectedRequestErrorInjected ||
                        error instanceof UserRejectedRequestErrorWalletConnect
                    ) {
                        if (connector instanceof WalletConnectConnector) {
                            connector.walletConnectProvider = null
                        }
                        setError('Please authorize to access your account')
                    } else if ((error as any).code === -32002) {
                        setError(`Already processing wallet connect requuest, please click on wallet to unlock it!`)
                    } else {
                        setError(`${error.message}`)
                    }
                }
            })
        } else {
            setError(`Cannot find connector in the connector config`)
        }

}

`

**Comment by rahulbhadja** [comment]
same issue I'm also unable to connect with WallletConnect provider

**Comment by ricp** [comment]
+1 using version 6.1.9

**Comment by Nikruto** [comment]
+1

**Comment by ricp** [comment]
Downgrading to @walletconnect/ethereum-provider@^1.6.0 fixed the problem for me guys, you probably use 1.7.1

**Comment by rahulbhadja** [comment]
> Downgrading to @walletconnect/ethereum-provider@^1.6.0 fixed the problem for me guys, you probably use 1.7.1 like I did

But we are using @web3-react/walletconnect-connector, I don't get the point of using @walletconnect/ethereum-provider@^1.6.0.

**Comment by Nikruto** [comment]
I changed @web3-react/walletconnect-connector version to ^7.0.2-alpha.0 on package.json then re-run npm install and it is fixed.

**Comment by bhishp** [comment]
downgrading to 6.2.8 worked for me, `yarn upgrade @web3-react/walletconnect-connector@6.2.8`

**Comment by paddyfink** [comment]
I fixed it by changing @web3-react/walletconnect-connector version from "^6.2.8" to simply "6.2.8" ;-)

**Comment by evansben87** [comment]
@paddyfink I downgraded to 6.2.8 but still not working :(

**Comment by evansben87** [comment]
> I changed @web3-react/walletconnect-connector version to ^7.0.2-alpha.0 on package.json then re-run npm install and it is fixed.

yeah, it works perfectly, so I closed this issue. Thank you so much for your support

**Comment by aqibnoborderz** [comment]
Type 'WalletConnect' does not satisfy the constraint 'Connector'.
  Property 'actions' is protected but type 'Connector' is not a class derived from 'Connector'.
  
  getting this issue any sugestions?
