### ISSUE TITLE
Choose which connector to use

### ISSUE THREAD

**Issue by BowgartField** [NoahZinsmeister/web3-react#390]
Hi, 
I'm looking for a way to choose the connector we want to use but with no succes. I have coded this:

      
    import { Web3ReactHooks } from "@web3-react/core";
    import { Connector } from "@web3-react/types";
    import { metaMask, metamaskHooks } from "../connectors/Metamask";
    import { walletConnect, walletConnectHooks } from "../connectors/WalletConnect";

      export enum Connectors{
          METAMASK,
          WALLETCONNECT
      }
      
      export interface Provider{
          connector: Connector
          hooks: Web3ReactHooks
      }
      
      interface Web3React{
          provider: Connector
          getConnector: (choosenConnector: Connectors) => void
          account: ()  => string
      }

    export default function useWeb3React(): Web3React{

        const connectors = new Map<Connectors,Provider>([
            [Connectors.METAMASK,{connector: metaMask, hooks: metamaskHooks}],
            [Connectors.WALLETCONNECT,{connector: walletConnect, hooks: walletConnectHooks}]
        ]);
    
        let account: ()  => string;
        let provider: Connector
    
        const getConnector = (choosenConnector: Connectors) : void => {
    
            const { connector, hooks } = connectors.get(choosenConnector);
    
            account = hooks.useAccount;
            provider = connector;
    
            console.log(provider.activate())
    
        }
    
        return{
            provider,
            getConnector,
            account
        }

    }

When i tried to `.activate` after `getConnector`, i got this error:
![image](https://user-images.githubusercontent.com/13118844/151246832-31ef781d-7dbb-44f2-957b-2b2e4f5f1ddc.png)

Any ideas ?

**Comment by NoahZinsmeister** [comment]
sounds like you need something like `getPriorityConnector` (https://github.com/NoahZinsmeister/web3-react/blob/main/packages/core/src/index.ts#L53)

see https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example/components/connectors/PriorityExample.tsx for example usage

**Comment by BowgartField** [comment]
> sounds like you need something like `getPriorityConnector` (https://github.com/NoahZinsmeister/web3-react/blob/main/packages/core/src/index.ts#L53)
> 
> see https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example/components/connectors/PriorityExample.tsx for example usage

Hmm that's not really about priority it's about choose which one we want to use. More like a getSelectedConnector

**Comment by NoahZinsmeister** [comment]
ah, i see!

here's one idea: what if there was a version of `getPriorityConnector` (i like your idea of `getSelectedConenctor`) that basically did exactly the same thing, but each hook had an additional `connector: Connector` argument that selected the hook for that connector?

**Comment by NoahZinsmeister** [comment]
ok check out https://github.com/NoahZinsmeister/web3-react/blob/c3584a3c416a2f5062adbb121e5e83fab8f2407d/packages/core/src/index.ts#L54, does this address your needs?

**Comment by BowgartField** [comment]
Yes it's look like what I think about. Do you have any exemple how to use it ?

**Comment by NoahZinsmeister** [comment]
it's basically the same as https://github.com/NoahZinsmeister/web3-react/blob/c3584a3c416a2f5062adbb121e5e83fab8f2407d/packages/example/components/connectors/PriorityExample.tsx#L20 !

something like this:

```typescript
const { useSelectedChainId } = getSelectedConnector([metaMask, metaMaskHooks], [network, networkHooks])
function MyComponent() {
  const metaMaskChainId = useSelectedChainId(metaMask)
  const networkChainId = useSelectedChainId(network)
}
```

**Comment by BowgartField** [comment]
Thanks !
