### ISSUE TITLE
v8: MetaMask always shows 'isActivating: true'

### ISSUE THREAD

**Issue by brioapp** [NoahZinsmeister/web3-react#391]
CRA, fresh install, all code copied from 'example' package. 

![cra](https://user-images.githubusercontent.com/1852808/151444634-bd102538-c17e-4ad7-92e4-6b86ba0e19eb.png)

**Comment by NoahZinsmeister** [comment]
hm, can you repro this in the "official" example, either hosted or localhost?

are you sure you have metamask installed and there's no pending connection request?

**Comment by brioapp** [comment]
The official example (NextJs) works fine on my local machine without problems. 

But when I run the 'example' with CRA, the first click can be connected normally, and then manually disconnected in the MetaMask extension panel, refresh the page, it shows that it is 'isActivating', and tried many times in two CRA based repos, one fresh install and one dev repo. 

Here is my test(CRA config ejected): https://github.com/brioapp/web3-react-cra-test

**Comment by brioapp** [comment]
Something is not compatible with CRA? Can you create a CRA based example?

**Comment by NoahZinsmeister** [comment]
weird that a CRA incompatibility would be causing something like this, but yeah i can investigate

**Comment by brioapp** [comment]
> weird that a CRA incompatibility would be causing something like this, but yeah i can investigate

Do you have time to fix it?

**Comment by brioapp** [comment]
React.lazy() solved it.

**Comment by bard** [comment]
I'm encountering the same. @brioapp how did you use React.lazy() to solve this?

**Comment by bard** [comment]
@NoahZinsmeister it seems to be a race condition, and importing modules dynamically (as in the example, or via `React.lazy`) masquerades it. The following triggers the problem (drop it into a `create-react-app` project and export `AppWithRaceCondition` or `AppWithWorkaround`; sorry for lack of proper repro):

```ts
import React, { useEffect, useState, useMemo } from "react";
import { initializeConnector } from "@web3-react/core";
import { MetaMask } from "@web3-react/metamask";

const AppWithRaceCondition: React.FC = () => {
  const connectInfo = useMemo(
    () => initializeConnector<MetaMask>((actions) => new MetaMask(actions)),
    []
  );

  return (
    <div className="App">
      <ConnectMetamask connectInfo={connectInfo} />
    </div>
  );
};

const AppWithWorkaround: React.FC = () => {
  const [connectInfo, setConnectInfo] = useState<ReturnType<
    typeof initializeConnector
  > | null>(null);

  useEffect(() => {
    setTimeout(() => {
      setConnectInfo(
        initializeConnector<MetaMask>((actions) => new MetaMask(actions))
      );
    }, 1000);
  }, []);

  if (!connectInfo) return <div>Delaying...</div>;

  return (
    <div className="App">
      <ConnectMetamask connectInfo={connectInfo} />
    </div>
  );
};

const ConnectMetamask: React.FC<{
  connectInfo: ReturnType<typeof initializeConnector>;
}> = ({ connectInfo }) => {
  const [connector, hooks] = connectInfo;

  const {
    useChainId,
    useAccounts,
    useError,
    useIsActivating,
    useIsActive,
    useProvider,
    useENSNames,
  } = hooks;

  const chainId = useChainId();
  const accounts = useAccounts();
  const error = useError();
  const isActivating = useIsActivating();
  const isActive = useIsActive();
  const provider = useProvider();
  const ENSNames = useENSNames(provider);

  const handleConnectClick = () => {
    if (isActivating) return;
    connector.activate();
  };

  return (
    <div>
      <button onClick={handleConnectClick} disabled={isActivating}>
        Connect
      </button>

      <pre>
        {JSON.stringify({
          chainId,
          accounts,
          error,
          isActivating,
          isActive,
          provider,
          ENSNames,
        })}
      </pre>
    </div>
  );
};

export default AppWithWorkaround;
```

**Comment by YueminHu** [comment]
my workaround:
```
const MetaMaskCard = React.lazy(
  () => import("./components/connectors/MetaMaskCard")
);
<Suspense fallback={<div>Loading...</div>}>
          <MetaMaskCard />
        </Suspense>
```
