### ISSUE TITLE
AddEthereumChainParameter argument for WalletConnect

### ISSUE THREAD

**Issue by earthtojake** [NoahZinsmeister/web3-react#394]
WalletConnect wallets are starting to support multiple chains (Polygon, Optimism, Arbitrum, etc), but it looks there isn't support  for adding / switching to those networks in the WalletConnect connector.

E.g. when I try and request `wallet_switchEthereumChain` to Optimism via the WalletConnectProvider it successfully executes in the Rainbow / MetaMask wallets, but throws an error `Invalid chainId 10` after switching and does not update web3-react state.

Hoping this is a pretty easy fix, the logic would look similar to this: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/metamask/src/index.ts#L134-L150

**Comment by NoahZinsmeister** [comment]
oh i didn't realize walletconnect supported `wallet_switchEthereumChain`, happy to add support. would be even happier to review a PR 😛

**Comment by NoahZinsmeister** [comment]
ok i took the liberty of just making the PR: https://github.com/NoahZinsmeister/web3-react/pull/397

still a few rough edges (biggest one i can find is trying to connect to an unsupported network just hangs on most wallets)

lmk what you think!
