### ISSUE TITLE
Don't clear state when switching networks on a connected wallet

### ISSUE THREAD

**Issue by earthtojake** [NoahZinsmeister/web3-react#398]
With multichain connections it would be ideal if `activate` didn't reset the current connection state to`DEFAULT_STATE` if the user is already connected to that wallet and is just trying to switch networks.

E.g. we support transactions on Optimism and Mainnet and sometimes need users to switch between those networks when they are connected, but currently when I recall `activate` it resets the wallet state until I've switched networks.

This is only really noticeable on wallet providers like WalletLink and WalletConnect that have longer connection processes.

**Comment by NoahZinsmeister** [comment]
that's funny, literally just addressed this in my latest commit to #397

definitely agree, if there's an easy way to query current connection state, this is something that should be handled. going to leave this open until we're sure it's handled well in all current connectors!

**Comment by earthtojake** [comment]
This seems to be working on metamask, wc and walletlink!

**Comment by earthtojake** [comment]
This is accounted for on wc and walletlink

**Comment by NoahZinsmeister** [comment]
one consideration here is if it should be possible to detect a "pending" change while a connection is active. right now, network switching is handled in wc and walletlink by short-circuiting network switches, and only updating once the switch was successful or there was an error.

in theory, though, while this switch was pending, we could set the `activating` flag (or something else) without clearing state, and the UI could then reflect this. i'm just a little worried that this state might be too ambiguous, and also i think it might complicate the store logic (e.g. when is this flag cleared? on the first subsequent update?) worth considering though...
