### ISSUE TITLE
WalletLink chainId is incorrectly updating

### ISSUE THREAD

**Issue by earthtojake** [NoahZinsmeister/web3-react#399]
WalletLink connector looks like it's incorrectly updating `chainId`. When I switch to Optimsim network with chainId 10, it reports it as 10 on first render and then updates to 16.

I'm guessing this line is the culprit: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/walletlink/src/index.ts#L7

Current workaround:
```
const _chainId = useSelectedChainId(connector)
const chainId = _chainId === 16 && connector instanceof WalletLink ? 10 : _chainId
```

**Comment by NoahZinsmeister** [comment]
good catch, tbh i think this is a regression in walletlink, but regardless it's fixed in https://github.com/NoahZinsmeister/web3-react/commit/53d57a2742a62c091e2aa5228c29336151a67944 (released as `8.0.9-beta.0`)
