### ISSUE TITLE
Is there a way to use "library" without connecting? 

### ISSUE THREAD

**Issue by pivnyk2005** [NoahZinsmeister/web3-react#403]
Hi! Thanks for your great work! 

Can you please describe, is there a way to use "library" (in my case web3.js) from "useWeb3React" without connecting? As it's undefined while user is not active. 

For example, I have code like this: 
`const { active, library, activate } = useWeb3React();`

But I can't use "library" until I'm not connected via "activate" function.

Thanks in advance!

**Comment by pivnyk2005** [comment]
I have solved it with network-connectork, thanks!

**Comment by thelimpbacon** [comment]
can you give an example on this?
