### ISSUE TITLE
../node_modules/walletlink/dist/index.js Module build failed: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by earthtojake** [NoahZinsmeister/web3-react#404]
Full stack trace:

```
../node_modules/walletlink/dist/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/jakefitzgerald/lyra/lyra-js/node_modules/walletlink/dist/index.js'
```

Disabling SSR, reinstalling node modules, removing nextjs cache don't fix this issue - my workaround was to install walletlink separately but I have a feeling this may be causing a dependency issue related to https://github.com/walletlink/coinbase-wallet-sdk/issues/303

I believe this is related to SSR but I have no way of disabling the error outside of the web3-react package

**Comment by NoahZinsmeister** [comment]
if i'm understanding correctly, this was fixed when you installed `walletlink` explicitly? if so, that's in fact intended behavior, see https://github.com/NoahZinsmeister/web3-react#upgrading-connector-dependencies
