### ISSUE TITLE
Walletconnect provider not working properly above 6.2.4

### ISSUE THREAD

**Issue by Funst3r** [NoahZinsmeister/web3-react#405]
If the flag qr-code: false is set to disable the modal and display the QR Code byself the qr code URL is not returned anymore.
The connection without the modal is not possible anymore after versions ^6.2.4.

Furthermore the connection dosn't close properly when using connector.close() or deactivate().
Using metamask the connection is still alive and can only be terminated by killing it directly.

**Comment by Funst3r** [comment]
Additional info: Close & deactivate seems to be a bug with the walletconnect provider

**Comment by NoahZinsmeister** [comment]
@Funst3r did #429 address this, or are you still having issues?

**Comment by Funst3r** [comment]
Upgrading to v8 let the disconnect work in most cases.
Sometimes the connection is still viewable in the device (e.g. using metamask app) but mostly it is closed properly. 
Thanks
