### ISSUE TITLE
Wallet connect signMessage not working.

### ISSUE THREAD

**Issue by akpro-io** [NoahZinsmeister/web3-react#407]
Signing a message doesn't work with Wallet Connect. It works with MetaMask though.

`const { library, chainId, ...web3React } = useWeb3React()`
`const signature = await library?.getSigner().signMessage('Message')`

It fires signature request on Trust Wallet but after approval, it throws an error with the message "Failed to sign message".

package version
"@web3-react/core": "^6.1.9",
"@web3-react/injected-connector": "^6.0.7",
"@web3-react/walletconnect-connector": "^6.2.4",

**Comment by NoahZinsmeister** [comment]
would accept a bug fix PR for this
