### ISSUE TITLE
react-scripts 5.0 (create react app) breaking walletconnect-connector

### ISSUE THREAD

**Issue by FanManutd** [NoahZinsmeister/web3-react#414]
Hi! I know v6 is not supported now, but still. 
Just do  `npx create-react-app test` and `npm i @web3-react/walletconnect-connector`. 
Dependencies:
![image](https://user-images.githubusercontent.com/90761929/153355482-bfc69b77-2315-459a-bf99-f1d131b0a873.png)
And just import: 
![image](https://user-images.githubusercontent.com/90761929/153355648-7dd7ef69-a8a0-46b9-ba1e-59f6402d6cfc.png)

In total, we have about 70 warnings in the console and actually not working connector. 
![image](https://user-images.githubusercontent.com/90761929/153356159-bbd83eb0-f04c-4e87-b260-d96cc8e94f06.png)

It doesn`t happen with react-scripts 4.0.3.

**Comment by ECNUwyzZL** [comment]
got same errors ..

**Comment by willisk** [comment]
https://github.com/NoahZinsmeister/web3-react/issues/423#issuecomment-1048320063 
might help

**Comment by NoahZinsmeister** [comment]
this should be addressed in the latest `beta` packages, please open another issue if you're still having problems!
