### ISSUE TITLE
Default chainId parameter for Network connector v8

### ISSUE THREAD

**Issue by Breta01** [NoahZinsmeister/web3-react#416]
Hi,

looking into v8 I am missing parameter for setting default chainId of Network connector. Right now it is set by taking first key of `urlMap` parameter (as shown below) which doesn't give much control. I think adding one extra parameter for default chainId to the constructor would be helpful.

https://github.com/NoahZinsmeister/web3-react/blob/151d10002e2dd8793626cf7f3da6261d8c9b5435/packages/network/src/index.ts#L16-L28

Anyways thank you for the great work.

**Comment by NoahZinsmeister** [comment]
available as of @web3-react/network@8.0.8-beta.0!
