### ISSUE TITLE
If a user locks their MetaMask wallet and tries to connect wallet, no MetaMask password window pops up

### ISSUE THREAD

**Issue by addmorebass** [NoahZinsmeister/web3-react#420]
If a user locks their MetaMask wallet, and tries to connect their wallet, there is no pop up window prompting the user for a password.

There is only a notification that displays within the MetaMask extension (no pop up).

It would be much more user friendly if we were able to pop up with the password window if a user clicked 'Connect Wallet' after locking their wallet.

Steps to reproduce:
1. Connect MetaMask wallet to UniSwap
2. Lock MetaMask wallet
3. Try connecting MetaMask wallet again to Uniswap
4. No pop-up appears prompting the user to enter their MetaMask password. User has to be aware of the notification within the browser icon.

**Comment by theCuratorCM** [comment]
Seeing this as well and seeing increased support queries regarding it.

Please fix.

**Comment by addmorebass** [comment]
It's a known MetaMask issue @theCuratorCM @2pmflow. We can close this.

**Comment by addmorebass** [comment]
https://github.com/MetaMask/metamask-extension/issues/13590#issuecomment-1041275782
