### ISSUE TITLE
CJS exports must be suffixed in .cjs for nextjs compat

### ISSUE THREAD

**Issue by zzmp** [NoahZinsmeister/web3-react#424]
With a `.cjs` suffix, these files are treated as ES modules by nextjs:

> index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs"

All packages should name these files `./dist/cjs/index.cjs` instead of `./dist/cjs/index.js`, and update their package.json's accordingly.

See https://nodejs.org/api/esm.html#:~:text=ESM_FILE_FORMAT(url)

**Comment by Carlos7687** [comment]
$ node index.mjs
success!
$ node index # Failure!
Error: Cannot find module
$ node --experimental-specifier-resolution=node index
success!

**Comment by NoahZinsmeister** [comment]
closing as out of scope, problem is solvable by modifying client package.json
