### ISSUE TITLE
V8 Walletconnect disabled QRCode modal - no URI returned

### ISSUE THREAD

**Issue by Funst3r** [NoahZinsmeister/web3-react#429]
I recently upgraded from V6 to V8.
Unfortunatly the URI callback for displaying an QR code instead of using the modal is not been fired anymore.
The register for the WalletConnect connector:

connector.on("URI_AVAILABLE", activateWC)
const activateWC = uri => {
      console.log("New QR code:" + uri)
      setQrCodeUri(uri)
}

Isn't working anymore since the update.
Was anyone able to fix it? Any workaround?

**Comment by Funst3r** [comment]
I figured out an ugly heck to solve this issue. 
Since we are not able to use the emitter on the connector object we can use the original one by casting it the following way:
Thus we can use "qrcode: false" and get an uri returned when activating the connector.

` useEffect(() => {    
    if (!!connector.provider)
    {
      if (connector as WalletConnect)
      {    
      (connector.provider as unknown as WalletConnectProvider).connector.on("display_uri", (err, payload) => {
        const uri = payload.params[0];
        console.log("New QR-Code:" + uri);
        setQrCodeUri(uri)
      });
      }
    }
  },[connector.provider])`

**Comment by NoahZinsmeister** [comment]
oh, that is ugly indeed, sorry about the regression @Funst3r .

i've added an `events` property to the `WalletConnect` connector which will now emit a `"URI_AVAILABLE"` event with the URI whenever `connector.provider` fires a `"display_uri"` event! available as of `@web3-react/walletconnect@8.0.13-beta.0`

for the record, i'm glad that code worked, but it's fragile and i wouldn't recommend it, as `connector.provider` is non-reactive, and can change independently of the react useEffect lifecycle, hence you're not guaranteed that it'll fire when connector changes

**Comment by Funst3r** [comment]
Thank you very much. Your approach is much better. Now i do understand why the QR code is not always changing :)
