### ISSUE TITLE
Getting "invalid json request" when using V8 provider with OpenSea

### ISSUE THREAD

**Issue by Funst3r** [NoahZinsmeister/web3-react#435]
I'm not entirely sure if this issue is related more to opensea or to the V8 of walletconnect. 
The callstack looks like a problem with walletconnect.

Story:
Before the upgrade to V8 and before openseas upgrade to wyvern 2.3 the "createSellOrder" call worked fine.
Now I'm getting this issue only when submitting transactions (with infura + walletconnect) using valid infura & opensea API keys.
Any other get requests to the api using the opensea SDK and web3-react walletconnect provider are working fine. 
All the transaction calls appearing in the infura dashboard as "invalid" calls. Direct signature or sendTransaction calls are working.

If u need any more information or a live demo just DM me.

Request:
![grafik](https://user-images.githubusercontent.com/97366405/155608393-12a6c4bd-4fd8-4287-9142-d16e3708782d.png)

Response:
![grafik](https://user-images.githubusercontent.com/97366405/155608544-66c9ca39-b01f-4817-9df5-58570456eafc.png)

Callstack:
![grafik](https://user-images.githubusercontent.com/97366405/155609082-0c80ca39-fd9d-4857-a5c6-2e42ce221767.png)

Code:
![grafik](https://user-images.githubusercontent.com/97366405/155610854-3a58e45a-ccfd-478f-8391-75f734f27f45.png)

Infura Dashboard:
![grafik](https://user-images.githubusercontent.com/97366405/155611676-edeb03f9-7649-4e22-a02f-0691409befc3.png)

**Comment by NoahZinsmeister** [comment]
this is definitely not related to web3-react

**Comment by Funst3r** [comment]
@NoahZinsmeister sorry but this is defnitly related to web3-react or packages it uses.
I tripple checked it together with an opensea admin. We build two simple testmethods one returning a signature the other returning 400. I used your example code to create the provider. I know how this looks but please have a closer look.
You can hit me on discord any time.

![grafik](https://user-images.githubusercontent.com/97366405/155673415-19176c17-fbdc-4433-bc40-73fcab220cc6.png)
