### ISSUE TITLE
What is the status on Ledger and Trezor connectors for v8?

### ISSUE THREAD

**Issue by DannyFung97** [NoahZinsmeister/web3-react#436]
V6 is great but lately it hasn't been playing well with some dapps, and also Next.js projects due to the breaking change of webpack v4 to v5, at least from what I've heard.

However, I don't see the hardware wallet connectors on V8 yet, I hope to see it soon. :)

**Comment by talentlessguy** [comment]
They probably won't be implemented in favor of more native connectors like MetaMask (you can import both ledger and trezor there)

https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010591863
