### ISSUE TITLE
Add chainId to context

### ISSUE THREAD

**Issue by pcowgill** [NoahZinsmeister/web3-react#44]
See this blog post: [ChainId vs NetworkId? How do they differ on Ethereum?](https://medium.com/@pedrouid/chainid-vs-networkid-how-do-they-differ-on-ethereum-eec2ed41635b) by @pedrouid

**Comment by NoahZinsmeister** [comment]
on it in v6! the current `networkId` is actually already the `chainId`, just not named as such.

let's track in #37
