### ISSUE TITLE
Magic Connector doesn't work in beta

### ISSUE THREAD

**Issue by mmarkell** [NoahZinsmeister/web3-react#444]
I'm sure it's to be expected at this stage, but just wanted to log the expected / current behavior:

Here's how I'm initializing the magic connector.
```ts
export const magicConnector = initializeConnector<MagicConnector>(
  (actions) => {
    return new MagicConnector(actions, {
      apiKey: process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY!,
      // testMode: process.env.NODE_ENV !== "production",
      network: chainIdToNetwork[parseInt(process.env.NEXT_PUBLIC_CHAIN_ID!)],
    });
  },
  [parseInt(process.env.NEXT_PUBLIC_CHAIN_ID!)]
);
```

Right off the bat, this throws a type error:
```
Type 'MagicConnector' does not satisfy the constraint 'Connector'.
  Types of property 'activate' are incompatible.
    Type '(configuration: LoginWithMagicLinkConfiguration) => Promise<string | void | null>' is not assignable to type '(...args: unknown[]) => void | Promise<void>'
```

Then, activation works fine:
```
const [connector] = magicConnector;
await connector.activate({
  email: body.email,
  showUI: true,
});
```

If I want to access the hooks for the context, here's how I'm doing it with the new API:
```
const [connector, hooks] = magicConnector;
const provider = hooks?.useProvider();
```

Unfortunately, even after activating, the provider stays undefined. So it seems like the hook state is not updating.

If you have any recommendations on the way to solve these problems, I'd be happy to open a PR. Just lmk.

Thanks for the library! It's been so helpful over the last year to me.

**Comment by NoahZinsmeister** [comment]
thanks for flagging @mmarkell , you're right that the magic connector is not in a stable/working state. there have been a lot of changes to connectors in general that aren't reflected in the code - going to close in favor of #352, would like to get to this soon!

**Comment by mmarkell** [comment]
@NoahZinsmeister Thanks!

Let me know if you'd like any help or can point me in the right direction (is there another connector i can model on etc)

**Comment by NoahZinsmeister** [comment]
would love the help if you're feeling motivated! each of the metamask/network/wallet{connect,link} connectors is basically production-ready, and all have their little idiosyncrasies that should give you a good sense of the options available
