### ISSUE TITLE
Consider creating a Discord or a Discourse for web3-react users to do community support for each other

### ISSUE THREAD

**Issue by pcowgill** [NoahZinsmeister/web3-react#45]

**Comment by PaulRBerg** [comment]
Even a Telegram would be nice at this stage.

**Comment by NoahZinsmeister** [comment]
this is a good idea, will start thinking about this as we get closer to the v6 release

**Comment by pcowgill** [comment]
My vote would be Discourse so that the evergreen, useful information can bubble up to the top.

**Comment by NoahZinsmeister** [comment]
going to close this for the time being 😛 

rest assured i still want there to be lots of communication around the project, but i'm fairly swamped on existing channels, and would prefer to use github issues as the primary discussion channel for web3-react.

i also think a lot of issues people have that a chat might help with could also be solved by better docs, so this is an incentive to do that!

**Comment by PaulRBerg** [comment]
"i'm fairly swamped on existing channels"

Oh boy it's the same for all of us. Gotta to some detox soon.

"i also think a lot of issues people have that a chat might help with could also be solved by better docs, so this is an incentive to do that!"

+1 for this. Docs would help a lot. For Sablier, I integrated web3-react by blindly following your latest commits on uniswap-frontend.
