### ISSUE TITLE
Not getting success callback/receipt transaction with walletconnect-connector

### ISSUE THREAD

**Issue by nguy3nds** [NoahZinsmeister/web3-react#451]
**Expected behaviour**

- It should give a success callback & receipt if used with WalletConnectConnector

**Actual behaviour**

```
const { library } = useWeb3React<Web3Provider>();
const signer = await library.getSigner()
const Pool = Pool__factory.connect(currentPoolAddress, signer)
const txn = await Pool.swap(
   ...
  )
const receiptTxn = await txn.wait();
```

It never gets called with WalletConnectConnector but always gets called with InjectedConnector

**Steps to reproduce the behaviour**

1. Connect wallet by scanning QR code with Metamask mobile or WalletConnect supported wallet app
2. Do any contract interaction Txn
3. See if its calling final success callback with receipt

**Logs**

**Environment**

walletconnect-connector: ^6.1.1
web3-react/core: ^6.0.9
web3-react/injected-connector: ^6.0.7
Node: v14.17.1
OS: Mac OS 12.0.1

**Comment by NoahZinsmeister** [comment]
unfortunately this almost certainly doesn't have anything to do with web3-react, and is probably due to some idiosyncracy within ethers/walletconnect/etc.
