### ISSUE TITLE
Cannot resolve @coinbase/wallet-sdk in v8

### ISSUE THREAD

**Issue by tinaszheng** [NoahZinsmeister/web3-react#452]
`./node_modules/@web3-react/walletlink/dist/index.js
Module not found: Can't resolve '@coinbase/wallet-sdk' in 'my_app/node_modules/@web3-react/walletlink/dist'`

using create-react-app v4 with web3-react v8
confirmed i'm using the latest version: `"@web3-react/walletlink": "8.0.20-beta.0",`

**Comment by NoahZinsmeister** [comment]
ah yeah - as you can see in https://github.com/NoahZinsmeister/web3-react/blob/main/packages/walletlink/package.json#L30, `@coinbase/wallet-sdk` is in `peerDependencies`, meaning you have to install it yourself - the idea here is to make client package version upgrades more transparent

**Comment by mclc1120664311** [comment]
> 
This link has expired. When I try to install @coinbase/wallet SDK myself, I report an error saying that I can't find this package

Please tell me how to solve this problem. thanks
<img width="593" alt="image" src="https://user-images.githubusercontent.com/48986212/175770804-0979364a-d756-4637-a8c4-d8bd353dd2b1.png">
![image](https://user-images.githubusercontent.com/48986212/175770810-49a4ad0c-b2d5-4d38-b2de-0e975b597a5f.png)

**Comment by berkaycirak** [comment]
peerDependencies are needed for testing and local development while dependencies for production. What will happen when we deploy our project ?
