### ISSUE TITLE
Closing WalletConnect modal leaves example in bad state

### ISSUE THREAD

**Issue by nick** [NoahZinsmeister/web3-react#454]
If I close the WalletConnect modal, I get the error below in the console and no way to retry.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/939/157111910-536e083c-5b51-4535-8ab3-9339218bab17.png">

**Comment by NoahZinsmeister** [comment]
nice catch, this is a walletconnect regression as of `@walletconnect/ethereum-provider@1.7.4`. going to deprecate the web3-react release that bumped to this, and stick to `@walletconnect/ethereum-provider@1.7.1` for now

**Comment by NoahZinsmeister** [comment]
if you want to run it locally, there's a repro branch here: https://github.com/NoahZinsmeister/web3-react/tree/walletconnect-bug-repro

just follow the instructions in the readme and you should be able to replicate

**Comment by NoahZinsmeister** [comment]
ok i reverted the commits / untagged the problematic release - stay tuned!

**Comment by pofulu** [comment]
As a temporary solution, overrides the dependency version used by the package in `package.json` seems to work.

yarn version
```json
"resolutions": {
  "@walletconnect/jsonrpc-provider": "1.0.0"
}
```

pnpm version
```json
"pnpm": {
  "overrides": {
    "@walletconnect/jsonrpc-provider": "1.0.0"
  }
}
```

**Comment by bhavesh1334** [comment]
> As a temporary solution, overriding the dependency version used by the package in `package.json` seems to work.
> 
> for [yarn](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it)
> 
> ```json
> "resolutions": {
>   "@walletconnect/jsonrpc-provider": "1.0.0"
> }
> ```
> 
> for [pnpm](https://pnpm.io/package_json#pnpmoverrides)
> 
> ```json
> "pnpm": {
>   "overrides": {
>     "@walletconnect/jsonrpc-provider": "1.0.0"
>   }
> }
> ```

Nice this worked for me!! 👍

**Comment by nguy3nds** [comment]
What version of @web3-react/walletconnect-connector is the most stable for development now? I'm using v6.2.13, but sometimes I have some problem :(((

**Comment by welps** [comment]
Just to note, we're awaiting fix in https://github.com/WalletConnect/walletconnect-utils/pull/7

**Comment by NoahZinsmeister** [comment]
released the fix in @web3-react/walletconnect@8.0.22-beta.0

**Comment by chronos-ohm** [comment]
Same error with `@walletconnect/web3-provider@1.7.4`

**Comment by johnnyshankman** [comment]
Hey y'all, bringing this back up. It seems `wcProvider.enable();` doesn't return if the user closes the modal.
