### ISSUE TITLE
Add new @web3-react/coinbasewallet package, deprecate @web3-react/walletlink

### ISSUE THREAD

**Issue by jeongmincho** [NoahZinsmeister/web3-react#467]
Hi @NoahZinsmeister! This is JM from CB Wallet. In an attempt to complete the rebrand of Coinbase Wallet SDK from Walletlink, we'd like to add a new package called `@web3-react/coinbasewallet` and update the docs in place of walletlink (like this [PR](https://github.com/NoahZinsmeister/web3-react/pull/465/files)). Would you be able to help us publish this new package as a part of your library? Thank you!

**Comment by NoahZinsmeister** [comment]
done!

**Comment by NoahZinsmeister** [comment]
done!
