### ISSUE TITLE
Performance concerns with v8

### ISSUE THREAD

**Issue by agcty** [NoahZinsmeister/web3-react#470]
The new hooks seem to be less performant compared to the v6 version. Pretty sure this is due to a combination of mapping over the initializedConnectors and calling the connector hooks over and over again and not using a provider anymore that acted as a cache. 

```tsx
function useSelectedAccount(connector: Connector) {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const values = initializedConnectors.map(([, { useAccount }]) => useAccount())
    return values[getIndex(connector)]
  }

function useSelectedIsActive(connector: Connector) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const values = initializedConnectors.map(([, { useIsActive }]) => useIsActive())
  return values[getIndex(connector)]
}

```

Think this leads to a death by thousand cuts as you use more and more hooks.

Little adaption of example-next: 

PriorityExample.tsx
```tsx
export const { usePriorityConnector, usePriorityIsActive, usePriorityProvider } = getPriorityConnector(
  [metaMask, metaMaskHooks],
  [walletConnect, walletConnectHooks],
  [walletLink, walletLinkHooks],
  [network, networkHooks]
)
```

index.tsx
```tsx
import { useState } from 'react'
import MetaMaskCard from '../components/connectors/MetaMaskCard'
import PriorityExample, { usePriorityIsActive, usePriorityProvider } from '../components/connectors/PriorityExample'

export default function Home() {

  const [isActive, setIsActive] = useState(false)
  
  return (
    <>
      <PriorityExample />
      <div style={{ display: 'flex', flexFlow: 'wrap', fontFamily: 'sans-serif' }}>
        <button onClick={() => setIsActive(!isActive)}>Switch</button>

        <MetaMaskCard />
        {/* <WalletConnectCard />
        <WalletLinkCard />
        <NetworkCard /> */}
        {isActive && <Test1/>}
       {!isActive &&  <Test2/>}
      </div>
    </>
  )
}

function Test1() {
  const prov = usePriorityProvider()
  const isActive = usePriorityIsActive()
  console.log({prov1: prov})
  console.log({isActive1: isActive})
  return <div>Test 1</div>
}

function Test2() {
  const prov = usePriorityProvider()
  const isActive = usePriorityIsActive()
  console.log({prov2: prov})
  console.log({isActive2: isActive})
  return <div>Test 2</div>
}
```

As you switch between Test1 and Test2 you'll see a ton of console logs, specifically n connectors + 1. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/12101091/158459854-62e86f0d-3188-4e43-869b-e27485757cf5.png">

This doesn't really fall into weight in little projects but bigger applications become quite slow.

**Comment by agcty** [comment]
Can confirm that using React.Context as a cache layer reduces hook renders drastically.

And I mean it does make sense that renders get reduced, instead of calling the respective hooks in a loop over and over again it only really does it once with then provides that to whichever consumer component might need it. 

```jsx
export function useWeb3React() {
  const { usePriorityWeb3React, usePriorityProvider } = priorityWeb3
  const priorityProvider = usePriorityProvider()
  return usePriorityWeb3React(priorityProvider)
}

const Web3Contextext = createContext<ReturnType<typeof useWeb3React>>(null)

export function Web3Provider({ children }: { children: React.ReactNode }) {
  const values = useWeb3React()
  return (
    <Web3Contextext.Provider value={values}>{children}</Web3Contextext.Provider>
  )
}

export function useWeb3Context() {
  return useContext(Web3Contextext)
}
```

_app.tsx
```jsx
function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <Web3Provider>
      <Web3Manager />
      <Component {...pageProps} />
    </Web3Provider>
  )
}
```

This was really simple to implement and guessing a multitude of people might run into the same issues so I'm thinking it might make sense for web3-react to export an official Provider component that simply calls usePriorityWeb3React and injects that through the provider. 

Been pondering about the idea of different hooks per connector and think it generally makes a lot of sense but I have the feeling most people will use only one connector, the priority connector anyway, that's I think why the usePriority hooks were created in the first place.

There are not many cases where you want to be connected to multiple connectors at the same time in my opinion, but if you do have a need for that you can just use the connector's hooks directly, which would also solve the performance issues in this case.

For the other 99% of cases, I think a Provider component would make life a lot easier especially for people who don't understand what happens behind the scenes in this library.

**Comment by agcty** [comment]
Another option could be to go the zustand route similar to what react-three-fiber does with the useThree hook (https://docs.pmnd.rs/react-three-fiber/api/hooks#selector) given that web3-react already uses zustand under the hood.

Something like:

_app.tsx
```jsx
import { Web3Provider } from "web3-react";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <Web3Provider connectors={connectors}>
      <Component {...pageProps} />
    </Web3Provider>
  )
}

```

core/index.ts
```jsx
const Web3Context = createContext(null)

export function Web3Provider({
  children,
  connectors,
}: {
  children: React.ReactNode
  connectors: [Connector, Web3Hooks][]
}) {
  const { usePriorityStore } = getPriorityConnector(connectors)
  const store = usePriorityStore()
  return <Web3Context.Provider value={store}>{children}</Web3Context.Provider>
}

export function useStore() {
  const store = React.useContext(Web3Context)
  if (!store)
    throw `Web3 hooks can only be used within the Web3Provider component!`
  return store
}

export function useWeb3<T = RootState>(
  selector: StateSelector<RootState, T> = (state) => state as unknown as T,
  equalityFn?: EqualityChecker<T>
) {
  return useStore()(selector, equalityFn)
}

```

Then users would be able to use the useWeb3 hook with zustand selectors.

Here are some relevant code references from fiber: 
https://github.dev/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/hooks.ts#L33
https://github.dev/pmndrs/react-three-fiber/blob/master/packages/fiber/src/web/index.tsx#L136

In any case, I think this library needs some sort of officially exported Provider component that keeps track of the currently active connector. Let me know what you think, would be happy to help with PRs.

**Comment by NoahZinsmeister** [comment]
hey @agcty, thanks for digging in on this! i'm definitely keen to implement some of these perf improvements - i agree that naively using `usePriority*` hooks everywhere isn't ideal if you're perf-sensitive, precisely because of the multiple render issue you pointed out.

at first glance, i'm leaning toward the vanilla react context version version outlined in your second comment. the selector pattern is neat, but i'm worried it's a little too zustand-y. it also introduces the annoyance of having to make sure your selector functions are referentially stable.

if you're feeling up for it, would love to collaborate/do PR review/etc. on an implementation of the context pattern in @web3-react/core!

**Comment by agcty** [comment]
got it, will work on a PR :)

**Comment by agcty** [comment]
@NoahZinsmeister quick update about the PR, pretty much done functionality wise but currently battling with the build tooling 😂 will create a draft pr later today

**Comment by NoahZinsmeister** [comment]
sounds good @agcty ! happy to help out on the tooling side i've done my fair share of lerna-wrangling
