### ISSUE TITLE
Issues getting V8 to work with a app.js file

### ISSUE THREAD

**Issue by Westy-Dev** [NoahZinsmeister/web3-react#477]
I have been following the code in V8 and believe I have a decent understanding of it at this point.

However, I am having issues with what should be provided as context in the app.js file for a nextJs project. This doesn't seem to be in the example project. Originally for V6 I had a component like this:

![image](https://user-images.githubusercontent.com/14790704/159000209-3161f7a9-a483-4949-8e1b-ebeb8880f29f.png)

![image](https://user-images.githubusercontent.com/14790704/159000287-907a0fe0-3c4c-4488-a155-d2b7c8123564.png)

but this context doesn't seem to exist in V8? Unless I am mistaken!

My project currently looks very similar to the example project as I am getting to grips with the new V8 version. How is the context being handled in the example project?

**Comment by agcty** [comment]
This context doesn't exist in v6 just yet, you can take a look at #476 that adds this functionality

**Comment by Westy-Dev** [comment]
Great thanks @agcty , looks like it is coming soon!

**Comment by agcty** [comment]
@Westy-Dev feature has just landed in main! you can look into the ProviderExample in example-next https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example-next/components/ProviderExample.tsx#L33 as a reference
