### ISSUE TITLE
Where is the name of a connector set?

### ISSUE THREAD

**Issue by pcowgill** [NoahZinsmeister/web3-react#48]
Where is the name of a connector set such that it shows up in the context as `connectorName`?

I have this question both for the connectors that are exported by default from this library and for custom connectors. Thanks!

**Comment by pcowgill** [comment]
Is it from the connectors variable that is passed into Web3Provider?

`const connectors = { Injected, Network };`

```
<Web3Provider
  connectors={...}
  libraryName={'ethers.js'|'web3.js'|null}
  ...
>
  ...
</Web3Provider>
```

because that way of defining `connectors` above is equivalent to writing:

```
const connectors = {
  Injected: Injected,
  Network: Network
};
```

**Comment by NoahZinsmeister** [comment]
@pcowgill yes that's right. agreed it's a weird pattern, thinking of eliminating names altogether in v6, or at least moving them into connectors proper as a static function.

**Comment by pcowgill** [comment]
@NoahZinsmeister Which solution did you end up going with?

**Comment by NoahZinsmeister** [comment]
no connector names! connectors are now just passed as objects to `activate`. recognizing connectors is as easy as using a `===` check now

**Comment by pcowgill** [comment]
Nice! I like it.
