### ISSUE TITLE
MetaMask can not disconnect

### ISSUE THREAD

**Issue by falstack** [NoahZinsmeister/web3-react#493]
visit https://matrixworld.org/home and use MetaMask SignIn, click SignOut and refresh page, user status is logout
visit https://web3-react-mu.vercel.app and use MetaMask SignIn, click SignOut and refresh page, user status is **not** logout

web3-react is cool~ but how can i really disconnect with MetaMask?

**Comment by mattparrilla** [comment]
So the connection is actually maintained by the MM extension. If you disconnect from matrixworld.org and open your metamask wallet, you'll see that it still says "connected."

If you want a client side application to remember that a user chose to disconnect, you'll need some way to persist that preference across sessions.

One way to do this is using local storage. I do this myself and if you look at matrixworld.org's local storage, you'll see that they save `chainType="ethereum"` when you connect and remove it when you disconnect. Presumably in their code somewhere if they don't see the `chainType` key in local storage, they do not connect using the MetaMask connector.

**Comment by falstack** [comment]
@mattparrilla thx！
