### ISSUE TITLE
Library breaks with React 18

### ISSUE THREAD

**Issue by agcty** [NoahZinsmeister/web3-react#496]
When upgrading a Next application to React 18, web3-react throws: 

`Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.`

Might be a zustand problem

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/12101091/160844383-6426fff1-a150-40ad-9c25-a5f0b6a29e54.png">

**Comment by NoahZinsmeister** [comment]
hm, i bumped to zustand beta.3 which upgraded to uSES 1.0.0, perhaps that will fix this?

the round of releases with the latest zustand dependency can be seen here: https://github.com/NoahZinsmeister/web3-react/commit/5cd95ddcb0199d09b3f45a3aa2162189f6d92e79

**Comment by NoahZinsmeister** [comment]
i bumped to react 18 [here](https://github.com/NoahZinsmeister/web3-react/commit/3e0a0785f27a1a0413a2f81d2b0669c017bd4bf0) and everything seems to work! closing for now, feel free to open another issue if something still seems broken
