### ISSUE TITLE
Compatibility with upcoming MetaMask breaking changes

### ISSUE THREAD

**Issue by hantuzun** [NoahZinsmeister/web3-react#50]
MetaMask announced to have breaking changes: https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

We will have a window from November 25 to December 16 to update web3-react.

**Comment by NoahZinsmeister** [comment]
@hantuzun yes i saw that! i'd like to aim for that period to release as well :)

already testing out the new APIs locally!

going to close this, let's track in #37
