### ISSUE TITLE
Unable to access provider instance using ether.js

### ISSUE THREAD

**Issue by faith-ware** [NoahZinsmeister/web3-react#500]
I want to use the library.getSigner() function but it is not working.

**Comment by NoahZinsmeister** [comment]
this issue isn't related to web3-react, as you can see the [provider from this library](https://github.com/NoahZinsmeister/web3-react/blob/cb7fc2f417774319fb8d4877e4fecaed5703d1bc/packages/core/src/hooks.ts#L345) is just a Web3Provider, which should expose a signer if the underlying connection method has one
