### ISSUE TITLE
Some of the Metamask functions are deprecated and throwing warnings in the console

### ISSUE THREAD

**Issue by lla-dusk** [NoahZinsmeister/web3-react#508]
Hey there, can you please update the code as per the Metamask doc? 
Some functions are deprecated and it's giving warnings in the console. Attached the warnings screenshot below.

https://docs.metamask.io/guide/ethereum-provider.html#ethereum-send-deprecated

Thank you :)

![unknown](https://user-images.githubusercontent.com/41337166/162125412-9753e094-39fe-4466-bc26-f20ff4fc34f6.png)

**Comment by talentlessguy** [comment]
Please use the v8 `MetaMask` connector instead. It's code is up-to-date.
