### ISSUE TITLE
activate is successful even if user rejects changing the desired network

### ISSUE THREAD

**Issue by markostojanovic087** [NoahZinsmeister/web3-react#509]
[activate function](https://github.com/NoahZinsmeister/web3-react/blob/main/packages/metamask/src/index.ts#L119) does not fail when user rejects changing the desired network.

This sort of feedback is important to have for showing notifications and especially for chaining calls to a flow, to be able to determine if a call failed to stop the flow.

[Here](https://codesandbox.io/s/wonderful-tdd-rv1129?file=/src/App.tsx) is the minimal example demonstrating the issue.

**Comment by markostojanovic087** [comment]
Duplicate of [Issue #504](https://github.com/NoahZinsmeister/web3-react/issues/504).

**Comment by plutownium** [comment]
@markostojanovic087 you should submit this as documentation on how to use the package. Theres a lot of people asking for it

**Comment by plutownium** [comment]
@markostojanovic087 I'm trying to copy your minimal example to get the *connect to Metamask* functionality.

But I get `Cannot find module '@web3-react/metamask' or its corresponding type declarations.ts(2307)` even though I copied your package.json *exactly*

**Comment by markostojanovic087** [comment]
Verified as fixed! Tested on
![image](https://user-images.githubusercontent.com/19815352/173605626-36a0cbe6-8979-4fa7-ad7e-5cbe85b04542.png)
