### ISSUE TITLE
Outdated WalletLink Code --> Needs to be updated to Coinbase Wallet SDK

### ISSUE THREAD

**Issue by TrevvvD** [NoahZinsmeister/web3-react#535]
Hi,

I work on the DevRel team at Coinbase and am submitting this issue to inform you that the WalletLink SDK has been deprecated in favor of our new [Coinbase Wallet SDK](https://github.com/coinbase/coinbase-wallet-sdk). You can find more on that and how to upgrade to the latest version [here](https://docs.cloud.coinbase.com/wallet-sdk/docs/welcome).

Please let me know if you have any questions!

Thanks,
Trevor

**Comment by NoahZinsmeister** [comment]
https://github.com/NoahZinsmeister/web3-react/tree/main/packages/coinbase-wallet
