### ISSUE TITLE
Selected provider does not get updated when network switched in Metamask

### ISSUE THREAD

**Issue by markostojanovic087** [NoahZinsmeister/web3-react#560]
Selected provider does not get updated when network is switched in Metamask on latest versions.
Since the network change is not properly registered, using the provider can create a damage.

Not working versions:
![image](https://user-images.githubusercontent.com/19815352/170690197-d6a38463-cef7-410f-a466-4766ed2fe816.png)

Working version:
![image](https://user-images.githubusercontent.com/19815352/170690135-367cd14c-6e96-4648-877f-32553aaaf189.png)

Minimal example [here](https://codesandbox.io/s/holy-breeze-hemppn?file=/src/App.tsx).

Repro steps:
- Connect account
- Observe the selected provider network is correct
- Switch network in metamask
- Observe the selected provider network is incorrect

**Comment by AzzouQ** [comment]
Should be fixed in `web3-react/core: 8.0.31`, see #565

**Comment by markostojanovic087** [comment]
Verified, it is fixed on `web3-react/core: 8.0.31-beta.0`!
