### ISSUE TITLE
Cannot connect to opera injected crypto wallet 

### ISSUE THREAD

**Issue by spacehaz** [NoahZinsmeister/web3-react#57]
**Bug Description**
I try to connect to opera crypto wallet (desktop browser) with InjectedConnector, but the only thing I see is an error - TypeError: Cannot read property 'hasOwnProperty' of undefined
The same logic for metamask works great, no problems detected. But connection to opera crypto wallet doesn't work.
Current error was detected with an update of web3-react library update. Previous version connected perfectly with Opera injected crypto wallet, so I think there is some kind of bug

**Reproduction**
https://codesandbox.io/s/web3-react-v6-8rg3h?fontsize=14&hidenavigation=1&theme=dark

Steps to reproduce:
You can open codesandbox link above in Opera Browser with crypto wallet and push the button "Injected" and then you can see an error in the console

**Expected Behavior**
It should return a valid connector provider, not an error

**Additional Context**
Opera browser version: 65.0.3467.78
OS: MacOS Catalina 10.15.1

**Comment by NoahZinsmeister** [comment]
you're right - good catch!

fixed in [6.0.3](https://www.npmjs.com/package/@web3-react/injected-connector/v/6.0.3) :)

**Comment by spacehaz2** [comment]
thanks !!! <3
