### ISSUE TITLE
WalletConnect missed modal popup

### ISSUE THREAD

**Issue by ndangmods** [NoahZinsmeister/web3-react#570]
My code is working good now, in the console of the browser, it printed out the QR Code already but it didn't popup the modal to scan QR
![image](https://user-images.githubusercontent.com/64793476/172144340-321721c6-a9ba-466d-9bf9-10dc3cdd0311.png)
This is my code 
![image](https://user-images.githubusercontent.com/64793476/172144415-ffc02f15-179d-4f5f-ab61-90f753dc4a5f.png)
![image](https://user-images.githubusercontent.com/64793476/172144436-2ee4e434-fa7e-4232-b7a2-23decc4f7b51.png)
![image](https://user-images.githubusercontent.com/64793476/172144494-4fc7171b-8a69-419e-8941-edfa35a84b7c.png)
![image](https://user-images.githubusercontent.com/64793476/172144515-1395e176-5fa1-495e-8cc1-545ddf388be1.png)

**Comment by bitcoinvsalts** [comment]
the qrcode option is not supported in the new version of @web3-react/walletconnect

I am not sure why. @NoahZinsmeister any idea why?

Many people have this issue.

**Comment by bitcoinvsalts** [comment]
@NoahZinsmeister sorry for the misunderstanding. I am trying to replicate with web3-react the same use case than https://www.rainbowkit.com/

On your mobile, if you click on the Metamask option, it will redirect you to the WalletConnect option but without the initial QR modal and offering you the Metamask option directly. Do you see what I mean? And do you think it is possible?

**Comment by bitcoinvsalts** [comment]
@NoahZinsmeister your thought about my comment above would be greatly appreciated as I am stuck on this one. Thank you.

**Comment by rupak-nm** [comment]
@NoahZinsmeister 
What options are exactly needed in `qrcodeModalOptions` inorder to show the modal ?
I don't get any errors but don't see the popup either.

This is my implementation:
```javascript
const [web3WalletConnect, web3WalletConnectHooks] = initializeConnector(
  (actions) => {
    return new WalletConnect({
      actions,
      options: {
        rpc: {
          1: "https://mainnet.infura.io/v3/..."
        },
        qrcode: true,
        bridge: "https://bridge.walletconnect.org",
      },
      onError: (error) => console.log({ wcError: error }),
    });
  }
);

// to activate
async function login(connector) {
  try {
    await connector.activate();
  } catch (error) {
    console.log(`error in connection: ${error}`)
  }
}
```

@ngyhdangg did you find any solution to your problem?
