### ISSUE TITLE
conflict with web3 library in Opera Browser with InjectedConnector

### ISSUE THREAD

**Issue by spacehaz** [NoahZinsmeister/web3-react#58]
**Bug Description**
Detected bug related to that issue: https://github.com/NoahZinsmeister/web3-react/issues/57
Now the previous error disappeared, but I can see a new one: OperaWeb3Provider.sendAsync(request, callback) got 1 arguments

**Reproduction**
The bug happens when you import web3 library somewhere to you application (doesn't matter if you use it or not as a part of getLibrary method of Web3ReactProvider).
here is the example: https://codesandbox.io/s/web3-react-v6-ocmxc
(pay attention to the file src/hooks.js, line 3 where I just imported web3 library previously added to package.json as dependency)

Steps to reproduce:
1. Install web3@1.2.4 to your application
2. Import it somewhere in your application (you can just import it, even not use somewhere)
3. Open application in Opera Desktop Browser (65.0.3467.78 for instance)
4. Try to activate Injected connector

**Expected Behavior**
Expected Behavior is to activate Injected Connector and to avoid error with web3 library installed and used in application

**Additional Context**
Opera Desktop Browser (65.0.3467.78)
MacOS Catalina (10.15.1)

**Comment by NoahZinsmeister** [comment]
ah, unfortunately it looks like this isn't something i can fix. seems like web3 is assuming that window.ethereum.sendAsync has a function signature that it doesn't have in opera.

given the struggles i've had with opera, it's likely that the fix should be on their end. however, it's unclear how this could be accomplished, so in the interim perhaps an issue report in the web3 repo might be a good idea, to put it on their radar.

**Comment by spacehaz** [comment]
@NoahZinsmeister ok, got it! Anyway thanks a lot!

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
