### ISSUE TITLE
Consider making provider packages independent

### ISSUE THREAD

**Issue by chaitanyapotti** [NoahZinsmeister/web3-react#59]
**Description**
Right now, if torus-embed gets a patch release, it requires you to release a new version of web3-react. The better way is for the dapp installing the package to include the corresponding provider package so that updates can be handled better.
What do you think?

**Comment by NoahZinsmeister** [comment]
that's not quite true @chaitanyapotti, for example the current connector works with any `@toruslabs/torus-embed` version matching `^0.2.10` (from [here](https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/torus-connector/package.json#L38)). so, patches will actually be used by default with a reinstall in client codebases. it's only in cases of minors or majors that the connector needs to be updated, and arguably it probably should be updated manually for these types of releases, so this is the correct behavior.

i don't really see a better way of doing this, other than maybe the peer dependencies route, but frankly that seems somewhat unnecessary.

**Comment by chaitanyapotti** [comment]
Okay !
