### ISSUE TITLE
Override default screens?

### ISSUE THREAD

**Issue by michaelhly** [NoahZinsmeister/web3-react#6]
Is it possible to use this module without the default screens?

**Comment by NoahZinsmeister** [comment]
@michaelhly yes! I realized that the default screens were leading to some non-optimal patterns, and have decided to remove them. You can use a version without the screens now via `npm i web3-react@unstable`, though unfortunately it's not documented (the code is in the [`unstable`](https://github.com/NoahZinsmeister/web3-react/tree/unstable) branch). The [latest docs for @next](https://noahzinsmeister.gitbook.io/web3-react/v/next/) may help, but I'm afraid beyond that you'll just have to check out the code.

Hoping to get a fully updated/documented/stable release out pretty soon (within a week or 2), at which point I'll ping you again and close this issue. In the meantime, feel free to let me know if you have any more questions!

**Comment by NoahZinsmeister** [comment]
sorry @michaelhly, i know this is taking longer than i promised. the good news is i've made a lot of progress!

if you're interested in bleeding edge stuff, there's an updated `unstable` build out (available via `yarn add web3-react@unstable`, source code in the [`unstable`](https://github.com/NoahZinsmeister/web3-react/tree/unstable) branch). WIP docs for this release are available on [gitbook](https://noahzinsmeister.gitbook.io/web3-react/v/unstable/).

if not, just hang tight! I'll be cleaning up the rough edges and cutting a stable release soon™!

**Comment by michaelhly** [comment]
Hey. It is no problem at all. I've already been using the unstable version in my project. Love your work!

**Comment by NoahZinsmeister** [comment]
awesome, thanks! let me know if you have any issues/questions with this latest release

**Comment by NoahZinsmeister** [comment]
FYI, the new version is out! `yarn add web3-react@latest`. [Updated docs are on Gitbook](https://noahzinsmeister.gitbook.io/web3-react/).
