### ISSUE TITLE
"Could not find block" thrown from network-provider

### ISSUE THREAD

**Issue by cwhinfrey** [NoahZinsmeister/web3-react#63]
**Bug Description**
Occasionally, the `network-provider`'s `web3-provider-engine` will throw an error with the message "Could not find block". This is due to a block number being returned from Infura for `eth_blockNumber` but `null` being returned for `eth_getBlockByNumber` for the same number.

![Screen Shot 2020-01-21 at 12 00 54 PM](https://user-images.githubusercontent.com/11652019/72843374-41aa8a80-3c4f-11ea-9cfd-56a98e8af892.png)
eth_blockNumber request
![Screen Shot 2020-01-21 at 12 27 16 PM](https://user-images.githubusercontent.com/11652019/72843406-4cfdb600-3c4f-11ea-9fc8-33314ff1ea70.png)
eth_blockNumber response
![Screen Shot 2020-01-21 at 12 27 23 PM](https://user-images.githubusercontent.com/11652019/72843444-61da4980-3c4f-11ea-8d81-e98d5826629f.png)
eth_getBlockByNumber request
![Screen Shot 2020-01-21 at 12 27 06 PM](https://user-images.githubusercontent.com/11652019/72843451-67d02a80-3c4f-11ea-8dba-52bfd3a275af.png)
eth_getBlockByNumber response
![Screen Shot 2020-01-21 at 12 27 30 PM](https://user-images.githubusercontent.com/11652019/72843457-6b63b180-3c4f-11ea-8f41-507d1873db65.png)

**Reproduction**
This is very hard to reproduce as the error is rare. By running the uniswap frontend locally and refreshing every ~15 secs, you may get the error to appear.

Steps to reproduce:
1. run the uniswap frontend locally
2. refresh every ~15 sec

**Expected Behavior**
The error should be caught and logged.

**Additional Context**

**Comment by NoahZinsmeister** [comment]
no longer using web3-provider-engine for the network connector, so this should be fixed
