### ISSUE TITLE
Require syntax error when used with Webpack | Connector: Torus

### ISSUE THREAD

**Issue by RyRy79261** [NoahZinsmeister/web3-react#65]
**Bug Description**
When importing the Torus connector, my webpack is throwing an error to do with internal node modules of Torus.

I'm using react with typescript 3.7+ via webpack

```[HMR] bundle has 1 warnings
client.js?f33d:189 ./node_modules/random-id/index.js 36:14-21Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Expected Behavior**

**Additional Context**
All other connectors work except for Authereum for a different reason

**Comment by chaitanyapotti** [comment]
@RyRy79261 
This is resolved with torus-embed v0.2.14. Please update your package.

**Comment by RyRy79261** [comment]
Epic, thanks!

**Comment by chaitanyapotti** [comment]
Please close the issue @RyRy79261
