### ISSUE TITLE
web3-react does not always update to current chainID

### ISSUE THREAD

**Issue by crazyrabbitLTC** [NoahZinsmeister/web3-react#69]
**Bug Description**
When switching networks, web3React does not always resolve with the current correct NetworkID/ChainID. I found this in our own custom code but noticed the behavior also in the demo code-sandbox. (Screenshot attached). I am unsure what is causing the problem. 

**Reproduction**
[CodeSandbox reproduction]()

Steps to reproduce:
1. 
2. 

**Expected Behavior**
Web3React should return proper ChainId/NetworkId information but sometimes it fails to do so. 

**Additional Context**
<img width="907" alt="Screen Shot 2020-01-29 at 11 17 26 PM" src="https://user-images.githubusercontent.com/1938013/73419675-f9920480-42ed-11ea-8857-df3c1b5b765e.png">

**Comment by NoahZinsmeister** [comment]
Can confirm I'm seeing some weird behavior too. Specifically with Kovan, it seems.

Will try to look into this shortly. It's _possible_ this is a MetaMask/Infura issue.

**Comment by crazyrabbitLTC** [comment]
Thanks! @NoahZinsmeister would you have any suggestions for temporary fixes? Is it possible to force a refresh that would grab the right info? Thanks!

**Comment by NoahZinsmeister** [comment]
FYI, this might be fixed by #71

**Comment by crazyrabbitLTC** [comment]
Unfortunately no, it hasn't be fixed. I'm on a different computer testing and still even on the code-sandbox the network information does not always match Web3React. 
![Screen Shot 2020-02-01 at 11 11 39 AM](https://user-images.githubusercontent.com/1938013/73595200-c1ecad80-44e3-11ea-9b39-9c78a686501f.png)

**Comment by crazyrabbitLTC** [comment]
In our code, when console.logging the output from useWeb3React(), the network information indeed is not accurate. 
![Screen Shot 2020-02-01 at 11 17 51 AM](https://user-images.githubusercontent.com/1938013/73595265-9ddd9c00-44e4-11ea-9793-cd71b2b45389.png)

**Comment by NoahZinsmeister** [comment]
i have to say this really seems like a metamask bug. i haven't yet been able to consistently reproduce any of these errors locally. still working on it.

**Comment by NoahZinsmeister** [comment]
ah, i think i have a fix. give me a few!

**Comment by crazyrabbitLTC** [comment]
So the issue seems to be fixed. Not sure if it was your fix or maybe MetaMask pushed up an update but thank you for your help @NoahZinsmeister !
