### ISSUE TITLE
Unhandled Rejection (Error): This contract object doesn't have address set yet, please set an address first.

### ISSUE THREAD

**Issue by ARUNSAKETH** [NoahZinsmeister/web3-react#75]
![Screenshot (175)](https://user-images.githubusercontent.com/40294421/73681835-288ce980-46e5-11ea-9a23-f35f58bef46f.png)
const context = useWeb3Context();

	const [roles, setRoles] = useState([])
	const [activeTab, setActiveTab] = useState('1')
	const [isLoading, setIsLoading] = useState(true)
	const [logs, setLogs] = useState([])
	const [errMessage, setErrMessage] = useState('')
 

	useEffect(() => {
		if (context.connectorName === undefined) {
			if (window.web3 === undefined) {
				context.setConnector("Infura");
			} else {
				context.setConnector("MetaMask");
			}
		} else {
			if (context != null) {
			const deployedNetwork = SupplyChainContract.abi.networks[context.networkId];
				const supplychainInstance = new context.library.eth.Contract(
					SupplyChainContract.abi,
					deployedNetwork && deployedNetwork.address,
				)
				instance = supplychainInstance
			}
		}
	}, [context])

	useEffect(() => {
    if (instance != null)
      currentAccountRoles()
			setTimeout(() => {
				setIsLoading(false)
			},3000)
			
	}, [context, context.account])

	
	const currentAccountRoles = async () =>{
               // showing error there
		**let myRoles = await instance.methods.whoAmI().call({from: context.account})**
		addToLogs(myRoles)
		const keys = Object.keys(myRoles)
		const values = Object.values(myRoles)
		let updatedRoles = []
		for (var i = 6; i < 12; i++) {
			updatedRoles.push({role: keys[i], isAssgin: values[i]})
		}
		setRoles(updatedRoles)

**Comment by NoahZinsmeister** [comment]
this is an issue with whatever library you're using (web3.js?). you have to instantiate the contract correctly with the deployed contract address.

**Comment by ARUNSAKETH** [comment]
> this

I'm using web3-react

**Comment by ARUNSAKETH** [comment]
> this is an issue with whatever library you're using (web3.js?). you have to instantiate the contract correctly with the deployed contract address.

Can u please explain it in brief !?

**Comment by NoahZinsmeister** [comment]
web3-react doesn't handle how your app communicates with nodes. in your `getLibrary` function you're using (probably) either ethers.js or web3.js. the problem you're having is with this library, not with web3-react. closing as unrelated.
