### ISSUE TITLE
Using web3.js as library + Metamask in browser throws errors in console

### ISSUE THREAD

**Issue by unjapones** [NoahZinsmeister/web3-react#79]
**Bug Description**

When using web3.js as the library instead of ethers, the injected connector and invoking `activate` throws errors on the browser's console. See attached screenshot in "Additional Context".
Although the error arise, web3.js instantiation seems to work kind-of-ok (didn't fully tested the insntiated web3js instance).
This is observable in v6 of web3-react, web3.js 1.2.4, Google Chrome and Firefox with Metamask, in Ubuntu 19.10 (all latest versions). 

**Reproduction**
The following codsandbox uses ethers.js and web3.js in conjuction (in a project I'm working on, a dependency relies on web3.js, so we just want to pass the provider to instantiate it). 
The errors are visible on local development environment, codesandbox will display a different thing so my recommendation is to checkout the example [https://github.com/unjapones/web3-react-ethersjs-web3js-example](https://github.com/unjapones/web3-react-ethersjs-web3js-example) and take a look at it locally.
https://codesandbox.io/s/web3-react-ethersjs-web3js-example-wgg13

Steps to reproduce:
Described in the 1st section of the bug report.

**Should not see the errors in the browser's dev console**

**Additional Context**
![thrown_errors](https://user-images.githubusercontent.com/4421917/74146509-83e93b00-4c01-11ea-89a5-0119091cdccb.png)

**Comment by Caveman07** [comment]
Having the same issue with both ethers.js and web3.js

**Comment by hbarcelos** [comment]
Same issue here, any updates?

**Comment by gabmontes** [comment]
Having same problem here. Any solution or workaround to this?

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
