### ISSUE TITLE
How can I theme `WalletConnectModal`?

### ISSUE THREAD

**Issue by rkhadder** [NoahZinsmeister/web3-react#884]
I've successfully migrated to Wallet Connect v2. I'd like to theme the `WalletConnectModal` that pops up on connect.

<img width="415" alt="Screenshot 2023-09-18 at 1 12 04 PM" src="https://github.com/Uniswap/web3-react/assets/2133003/665e498a-7acb-4779-9b97-8e7d40bd0534">

Specifically I'd like to set the z-index. Theming is supported by wallet connect ([docs](https://docs.walletconnect.com/2.0/advanced/walletconnectmodal/theming)). Is there a way for me to pass theme variables through web3-react?

**Comment by rkhadder** [comment]
Found it :)

```

        qrModalOptions: {
          themeVariables: {
            '--wcm-z-index': '10000',
          },
        },
```

Full web3-react wallet connect v2 props can be found [here](https://github.com/Uniswap/interface/blob/ad9879b4f9df82a7895ea79bcd93508287e0970b/src/connection/WalletConnectV2.ts#L30-L55)

Full wallet connect v2 theme overrides can be found [here](https://docs.walletconnect.com/2.0/advanced/walletconnectmodal/theming)

**Comment by chazzaoui** [comment]
Hey @rkhadder! could I ask you how you set up walletconnectv2 in your project? 

I seem to be getting an error when setting it up and curious if I missed something
