### ISSUE TITLE
Return account info from activate method

### ISSUE THREAD

**Issue by georgeweiler** [NoahZinsmeister/web3-react#91]
**Description**

The async activate function currently resolves `undefined`,  but it would be useful to access the account that was just activated such as `const {account} = await activate(abstractConnector)`

**Comment by Faolain** [comment]
Totally agree @georgeweiler as on my end I'm looking to use control flow via redux-sagas but a prerequisite to doing that would be being able to return the account data. In my particular case I use that data to then generate a new burner wallet (in a corresponding nested `Web3ReactProvider`) and I rather not include this logic into useEffects() on my presentational layer as it is a bit messy.

@NoahZinsmeister out of curiosity is there any reason why the account data is not returned here?  https://github.com/NoahZinsmeister/web3-react/blob/483bc54c8a5e831e3f2ffa42b733ffbbc0fd58b2/packages/core/src/manager.ts#L144 It seems like a pretty simple addition (one-liner) which would then provide the ability to access account data unless I'm missing something with respect to how this works.

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
