### ISSUE TITLE
Don't use `tiny-invariant` for runtime checks.

### ISSUE THREAD

**Issue by MicahZoltu** [NoahZinsmeister/web3-react#92]
https://github.com/NoahZinsmeister/web3-react/blob/2e40aaaabd3f00d3c8286eb1f02b941fc46dd7da/packages/core/src/normalizers.ts#L13

This code is validating inputs from a 3rd party system, which means that it has potential to fail in production rather than in development/testing.  Because of this, the error message that is produced should include a message that usefully allows for debugging the underlying problem.

`tiny-invariant`, by design, strips out all useful error messaging outside of dev builds and thus when a failure occurs in production you have no information available in the error message indicating *what* failed.

Recommended remediation:
Replace `invariant` with something like the following `require` method anywhere that you are validating inputs from an external system (something you cannot assert will always work at dev time).
```ts
function require(condition, message) {
    if (!condition) throw new Error(message)
}
```

**Comment by NoahZinsmeister** [comment]
not using in v8!
