### ISSUE TITLE
Can not integrate walletconnect

### ISSUE THREAD

**Issue by haythem96** [NoahZinsmeister/web3-react#94]
**Bug Description**

I'm trying to implement walletconnect using `web3-react`.
But I get the following error in browser console:
<img width="614" alt="Screen Shot 2020-05-06 at 12 29 54 AM" src="https://user-images.githubusercontent.com/17862704/81125662-bf5d8200-8f30-11ea-89c5-fd3392033210.png">

**Reproduction**

I have the connectors on connectors.ts
```
import { Connectors } from 'web3-react'

import { infuraNetworkURL, supportedNetworkIds } from '../utils/networks'

const { InjectedConnector, NetworkOnlyConnector, WalletConnectConnector } = Connectors

const MetaMask = new InjectedConnector({
  supportedNetworks: supportedNetworkIds,
})

const WalletConnect = new WalletConnectConnector({
  api: infuraNetworkURL,
  bridge: 'https://bridge.walletconnect.org',
  supportedNetworkURLs: {
    '1' : infuraNetworkURL
  },
  defaultNetwork: 1,
})

const Infura = new NetworkOnlyConnector({
  providerURL: infuraNetworkURL,
})

export default {
  Infura,
  MetaMask,
  WalletConnect,
}
```
and a `connect` function in another component that will get called by the button click handler
```
const Web3ReactConnector: React.FC<Props> = props => {
  const context = useWeb3Context()

  const connect = useCallback(
    (connector: string) => {
        context.setConnector(connector)
        setState(ConnectionState.CONNECTING)
        setReadOnly(connector in ReadOnlyConnectors)
    },
    [context],
  )
```

**Comment by NoahZinsmeister** [comment]
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3
